### ISSUE TITLE
InCompatible with PyOxidizer 

### ISSUE THREAD

**Issue by Baneeishaque** [gitpython-developers/GitPython#1002]
See [PyOxidizer Issue 69 : Stop requiring `__file__` in Python packages](https://github.com/indygreg/PyOxidizer/issues/69)

I am trying to use [git-repo-updater](https://github.com/earwig/git-repo-updater) with PyOxidizer.
```
    Finished dev [unoptimized + debuginfo] target(s) in 1m 29s
writing executable to C:\Lab\PyOxidizer\git-repo-updator\.\build\x86_64-pc-windows-msvc\debug\exe\git-repo-updator.exe
>>> from gitup.cli import run
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gitup.cli", line 18, in <module>
  File "gitup.update", line 15, in <module>
  File "git", line 33, in <module>
  File "git", line 22, in _init_externals
NameError: name '__file__' is not defined
>>>
```
git-repo-updater uses GitPython package : [git-repo-updater setup.py](https://github.com/earwig/git-repo-updater/blob/develop/setup.py), [git-repo-updater source file](https://github.com/earwig/git-repo-updater/blob/develop/gitup/update.py)

**Comment by Byron** [comment]
Oh neat, PyOxidizer is a Rust program!

Looking at the documentation, I believe it's possible to detect this case and avoid trying to use __file__.

An update should be released in the next days.
