### ISSUE TITLE
 git.config.GitConfigParser: alias of git.config.GitConfigParser

### ISSUE THREAD

**Issue by haferburg** [gitpython-developers/GitPython#1043]
The documentation doesn't make much sense here: https://gitpython.readthedocs.io/en/stable/reference.html#module-git.config

![image](https://user-images.githubusercontent.com/4941909/88305422-c911ad00-cd09-11ea-9b01-8202430e27c2.png)

**Comment by Byron** [comment]
Don't get me started on that sphinx-generated API documentation, it's quite abysmal!
A quick search through the codebase shows that this is nothing that was explicitly set, so can't be easily fixed.
Any suggestions on how to make it better are welcome.

For now I am closing this issue as there seems nothing that can be done. If there are options you feel like sharing, please follow up in the comments below. Thank you.
