### ISSUE TITLE
init a repo and failed to create_head

### ISSUE THREAD

**Issue by yndlsds** [gitpython-developers/GitPython#105]
I init a new repo, and then use the 'repo.create_head('refs/heads/master')'. But I get a gitdb.exc.Badobject:48454144. This will not be an error somehow. But it triped me.

**Comment by Byron** [comment]
What you have been doing was equivalent to `git branch master`, which fails with `fatal: Not a valid object name: 'master'.` on the commandline as well.
However, I have [added a new test-case](https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_repo.py#L690) to verify gitpython deals with empty repositories gracefully.
In addition to that, the BadObject exception is now a `BadName` exception, which doesn't convert perfectly nice names to some hex, which would just add to the confusion.
