### ISSUE TITLE
repo.active_branch raises TypeError "HEAD is a detached symbolic reference"

### ISSUE THREAD

**Issue by lsaffre** [gitpython-developers/GitPython#1060]
Accessing the repo.active_branch attribute fails In a repository where I previously checked out some earlier commit. Okay I can try...except to catch this, but IMHO this is unexpected behaviour.

**Comment by Byron** [comment]
One can argue that using exception to communicate there is no active branch (as opposed to say, `None`) is an unfortunate decision - exceptions are always surprising and personally I think they should be avoided if the language permits this.

Returning `None` where an exception was returned earlier is a breaking change, I believe there is nothing that can be done here. Thus I close the issue as I find nothing constructive, yet.

However, please feel free to propose or implement an alternative way of doing this via comments or a PR. Thank you
