### ISSUE TITLE
Example on tutorial doesn't work

### ISSUE THREAD

**Issue by derekchiang** [gitpython-developers/GitPython#107]
I tried the example given here: http://pythonhosted.org/GitPython/0.3.2/tutorial.html

When I did this:

```
from git import *
repo = Repo("/Users/mtrier/Development/git-python")
assert repo.bare == False
```

This happened:

Traceback (most recent call last):
  File "git.py", line 1, in <module>
    from git import *
  File "/media/Work_Study/CS/workspace/Python/environments/autover2/git.py", line 2, in <module>
    repo = Repo("/Users/mtrier/Development/git-python")
NameError: name 'Repo' is not defined

**Comment by 92dbajaj** [comment]
Hi, guys, I have installed gitpython on Anaconda using conda, it's been installed properly. Still, I am getting the following error:
 File "search.py", line 59, in <module>
    repo = Repo (Git_Repository)
NameError: name 'Repo' is not defined
Can anyone help, please?

**Comment by hick** [comment]
I got this error to, sth related:

![image](https://user-images.githubusercontent.com/38886/48928793-51302580-ef1d-11e8-8a3d-0ea6240614f7.png)

text version:


D:\hick\python>python git-.py
Traceback (most recent call last):
  File "git-.py", line 6, in <module>
    repo = git.Repo(r'D:\hick')
NameError: name 'git' is not defined

D:\hick\python>pip show GitPython
Name: GitPython
Version: 2.1.11
Summary: Python Git Library
Home-page: https://github.com/gitpython-developers/GitPython
Author: Sebastian Thiel, Michael Trier
Author-email: byronimo@gmail.com, mtrier@gmail.com
License: BSD License
Location: d:\program\python35\lib\site-packages
Requires: gitdb2

D:\hick\python>cat git-.py
'''
操作 git 的演练
'''
from git import Repo

repo = git.Repo(r'D:\hick')

print(repo.bare)


D:\hick\python>python -V
Python 3.5.4

**Comment by smkplus** [comment]
before using **GitPython** make sure you have a repository on path
if you haven't a repository use this command ```git init```
