### ISSUE TITLE
Failed to parse FETCH_HEAD line when fetching "HEAD"

### ISSUE THREAD

**Issue by hawicz** [gitpython-developers/GitPython#1080]
The contents of .git/FETCH_HEAD don't always match [what gitpython expects](https://github.com/gitpython-developers/GitPython/blob/30387f16920f69544fcc7db40dfae554bcd7d1cc/git/remote.py#L298), and an error of the form "ValueError: Failed to parse FETCH_HEAD line: '...'" is thrown.
This can be reproduced with the following commands:

```
git init repo1
cd repo1
echo foo > foo
git add foo
git commit -m foo foo
cd ..
git clone repo1 repo2
cd repo2
python -c 'from git import Repo; r = Repo("."); r.remote().fetch("HEAD")'
```

Given the comments later in that function, I suspect that code could be changed to just set ref_type_name to fetch_note, if fetch_note does not contain any spaces, and it might work ok.

**Comment by Byron** [comment]
Thanks for letting me know, it's great to see a script that helps to reproduce the issue.

Maybe there is more going on though, as running it with the latest version showed 'worked' as such that was no exception.

The contents of FETCH_HEAD in `repo2` is the following:

```
ece840e645a9ed689d164b72d536560c356fdfea		/Users/byron/dev/GitPython/test/repo1
```

In case it matters, I am running this snippet on MacOS, and would be grateful for the contents of the FETCH_HEAD on your end. That should make it easy to create a PR with a test and a fix.

Thank you

**Comment by hawicz** [comment]
Oh, sorry, I'm using an older version of GitPython, 3.1.2 specifically.  It looks like the error parsing FETCH_HEAD is ignored in more recent versions, due to commit a71ebbc11.  I don't know if there's any value in fixing the root cause here, but I think I can get my specific case working just by upgrading.

**Comment by Byron** [comment]
Thanks for your notes - I am also OK with the current solution and believe this issue can be fixed more thoroughly once there is a need for it.
