### ISSUE TITLE
Use of GitKraken in the GitPython organization

### ISSUE THREAD

**Issue by Byron** [gitpython-developers/GitPython#1107]
Hi @Harmon758,

was the access request done by accident? If so, I would deny it.
Otherwise could you state what it will be good for?

Thanks

**Comment by Harmon758** [comment]
I messaged you on Gitter about this.
I think it was already permitted before? because used it previously to push to repositories in the organization.
I use it as my main Git client. Right now, I'm having to switch over to GitHub Desktop or the command line to push.
