### ISSUE TITLE
`universal_newlines` is not respected if git process times out

### ISSUE THREAD

**Issue by x-santiaga-x** [gitpython-developers/GitPython#1116]
In Git.execute if `kill_check.isSet():` then stderr_value will be encoded to bytes even if universal_newlines is set.

**Comment by Byron** [comment]
Can you be more specific as to allow a PR to be created? In that moment I request a change of the subject as well.
This issue isn't currently actionable.

This issue will be reopened once the requested information was provided.

**Comment by x-santiaga-x** [comment]
If we run operation long enough to be killed after timeout and use universal_newlines set to True as this
```
from git.cmd import Git
g = Git(r'/path/to/repo')
g.rev_list('HEAD', kill_after_timeout=1e-6, universal_newlines=True)
```
script execution stopped with traceback

```
Traceback (most recent call last):
  File "../src/test.py", line 28, in <module>
    g.rev_list('HEAD', kill_after_timeout=1e-6, universal_newlines=True)
  File "/venv/path/lib64/python3.6/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/venv/path/lib64/python3.6/site-packages/git/cmd.py", line 1006, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/venv/path/lib64/python3.6/site-packages/git/cmd.py", line 789, in execute
    if stderr_value.endswith(newline):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```

because stderr_value is an error message about timeout decoded to bytes, but with universal_newlines = True newline is str, not bytes.

**Comment by Byron** [comment]
Thanks a lot! This looks like [the logic here](https://github.com/gitpython-developers/GitPython/blob/4a1339a3d6751b2e7c125aa3195bdc872d45a887/git/cmd.py#L786:L788) needs to adhere to the universal newlines flag. Would you be able to submit a PR for a fix?
