### ISSUE TITLE
[Question] How to get HEAD reference from remote repository

### ISSUE THREAD

**Issue by rubenwardy** [gitpython-developers/GitPython#1118]
## Question

Hi,

I have a service which monitors git repos for changes.

I'd like to be able to find out which branch is the default branch without cloning the repo. The way to do this with Git is to check for the [HEAD reference](https://stackoverflow.com/questions/28666357/git-how-to-get-default-branch), which you can do with one of the following commands:

	git ls-remote --symref origin HEAD
	git remote show origin | grep "HEAD branch" | cut -d ":" -f 2

## Attempt

Here is my current code:

```python
def get_commit_hash(git_url, ref_name=None):
	assert ref_name != ""

	git_dir = os.path.join(tempfile.gettempdir(), randomString(10))

	repo = git.Repo.init(git_dir)
	origin: git.Remote = repo.create_remote("origin", url=git_url)
	assert origin.exists()
	origin.fetch()

	if ref_name:
		ref: git.Reference = origin.refs[ref_name]
	else:
		# How to get default branch here?
		ref: git.Reference = None

	return ref.commit.hexsha
```

I've tried:

* `origin.refs.HEAD`
* `origin.refs.head`
* `origin.head`

**Comment by rubenwardy** [comment]
Solution:

```python
def get_commit_hash(git_url, ref_name=None):
	g = git.cmd.Git()
	remote_refs = {}
	for ref in g.ls_remote(git_url).split('\n'):
		hash_ref_list = ref.split('\t')
		remote_refs[hash_ref_list[1]] = hash_ref_list[0]

	if ref_name is None:
		ref_name = "HEAD"

	return remote_refs[ref_name]
```

**Comment by flying-sheep** [comment]
Would be nice to have this as an API.

**Comment by rubenwardy** [comment]
I'm a bit confused about what you mean about HEAD not known? This code has been working in production for 3 years

**Comment by agowa** [comment]
@rubenwardy 
1. Crate a bare repository
2. Add a remote
3. fetch the remote

=> No HEAD symlink exists. It needs to be created manually in this case. `git remote set-head origin -a` would show it. also `git remote show origin` lists it at the top. But it does appear that there is no gitPython command for this.

**Comment by agowa** [comment]
I managed to get it working. For some reason the above git.ls_remote didn't work, but this does: `repo.git.ls_remote("--symref","origin")`, maybe there is something strange with the remote repository or server?
