### ISSUE TITLE
Parsing error on git config

### ISSUE THREAD

**Issue by louisrli** [gitpython-developers/GitPython#112]
The error is below, doing a `config.get_value("user", "name")`

```
File "python-client/client.py", line 53, in <module>
main()
File "python-client/client.py", line 19, in main
user_info = githelpers.get_computer_info()["user"]
File "/home/sagar/dev/meteor/live-git/python-client/githelpers.py", line 35, in get_computer_info
user_name = config.get_value("user", "name")
File "/usr/local/lib/python2.7/dist-packages/git/config.py", line 379, in get_value
valuestr = self.get(section, option)
File "/usr/local/lib/python2.7/dist-packages/git/config.py", line 52, in assure_data_present
self.read()
File "/usr/local/lib/python2.7/dist-packages/git/config.py", line 291, in read
self._read(fp, fp.name)
File "/usr/local/lib/python2.7/dist-packages/git/config.py", line 262, in _read
raise e
ConfigParser.ParsingError: File contains parsing errors: /home/sagar/.gitconfig
[line 149]: '\t\tend\\n\\\n'
[line 150]: '\t\tFile.open(%(%A), %(w)) {|f| f.write(b)}\\n\\\n'
[line 151]: '\t\texit 1 if b.include?(%(<)*%L)\'"\n'
```

It happens on this .gitconfig after line 142. If you remove those parts, then it works fine.

https://github.com/cjhveal/dotfiles/blob/master/git/gitconfig.symlink

**Comment by Byron** [comment]
I am able to reproduce the error and believe the only way to fix it is to use a different/better parser implementation. There seem to be alternatives which are available on pypi as well, and I am confident I will find something suitable.
The config parser part of git-python has been a constant source for grief, and I will be happy to finally fix it.

**Comment by Byron** [comment]
I ended up improving the current (and custom) config parser implementation to the point where it can handle multi-line values correctly. There is a [new test-case](https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_config.py#L76) which verifies that git-python returns exactly the same value as git does.

```bash
it config -f git/test/fixtures/git_config_with_comments --get "merge.railsschema.driver"
ruby -e '
                system %(git), %(merge-file), %(--marker-size=%L), %(%A), %(%O), %(%B)
                b = File.read(%(%A))
                b.sub!(/^<+ .*\nActiveRecord::Schema\.define.:version => (\d+). do\n=+\nActiveRecord::Schema\.define.:version => (\d+). do\n>+ .*/) do
                  %(ActiveRecord::Schema.define(:version => #{[$1, $2].max}) do)
                end
                File.open(%(%A), %(w)) {|f| f.write(b)}
                exit 1 if b.include?(%(<)*%L)'
```

**Comment by Byron** [comment]
Also, just for fun, I have recorded the process of fixing this issue.

* [Fixing 112 PT1/2](http://youtu.be/kHLNXBI40aA)
* [Fixing 112 PT2/2](http://youtu.be/UWy73D0nnj0)
