### ISSUE TITLE
Adding python 3.9, release prior to dropping 3.4.

### ISSUE THREAD

**Issue by Yobmod** [gitpython-developers/GitPython#1132]
#1131 

Hi,
When running the tests after dropping 3.4, I also tested against 3.9 on Linux. All tests passed, so I was thinking to add simply add 3.9. But will probably want final 3.4 release cutting before either are merged?

Dropping 3.4 allows the use of function type hints and async/await coroutines.

Note: According to https://pypistats.org/packages/gitpython python 3.4 downloads are at 0.04% and 3.5 is still at 3.38%

**Comment by Byron** [comment]
Thanks for the great release planning to maximize usability! I wonder if people running 3.9 wouldn't be able to install GitPython just because python 3.9 isn't listed?

If you see issues there, I would be waiting for a PR who adds python 3.9 support before #1131 is merged.

**Comment by Yobmod** [comment]
#1184
I've added 3.9 support. All checks passed.
