### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hjwp** [gitpython-developers/GitPython#114]
Running setup.py egg_info for package gitdb
      Traceback (most recent call last):
        File "<string>", line 16, in <module>
        File "/tmp/pip-build-root/gitdb/setup.py", line 24
          print "Ignored failure when building extensions, pure python modules will be used instead"

Just popping this in here as a placeholder, apologies if I missed this elsewhere  Looks like an interesting project!

**Comment by Byron** [comment]
Python 3.3/3.4 is now supported, next to python 2.6 and 2.7.
The new release v0.3.4 will hit pipy in the course of the day.

**Comment by NotSqrt** [comment]
:gift: :wine_glass:

**Comment by hickford** [comment]
Wahey. Brilliant great work
