### ISSUE TITLE
GitPython does not seem to follow core.autocrlf setting

### ISSUE THREAD

**Issue by jlvermeulen** [gitpython-developers/GitPython#1189]
When I create a commit using repo.index.commit, it commits all the Windows line endings in my local file, even though I have the git option core.autocrlf set to true.

### Steps to reproduce

On a Windows machine, init a new git repo, and commit a file `test.txt` containing the following lines:

```
one
two
three
```

Then run a python script containing the following code:

```python
import git

repo = git.Repo('.')
with open('test.txt', 'a') as f:
	print('four', file = f)

repo.index.add(['test.txt'])
repo.index.commit('Four!')
```

Running `git diff HEAD^1 HEAD` now gives the following diff:

```diff
diff --git a/test.txt b/test.txt
index 4cb29ea..7fbf4d8 100644
--- a/test.txt
+++ b/test.txt
@@ -1,3 +1,4 @@
-one
-two
-three
+one^M
+two^M
+three^M
+four^M
```

However, if I only write a line to the file, but don't programmatically add or commit, I get the following result from git diff, which is what I would expect:

```diff
diff --git a/test.txt b/test.txt
index 4cb29ea..f384549 100644
--- a/test.txt
+++ b/test.txt
@@ -1,3 +1,4 @@
 one
 two
 three
+four
```

Is this an issue with GitPython, or am I using the library incorrectly?

**Comment by Byron** [comment]
Thanks for making this issue easy to understand and to follow, it's much appreciated.

The current `IndexFile` implementation is only quite very basic and must be considered plumbing. No git config settings are examined during its operation leaving it in the hands of the user. This is why there is no automatic conversion.

I recommend [using git directly](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly) for the operations that need git config settings to be respected.

Even though I am closing the issue, please feel free to keep commenting for clarification. Thanks for your understanding.

**Comment by HebaruSan** [comment]
So using gitpython on text files on Windows just isn't workable? Seems like something to re-open and fix, unless some prominent disclaimers are going to be added to the documentation.

**Comment by Byron** [comment]
You are welcome to submit a PR to add this limitation to the [limitations section](https://github.com/gitpython-developers/GitPython#limitations) of the readme, along with the workaround mentioned here. Please feel free to add a new section in the official docs, too (see the .rst files in this repo).

**Comment by HebaruSan** [comment]
OK, I will take a look and see if I can find a way to add that. Probably about a 35% chance of me following all the way through to a pull request given my interest level, experience level, and the other things I have going on, for what it's worth.
