### ISSUE TITLE
gitdb submodule is linked to an unexisting commit

### ISSUE THREAD

**Issue by asavah** [gitpython-developers/GitPython#1211]
```
From https://github.com/gitpython-developers/GitPython
14fc8bd3..651a81de  main       -> origin/main
Fetching submodule git/ext/gitdb
fatal: remote error: upload-pack: not our ref 03ab3a1d40c04d6a944299c21db61cf9ce30f6bb
Errors during submodule fetch:
gitdb
```

https://github.com/gitpython-developers/gitdb/tree/03ab3a1d40c04d6a944299c21db61cf9ce30f6bb returns 404

Please fix your repo to point to a valid gitdb commit.

**Comment by Byron** [comment]
Thanks for letting me know. The issue stemmed from a local commit that wasn't pushed yet. This is fixed now.
