### ISSUE TITLE
API Reference is not properly rendered in https://gitpython.readthedocs.io/en/stable/reference.html

### ISSUE THREAD

**Issue by jayeye** [gitpython-developers/GitPython#1228]
Clicking on the the ["API Reference" link](https://gitpython.readthedocs.io/en/stable/reference.html) gives me this page:
![image](https://user-images.githubusercontent.com/6548192/116010724-cde3f400-a5ee-11eb-96b5-e4ddd7139adb.png)

None of the entries point to additional docs.

**Comment by Byron** [comment]
Thanks for letting me know. Admittedly I have no idea how to fix this, but have a hunch that the newly added types might be causing this - they are by far the biggest and most invasive change.

**Comment by Byron** [comment]
I am closing this ticket in favor of https://github.com/gitpython-developers/GitPython/issues/1235 which is more exhaustive. Please subscribe there to stay informed about progress. Thank you.
