### ISSUE TITLE
Missing tags for 3.1.16 and 3.1.17

### ISSUE THREAD

**Issue by dvzrv** [gitpython-developers/GitPython#1243]
Hi!

Tags are missing for [3.1.16](https://pypi.org/project/GitPython/3.1.16/) and [3.1.17](https://pypi.org/project/GitPython/3.1.17/).

The latest tag in this repo is 3.1.15 which relates to a "yanked" [version on pypi](https://pypi.org/project/GitPython/3.1.15/).

**Comment by Byron** [comment]
Thanks for the reminder and sorry for the hassle. Sometime I should read my own [maintenance guide](https://github.com/gitpython-developers/GitPython#how-to-make-a-new-release). Maybe I am just too used to [cargo-release].
 
The missing tags have been added now.

[cargo-release]: https://github.com/sunng87/cargo-release#cargo-release
