### ISSUE TITLE
incorrect index mode for files which have a mode not in (0644, 0755)

### ISSUE THREAD

**Issue by tmzullinger** [gitpython-developers/GitPython#1253]
A recent [bug report](https://bugzilla.redhat.com/1963954) in Fedora revealed an issue where GitPython creates incorrect index modes for a file added which had mode `0700`.  This is similar to issue #430 which was addressed in commit bebc4f56 (Use correct mode for executable files, 2016-05-19).

I'll push a fix for this momentarily.  This area could certainly use some tests.  The previous commit did not add any tests for me to copy and extend.  I'm happy to try to add some tests, but I'm not sure that I have enough time to bring myself up to speed.  Any help would be more appreciated if we want tests to go along with this change.

A very simple example of the issue is:

```
$ git init -q /tmp/git-test; cd /tmp/git-test ; touch foo ; chmod 700 foo
$ python -c 'import git; repo = git.Repo(); repo.index.add(["foo"])'
$ git ls-files -s
100744 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 0   foo
```

**Comment by Byron** [comment]
Thanks a lot for the report, and sorry for the hassle!

I will continue my reply in the PR.

**Comment by tmzullinger** [comment]
No hassle at all.  Thank you for all your work on GitPython! :)
