### ISSUE TITLE
stale_refs failing due to unhandled "xxxxxx will become dangling!" message

### ISSUE THREAD

**Issue by afeblot** [gitpython-developers/GitPython#1262]
With a repo set up in way that `git remote prune --dry-run origin`returns the following:
```
URL: .... my repo utl...
 * [would prune] origin/some-branch
 * [would prune] origin/some-more-branches
 * [would prune] origin/main
 refs/remotes/origin/HEAD will become dangling!
```
**stale_refs** throws `ValueError: Could not parse git-remote prune result: ' refs/remotes/origin/HEAD will become dangling!'`
I suppose this warning message should just silently be skipped at https://github.com/gitpython-developers/GitPython/blob/main/git/remote.py#L614

**Comment by Byron** [comment]
Thanks for the report. I agree that `GitPython` reacts a bit strongly to unknown input which can always happen given its source.

**Comment by afeblot** [comment]
Thanks for the quick reaction 👍
