### ISSUE TITLE
Nose unsupported, doesnt work with Python 3.10

### ISSUE THREAD

**Issue by Yobmod** [gitpython-developers/GitPython#1287]
3 months until 3.10 is released (Oct 2021), so i've just tried run the test suite on 3.10.0beta4.

Didn't get very far, as Nose does not work on 3.10. The issue was reported during 3.9alpha release, so not going to be fixed or released: https://github.com/nose-devs/nose/issues/1099.

Finally time to move to pytest? Then can use all the plugins! Seems is as easy to move to pytest as Nose2.
If anyone wants to help with that..... ('ve never used Nose before).
https://github.com/pytest-dev/nose2pytest might help?

**Comment by Byron** [comment]
Great, thanks for the upgrade! I think nose was hip when I started this more than a decade ago, and I am happy there is something even better by now.
