### ISSUE TITLE
How to submit lfs files by GitPython

### ISSUE THREAD

**Issue by observerno1** [gitpython-developers/GitPython#1290]
Here is what i wrote,  lfs was not considered

```
            GitRepo   = Repo(Root)
            GitIndex = GitRepo.index

            .....            

            if FilesToSubmit:
                GitIndex.add(FilesToSubmit)
            if FilesToDelete:
                GitIndex.remove(FilesToDelete, working_tree=True, r=True)

            GitNewCommit = GitIndex.commit(SVNCommitMessage, author=Author, commit_date=Time)
```

Then I found it deal wrong to lfs things, such as aaa.exe, though lfs was installed and .exe exception was wrote in .gitattribute
After pushing to gitlab, it seemed to be a normal file in remote repository, not lfs file.

So how can I use the GitRepo.git to submit such lfs files?

**Comment by Byron** [comment]
Using the `index` implementation is not recommended as it's not a complete implementation by any means. Hence it ignores `.gitattributes` and filters, which probably means that `git lfs` among others things aren't handled correctly.

To workaround this, use git directly like so: `GitRepo.git.add(…)`, see [details in the docs](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly).

Even though I am closing the issue, please feel free to keep commenting here.
