### ISSUE TITLE
Import issues in new 3.1.19 release

### ISSUE THREAD

**Issue by PhilipMay** [gitpython-developers/GitPython#1296]
The new 3.1.19 release raises this issue on my site:

![grafik](https://user-images.githubusercontent.com/229382/126778092-11fa8030-49db-4cca-aa9c-899c2641832b.png)

**Comment by Yobmod** [comment]
Typing_extensions needs to be updated to 3.10.0.0.

Or, as the release yanked, upgrading gitpython will actually downgrade you back to 3.1.18.

**Comment by Byron** [comment]
Thanks for reporting. It’s a known issue that will be fixed with one of the next releases.

**Comment by PhilipMay** [comment]
> Thanks for reporting. It’s a known issue that will be fixed with one of the next releases.

Would it maybe better to remove this version from pypi or provide a quick fix?

**Comment by PhilipMay** [comment]
@Byron you close issues that report a bug but are not fixed?

**Comment by Byron** [comment]
Release is yanked for hours.

**Comment by PhilipMay** [comment]
> Release is yanked for hours.

Thanks.

**Comment by Byron** [comment]
You are welcome.
The actual progress of fixing this in an upcoming release are tracked here #1095.
