### ISSUE TITLE
Latest release on GitHub page is not most recent release or matching Pip

### ISSUE THREAD

**Issue by jgstew** [gitpython-developers/GitPython#1326]
The newest release listed on the GitHub page does not actually match the latest stable GitHub release, nor does it match what is currently published in Pip.

From: https://github.com/gitpython-developers/GitPython

![GitHub-GitPython-ReleasesOutdated](https://user-images.githubusercontent.com/2439367/130472031-a70d3a11-d1b1-47e5-b961-e94ed018c746.PNG)

I think the newest release needs published to the "version" of the release, but also "latest"? or something like that. Not certain of the details.

**Comment by jgstew** [comment]
Related:

The [Project description in Pip](https://pypi.org/project/GitPython/) should pull in the [README.md](https://github.com/gitpython-developers/GitPython/blob/main/README.md)

**Comment by Byron** [comment]
<img width="232" alt="Screenshot 2021-08-24 at 09 29 52" src="https://user-images.githubusercontent.com/63622/130540930-cd89a280-faaf-4318-a70b-f47050726a8d.png">

Thanks a lot for the hint - I published the latest now for good measure.

Probably that one will be out of date as I will likely be forgetting this extra step at some point, but a contribution for a github workflow that automates this would certainly be welcome.
