### ISSUE TITLE
Project description in Pip should pull in contents of README.md

### ISSUE THREAD

**Issue by jgstew** [gitpython-developers/GitPython#1327]
The [Project description in Pip](https://pypi.org/project/GitPython/) should pull in the [`README.md`](https://github.com/gitpython-developers/GitPython/blob/main/README.md) by moving the `long_description` in [`setup.py`](https://github.com/gitpython-developers/GitPython/blob/main/setup.py#L98) to `setup.cfg` like:

Example `setup.cfg`
```
[metadata]
long_description = file: README.md
long_description_content_type = text/markdown
```

It probably also makes sense to remove the language from the [`README.md`](https://github.com/gitpython-developers/GitPython/blob/main/README.md) that suggests GitPython is not actively developed anymore since that does not seem to be the case.

Alternatively, there could be a Pip Product Description specific markdown file to use instead of the default `README.md` but I think cleaning up and improve the existing `README.md` a bit and using that for the pip product description makes the most sense.

**Comment by Byron** [comment]
Great, I didn't know this was possible. Maybe you could propose a custom README just for pip that is a digest of the current `README.md` and create a PR for it. Alternatively, it's certainly a good start to have a PR referencing the current README instead.

> It probably also makes sense to remove the language from the README.md that suggests GitPython is not actively developed anymore since that does not seem to be the case.

GitPython is in maintenance mode which means it's living off PR's that are community created. Maybe there are better ways to describe this.

Thanks for your help.

**Comment by Yobmod** [comment]
I tried this when I added the setup.cfg. #1294
But I kept getting pypi complaints about the imported README having restructuredtext mistakes (does pypi convert it to rst?)
So if someone likes writing rst, feel free to do it.

**Comment by Byron** [comment]
Fantastic work, @Yobmod . To me this looks good and is exactly what this issue asks for.
