### ISSUE TITLE
`git status` output has changed in git 1.8.5

### ISSUE THREAD

**Issue by mhobbs-8B** [gitpython-developers/GitPython#133]
In git versions > 1.8.4, the output of *git status* has changed such that the lines no longer have a "#" comment prefix by default. (See status.displayCommentPrefix in http://git-scm.com/docs/git-config) As a result, Repo.untracked_files() no longer parses the lines correctly. It seems that the --porcelain option to *git status* is specifically designed for this type of use.

**Comment by Byron** [comment]
#138 was verified to be working, which should make this a non-issue as well.
