### ISSUE TITLE
No response forever when I want to clone an unavailable repository hosted on GitHub

### ISSUE THREAD

**Issue by mohmehmo** [gitpython-developers/GitPython#1331]
Hi,
When I want to clone an unavailable GitHub repository, GitPython does not return any response or error and remain forever at running status. For instance, you can check this problem using following repository.

https://github.com/shanky1947/Stock-Market-Prediction

Can you please check this issue and let me know how can I address it?

Thanks.

**Comment by Byron** [comment]
Could you provide the exact (or equivalent) GitPython code to reproduce the problem? Which GitPython version was used?

Thanks

**Comment by mohmehmo** [comment]
I am using Python 3.8 and and GitPython 3.1.18
here is the code that I used.
```
from git.repo.base import Repo
Repo.clone_from(repo_url, dir)
```

**Comment by Byron** [comment]
Thanks a lot, here is what I get on OSX.

```
➜  GitPython git:(main) python3
Python 3.8.2 (default, Jun  8 2021, 11:59:35)
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import git
>>> from git.repo.base import Repo
>>> Repo.clone_from("https://github.com/shanky1947/Stock-Market-Prediction", "foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/byron/dev/github.com/gitpython-developers/GitPython/git/repo/base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/Users/byron/dev/github.com/gitpython-developers/GitPython/git/repo/base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "/Users/byron/dev/github.com/gitpython-developers/GitPython/git/util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "/Users/byron/dev/github.com/gitpython-developers/GitPython/git/cmd.py", line 449, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/shanky1947/Stock-Market-Prediction foo
  stderr: 'Cloning into 'foo'...
remote: Repository not found.
fatal: repository 'https://github.com/shanky1947/Stock-Market-Prediction/' not found
```

This happens after a second or so.

Please feel free post more instructions on how to reproduce the issue.  To investigate further, [the GitPython debugging docs](https://gitpython.readthedocs.io/en/stable/tutorial.html#git-command-debugging-and-customization) might be helpful. You could also try to run the git commands it outputs in a terminal and see if the issue can be reproduced there. If so, it's something unrelated to GitPython which in this case shells out the work to `git` itself.
