### ISSUE TITLE
mypy is failing on `from git import Blob`

### ISSUE THREAD

**Issue by pbeza** [gitpython-developers/GitPython#1349]
Why `mypy` is failing when running this code:
```bash
$ cat /tmp/test.py 
from git import Blob

$ mypy /tmp/test.py
/tmp/test.py:1: error: Module "git" has no attribute "Blob"
Found 1 error in 1 file (checked 1 source file)

$ python3 -c "import git; print(git.__version__)"
3.1.23

$ mypy --version
mypy 0.910

$ python3 --version
Python 3.9.7
```
?

I can see that there is a conditional import in [`git/objects/base.py`](https://github.com/gitpython-developers/GitPython/blob/05825dcaaf6bf3de7d7e2bc595ad6dcb145f11e8/git/objects/base.py#L22):
```python
if TYPE_CHECKING:
    from git.repo import Repo
    from gitdb.base import OStream
    from .tree import Tree
    from .blob import Blob
    from .submodule.base import Submodule
    from git.refs.reference import 
```
and it seems that `TYPE_CHECKING` is set to `False` (I guess so based on the above error). Do you know why is that? How to workaround the problem?

**Comment by Byron** [comment]
Thanks for letting us know. If `Blob` was previously available and now it is behind a conditional, this may be an issue that was recently introduced.

However, it looks like it should rather be imported from `git.objects`, and maybe that was also the case [historically](https://gitpython.readthedocs.io/en/3.0.7/search.html?q=Blob&check_keywords=yes&area=default).

**Comment by Yobmod** [comment]
I'll have a look at this in the morning.

But initial thoughts are that the import from .blob is a relative import in the objects module, so that should work. (And mypy is working for me)

**Comment by pbeza** [comment]
> What is test.py? Your own code? Can I see it?

It's a one-liner – see my post above:
```bash
$ cat /tmp/test.py 
from git import Blob
```

> You might just be able to change a mypy setting to get it to pass. E.g allow_reexport = True and strict = False (see the mypy settings in our pyproject.toml.) if using strict, the order of settings also makes a difference).
> 
> If changing the import or mypy settings fixes it, let me know.

I will check it and let you know.

**Comment by tucked** [comment]
### SSCCE
``` sh
python3.7 -m venv venv
venv/bin/pip install GitPython==3.1.24 mypy==0.910
vim sscce.py
```
``` py
import git
git.Repo
```
``` sh
venv/bin/python sscce.py  # runs fine
venv/bin/mypy --strict sscce.py
```
### Expected
> Success: no issues found in 1 source file

### Observed
> sscce.py:2: error: Module has no attribute "Repo"
> Found 1 error in 1 file (checked 1 source file)

### Notes

I suspect this is the same problem as https://github.com/pallets/click/issues/1879 (related: https://github.com/python/mypy/issues/10198).
This is actually called out in https://github.com/gitpython-developers/GitPython/issues/1095#issuecomment-891111515 too.

**Comment by dmtucker** [comment]
What feedback is this waiting on?

**Comment by Byron** [comment]
Thanks for the hint, probably unintended.

**Comment by rra** [comment]
I believe the root cause of this issue is that the top-level `__init__.py` file of the `git` module dynamically constructs `__all__`. mypy relies on `__all__` to know which symbols are intended to be exported and will complain about importing symbols from modules that don't appear to intend to export them (depending on the mypy configuration) because this is normally a bug: depending on an implementation detail of another module that isn't part of its interface and therefore may change.

Unfortunately, if I'm right, the fix may be to explicitly list all of the symbols intended to be exported from `git` instead of dynamically constructing them, which will require some ongoing duplicate bookkeeping when new symbols are added.
