### ISSUE TITLE
git-upload-pack (177 bytes)

### ISSUE THREAD

**Issue by githublaohu** [gitpython-developers/GitPython#1353]
Code
`
url = "https://xxxx:xxxx@gitlab.xxxxx.com/languer/realtime_rec_test.git"
clone = Repo.clone_from(url = url,to_path="../realtime_rec_test")
clone.remote().pull()
`
error
`
Cloning into '../realtime_rec_test'...\nPOST git-upload-pack (177 bytes)\n
`

**Comment by Byron** [comment]
I am closing this issue as in its current state it's not actionable. Please provide exact python + GitPython versions used along with a script to reproduce the issue.

Please feel free to comment here with the required information to have this issue reopened.
