### ISSUE TITLE
Add support for git describe

### ISSUE THREAD

**Issue by jon-armstrong-zz** [gitpython-developers/GitPython#136]
Please consider adding support `git describe` command and its options.

**Comment by nuzz** [comment]
This should probably be somewhere in the documentation. I couldn't find this in the docs so I googled and it lead me here to this closed issue.

**Comment by corydodt** [comment]
Was this feature removed? The sample code no longer works.

**Comment by ogajduse** [comment]
Works for me. Out from Python3 console:
import git
r = git.repo.Repo("./..")
r.git.describe()
'0.0.3-8-g8c66b5c'

**Comment by ankostis** [comment]
Maybe this part of the documents help: [Using git directly](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly).

**Comment by corydodt** [comment]
My bad! I was omitting the `.git.` part of the API.
