### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [gitpython-developers/GitPython#1372]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/GitPython/lokal -name '*.py')
```

**Comment by Byron** [comment]
Thanks for posting. To know what we are talking about, I have run the script, here is the resulting patch:

```patch
diff --git a/git/config.py b/git/config.py
index cbd66022..e5fd7087 100644
--- a/git/config.py
+++ b/git/config.py
@@ -418,7 +418,7 @@ class GitConfigParser(cp.RawConfigParser, metaclass=MetaParserBuilder):
             line = fp.readline().decode(defenc)
             if not line:
                 break
-            lineno = lineno + 1
+            lineno += 1
             # comment or blank line?
             if line.strip() == '' or self.re_comment.match(line):
                 continue
diff --git a/git/ext/gitdb b/git/ext/gitdb
index 03ab3a1d..1c976835 160000
--- a/git/ext/gitdb
+++ b/git/ext/gitdb
@@ -1 +1 @@
-Subproject commit 03ab3a1d40c04d6a944299c21db61cf9ce30f6bb
+Subproject commit 1c976835c5d1779a28b9e11afd1656152db26a68-dirty
diff --git a/git/objects/fun.py b/git/objects/fun.py
index 19b4e525..beacae6d 100644
--- a/git/objects/fun.py
+++ b/git/objects/fun.py
@@ -96,7 +96,7 @@ def tree_entries_from_data(data: bytes) -> List[EntryTup]:
         # byte is NULL, get next 20
         i += 1
         sha = data[i:i + 20]
-        i = i + 20
+        i += 20
         out.append((sha, mode, name))
     # END for each byte in data stream
     return out
@@ -193,7 +193,7 @@ def traverse_trees_recursive(odb: 'GitCmdObjectDB', tree_shas: Sequence[Union[by
             # wrap around, but stop one before our current index, hence
             # ti+nt, not ti+1+nt
             for tio in range(ti + 1, ti + nt):
-                tio = tio % nt
+                tio %= nt
                 entries[tio] = _find_by_name(trees_data[tio], name, is_dir, ii)
 
             # END for each other item data
diff --git a/git/objects/tree.py b/git/objects/tree.py
index 22531895..2d53d9ce 100644
--- a/git/objects/tree.py
+++ b/git/objects/tree.py
@@ -79,21 +79,21 @@ def merge_sort(a: List[TreeCacheTup],
     while i < len(lefthalf) and j < len(righthalf):
         if cmp(lefthalf[i], righthalf[j]) <= 0:
             a[k] = lefthalf[i]
-            i = i + 1
+            i += 1
         else:
             a[k] = righthalf[j]
-            j = j + 1
-        k = k + 1
+            j += 1
+        k += 1
 
     while i < len(lefthalf):
         a[k] = lefthalf[i]
-        i = i + 1
-        k = k + 1
+        i += 1
+        k += 1
 
     while j < len(righthalf):
         a[k] = righthalf[j]
-        j = j + 1
-        k = k + 1
+        j += 1
+        k += 1
 
 
 class TreeModifier(object):
diff --git a/git/repo/fun.py b/git/repo/fun.py
index 1a83dd3d..6c17f8f5 100644
--- a/git/repo/fun.py
+++ b/git/repo/fun.py
@@ -307,7 +307,7 @@ def rev_parse(repo: 'Repo', rev: str) -> Union['Commit', 'Tag', 'Tree', 'Blob']:
             found_digit = False
             while start < lr:
                 if rev[start] in digits:
-                    num = num * 10 + int(rev[start])
+                    num *= 10 + int(rev[start])
                     start += 1
                     found_digit = True
                 else:
diff --git a/test/test_diff.py b/test/test_diff.py
index 9b20893a..8d13a822 100644
--- a/test/test_diff.py
+++ b/test/test_diff.py
@@ -347,7 +347,7 @@ class TestDiff(TestBase):
                             for ct in DiffIndex.change_type:
                                 key = 'ct_%s' % ct
                                 assertion_map.setdefault(key, 0)
-                                assertion_map[key] = assertion_map[key] + len(list(diff_index.iter_change_type(ct)))
+                                assertion_map[key] += len(list(diff_index.iter_change_type(ct)))
                             # END for each changetype
 
                             # check entries
diff --git a/test/test_remote.py b/test/test_remote.py
index 088fdad5..032f3b00 100644
--- a/test/test_remote.py
+++ b/test/test_remote.py
@@ -74,7 +74,7 @@ class TestRemoteProgress(RemoteProgress):
                 assert not message.endswith(', '), "Sanitize progress messages: '%s'" % message
 
         self._stages_per_op.setdefault(op_id, 0)
-        self._stages_per_op[op_id] = self._stages_per_op[op_id] | (op_code & self.STAGE_MASK)
+        self._stages_per_op[op_id] |= (op_code & self.STAGE_MASK)
 
         if op_code & (self.WRITING | self.END) == (self.WRITING | self.END):
             assert message
```

Since the number of changes is low, I wouldn't mind applying the patch without much ado.

Despite that, I hope you don't mind me asking what the actual value proposition is. It doesn't seem to be an improved readability of code, at least not to me. Is it performance? If so, the adjustments in the tree parser might be helpful - gitpython has a few performance tests that could be helpful there. What are the tools that can help making improvements, and will these be worth it?

**Comment by elfring** [comment]
>Since the number of changes is low, I wouldn't mind applying the patch without much ado.

Thanks for such a positive feedback.

:point_right: I suggest to take another look at details from the presented transformation approach (so that inappropriate changes will be excluded).

Example:
```python
                if rev[start] in digits:
                    num = num * 10 + int(rev[start])
```


>…, I hope you don't mind me asking what the actual value proposition is. …

How do you think about to support any collateral evolution according to information from [the Python enhancement proposal 577](https://www.python.org/dev/peps/pep-0577/ "Augmented assignment expressions") (from 2018-05-14)?

**Comment by Byron** [comment]
I am sorry but I don’t understand what’s proposed here, and my question to clarify the value was answered with a question regarding a withdrawn pep.

Thus , and respectfully, I choose to not invest more time here or cause more time expenditure by continued requests. Other maintainers are of course welcome to chime in.

**Comment by elfring** [comment]
Can you accept the explanation from the Python documentation?

“…
In the augmented version, `x` is only evaluated once. Also, when possible, the actual operation is performed _in-place_, meaning that rather than creating a new object and assigning that to the target, the old object is modified instead.
…”

:thought_balloon: Do you accordingly expect positive effects for the software run time characteristics?

**Comment by Byron** [comment]
Of course that's acceptable. The test suite, as stated before, does have performance tests and maybe they indicate an improvement. I do doubt that, but if somebody wants to take the time to prove improvements with a patch like this, a PR is definitely welcome.

**Comment by elfring** [comment]
:thought_balloon: Do any factors hinder the wider application of [functionality which became generally available with Python 2](https://docs.python.org/3/whatsnew/2.0.html#augmented-assignment "Augmented assignments")?
