### ISSUE TITLE
repo.index.add() first argument type accepts os.PathLike but code raises TypeError

### ISSUE THREAD

**Issue by itsayellow** [gitpython-developers/GitPython#1382]
In the docs and in the code types, the first argument for `repo.index.add()` is `Sequence[Union[str, os.PathLike, git.objects.blob.Blob, git.index.typ.BaseIndexEntry, Submodule]]`.
However, actually trying to submit a list of Paths to this argument results in a TypeError, as it seems the code inside `_preprocess_add_items` does not handle Paths.

I think this could be fixed by changing line 611 inside of `_preprocess_add_items` in `base.py` to:
```
 if isinstance(item, str) or isinstance(item, os.PathLike):
```
https://github.com/gitpython-developers/GitPython/blob/fe54118ec07a68d5dc6f6108510cffc55dfca643/git/index/base.py#L611
Since `_to_relative_path()` already accepts pathlike arguments.

**Comment by Byron** [comment]
Thanks a lot for the summary and the suggestion for a fix. A PR is definitely welcome.
