### ISSUE TITLE
Cannot push branch upstream

### ISSUE THREAD

**Issue by aurelien-m** [gitpython-developers/GitPython#1408]
Hello,

I have a strange issue that I have not been able to resolve... It seems to maybe come from my SSH key, but I don't have any issues with it (git in the terminal works fine).

Here's what my code looks like:

```python
git_repo = GitRepo.init(dataset_dir)
git_repo.create_remote("origin", url=git_remote_url)

git_repo.index.add(some_files)

git_repo.index.commit("Initial commit")
git_repo.git.push("--set-upstream", "origin", "master")
```

But at the last line, it breaks with this error:

```bash
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git push --set-upstream origin master
  stderr: 'GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
```

Using `git push --set-upstream origin master` works fine in the terminal. What is going wrong here? Thanks!

**Comment by aurelien-m** [comment]
Update: randomly downgraded to 3.1.17, and it worked :/ I can try upgrading versions from there and see when it breaks, if it helps. By the way, I had this issue on Windows 10 and Ubuntu.

**Comment by aurelien-m** [comment]
One weird thing: restarting my computer or reinstall `gitpython` using `pip` helps...

**Comment by Byron** [comment]
> One weird thing: restarting my computer or reinstall `gitpython` using `pip` helps...

Without knowing what caused the issue, I assume that it's resolved now. There can be a variety of issues with GitPython not being able to use ssh keys as these usually aren't authorized for use. The only way to control this is like so:

```python
ssh_cmd = 'ssh -i id_deployment_key'
with repo.git.custom_environment(GIT_SSH_COMMAND=ssh_cmd):
    git_repo.git.push("--set-upstream", "origin", "master")
```

(_the above is a modified sample from the [GitPython tutorial](https://gitpython.readthedocs.io/en/stable/tutorial.html)_).

Even though I am closing this issue as there is nothing actionable right now, please feel free to keep commenting if there is anything else that might change that.

**Comment by Byron** [comment]
@aurelien-m Just for completeness, does `git_repo.git.push("--set-upstream", "origin", "master")` work the same as the `os.system(…)` invocation proposed above? It is expected to, but offer more convenience and potentially better error reporting.

**Comment by aurelien-m** [comment]
Thanks for coming back to @Byron. Yes, I expect it to behave the same, and it does indeed behave identically.

After a few tests, the following code:
```python
os.system("cd /my/git/repo && git push --set-upstream origin master")
```

Returns the following error (**not all the time**, I'm not able to find what causes this issue):
```
GitLab: The project you were looking for could not be found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

So using `os.system(...)` and `git_repo.git.push(...)` have the same effect and seem to crash identically.

I have finally added a simple `time.sleep(1)` before my unstable code, and it now seems to be much much more stable. After a few tests, I have not had any errors like before. Maybe I'm just having a networking latency issue, and it just needs some time to refresh.
