### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [gitpython-developers/GitPython#1409]
Hey there!

I belong to an open source security research community, and a member (@theworstcomrade) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by JamieSlome** [comment]
Hey @Byron - thanks for your response. You should have received an e-mail from us about 1 hour ago!

You can use the magic URL in our e-mail to view the report or you can see the report directly here:
https://huntr.dev/bounties/8549d81f-dc45-4af7-9f2a-2d70752d8524

It is private and only accessible to maintainers with repository write permissions!

**Comment by Byron** [comment]
After giving it a shot myself, I failed to fix it without breaking tests. It probably needs more work than I am able to commit right now, or somebody more familiar with the matter at hand.

**Comment by JamieSlome** [comment]
@theworstcomrade - would you be able to support with a fix?

**Comment by Byron** [comment]
A fix landed with the release of 3.1.27, resolving this issue.
