### ISSUE TITLE
`git pull` output has changed in git 1.8.5

### ISSUE THREAD

**Issue by migurski** [gitpython-developers/GitPython#142]
I’m seeing new errors resulting from changes to git 1.8.5 output, in [remote.py line 539](https://github.com/gitpython-developers/GitPython/blob/f573b6840509bf41be822ab7ed79e0a776005133/git/remote.py#L539) and [605](https://github.com/gitpython-developers/GitPython/blob/f573b6840509bf41be822ab7ed79e0a776005133/git/remote.py#L605). Looks connected to issues #133 and #138:

```
  File "/Users/migurski/Sites/tmp/CMS/bizarro/repo.py", line 68, in save_working_file
    clone.remotes.origin.pull(branch_name, rebase=True)
  File "/Users/migurski/Sites/tmp/CMS/venv-cms/lib/python2.7/site-packages/git/remote.py", line 605, in pull
    return self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/Users/migurski/Sites/tmp/CMS/venv-cms/lib/python2.7/site-packages/git/remote.py", line 539, in _get_fetch_info_from_stderr
    assert len(fetch_info_lines) == len(fetch_head_info), "len(%s) != len(%s)" % (fetch_head_info, fetch_info_lines)
AssertionError: len(["b2ae1672985fa90a09546504014cf58da122c766\t\tbranch 'f38f44fb-e990-4b72-8a0f-c7994157f6a6' of /var/folders/_0/1_xvzf1d7617_1qnntjkb1zm0000gn/T/bizarro-cqQlQ3\n"]) != len([' * branch            f38f44fb-e990-4b72-8a0f-c7994157f6a6 -> FETCH_HEAD', ' = [up to date]      f38f44fb-e990-4b72-8a0f-c7994157f6a6 -> origin/f38f44fb-e990-4b72-8a0f-c7994157f6a6'])
```

The outputs being compared:

```
b2ae1672985fa90a09546504014cf58da122c766        branch 'f38f44fb-e990-4b72-8a0f-c7994157f6a6' of /var/folders/_0/1_xvzf1d7617_1qnntjkb1zm0000gn/T/bizarro-cqQlQ3
```

…and:

```
 * branch            f38f44fb-e990-4b72-8a0f-c7994157f6a6 -> FETCH_HEAD
 = [up to date]      f38f44fb-e990-4b72-8a0f-c7994157f6a6 -> origin/f38f44fb-e990-4b72-8a0f-c7994157f6a6
```

**Comment by domino14** [comment]
I am using GitPython 0.3.5 and git 1.8.3.4 and this is broken for me. The length of the first thing it's comparing is 812 elements and the second is 811 elements. I don't necessarily want to attach a gigantic list of branch names here but what is the best way to debug this?

**Comment by nefaspartim** [comment]
domino14: Let me take a look on a machine with 1.8.3.4.

**Comment by Byron** [comment]
The reason it may appear broken is that in git-python 0.3.5, the assertion was re-added in a slightly different form. It's meant to prevent Fetch-information to be truncated, which is what would have happened in git-versions prior to that.
Therefore I hoped by putting this assertion to finally learn why it may still fail.

I would be glad if you could help me to reproduce this issue - either by providing me with steps to do it myself or by getting access to the data involved. The latter would be each line in [`my_progress_handler`](https://github.com/gitpython-developers/GitPython/blob/master/git/remote.py#L528) and the entire contents of the [FETCH_HEAD](https://github.com/gitpython-developers/GitPython/blob/master/git/remote.py#L546).

In the meanwhile, to solve your problem, probably even without causing side-effects, you can just remove the assertion in your code, or switch back to git-python 0.3.4.

Please note that I am somewhat hesitant to reopen this issue, as yours is not exactly the same. In case you want to provide the requested information, you could do so in a new issue.

Thank you

**Comment by domino14** [comment]
I wrote a script to parse the two things that it is trying to compare. FETCH_HEAD right now has 813 lines. The output of git fetch (I have not been able to figure out exactly what command it is running, but I'm assuming it's `git fetch --all -v` - is this correct?) has also 813 lines if you ignore the first two lines: `Fetching origin` and  `From github.com:org/repo`

However, the very last branch in FETCH_HEAD is missing in the output, in my case it is this line: 

`a3a81646dd65dfa4b4412c0f3a5fd4183cbaa2e5        not-for-merge   branch 'zendesk' of github.com:org/repo`

It can't find the matching line in the fetch output:

` = [up to date]      zendesk    -> origin/zendesk`

Even though I see the line when I do `git fetch --all -v`, I don't see it in the assert output. Let me know if you need more info. Is there possibly some length limit?

**Comment by domino14** [comment]
I put the above information in a new issue: #232
