### ISSUE TITLE
not possible to send multiple --push-option with remote.push()

### ISSUE THREAD

**Issue by eighthave** [gitpython-developers/GitPython#1463]
I need to programmatically open a merge request using Git Push Options e.g `git push --push-option ci.skip origin test`.  That lets a bot open merge requests by just pushing via GitLab's [Push Options](https://docs.gitlab.com/ee/user/project/push_options.html).  It seems that Python does not allow `kwargs` to have more than one of a given name.  So it is possible to set two push options by using the short and long flags:
```python
git_repo.remotes.origin.push('test-mr', None, o='ci.skip', push_option='merge_request.create')
```
But multiple fails:
```python
>>> git_repo.remotes.origin.push('test-mr', None, o='ci.skip', push_option='merge_request.create', push_option='merge_request.remove_source_branch')
  File "<stdin>", line 1
SyntaxError: keyword argument repeated: push_option
```

This works, but gives no feedback about errors:
```python
git_repo.git.push('-o', 'ci.skip', '-o', 'merge_request.create',
   '-o', 'merge_request.remove_source_branch',
   '-o', 'merge_request.title=Git push option test',
   '-o', 'merge_request.description=https://checkupdates.at.or.at/#/builders/1/builds/3984',
   'origin', 'test-mr')
```

The only solution I found is to use `repo.config_writer()` but that is a pain.  Maybe `remote.push()` could have a new arg `push_options=[]` that accepts a list or a dict?

**Comment by Byron** [comment]
Thanks a lot for letting me know! I see how this is a valid use case and that the current implementation could support it specifically to allow passing multiple `-o` flags to the underlying git command, which isn't currently possible.

I think this could be implemented generically in the underlying command abstraction so that the following becomes possible:

```python
git_repo.remotes.origin.push('test-mr', None, o='ci.skip', push_option='merge_request.create', push_option=['option1', 'optionN', …])
```

Git always repeats the flags, so if a list is passed as option it should be clear that the preceding keyword flag should be repeated.

Actually, when [looking at the code](https://github.com/gitpython-developers/GitPython/blob/main/git/cmd.py#L1139:L1148) I think it should already do it that way.

Can you try the above (i.e. passing a list)?

**Comment by eighthave** [comment]
So a list worked:
```python
git_repo.remotes.origin.push('test-mr', None,
    push_option=['ci.skip', 'merge_request.create', 'merge_request.remove_source_branch', 'merge_request.description=https://checkupdates.at.or.at/#/builders/1/builds/3984'])
```

This is a bit counterintuative if someone is used to thinking about _git_ command lines, since it is one flag with many arguments.  Seems workable though if it was documented, perhaps with an example also.

**Comment by Byron** [comment]
Great to hear! 

Indeed, a documentation update would be great.
Maybe you can submit a PR with an example line [added around here](https://github.com/gitpython-developers/GitPython/blob/ca2cf108522b0a298caf8f32e72df1c6006abcf8/test/test_docs.py#L472:L472).

**Comment by eighthave** [comment]
That looks like a test case, I don't understand how that's related to the docs.  Also, is there already documentation of this behavor of converting list kwargs values into command line args?  I could see a section in the Tutorial only on this topic.  I've used GitPython for years now, and I searched for info on this kwargs conversion, and didn't find the explanation.

**Comment by Byron** [comment]
It's documented mostly with examples, and the test I pointed to is not only run on CI to assure it's working, but also copied to the docs. If you look at both the test and the docs it becomes clearer where an additional example can be placed.

One could also write additional notes [directly in the surrounding documentation](https://github.com/gitpython-developers/GitPython/blob/main/doc/source/tutorial.rst#using-git-directly) or create a separate section like you suggested.
