### ISSUE TITLE
git.types.PathLike is partially unknown for Pylance/mypy

### ISSUE THREAD

**Issue by Predeactor** [gitpython-developers/GitPython#1473]
Hello everyone,

I am using GitPython in my project and I use Pylance/mypy with the strict type checking settings. This setting is pretty important for my project's sanity.

As I've been using methods from GitPython that make uses of paths, I've been getting the following errors:
![mypy raising an error for git.types.PathLike](https://user-images.githubusercontent.com/61093863/180901876-4f47a5a3-697d-4338-8008-77e075d13266.png)
As you can notice, what raises this error is `PathLike[Unknown]`, defined in `git.types.PathLike`. ([Source file & lines](https://github.com/gitpython-developers/GitPython/blob/main/git/types.py#L47-L51))

After further investigation, I've found out that this is because `os.PathLike` is considered as a generic class (Like `typing.List`, `typing.Dict` and so on)
![Image showing PathLike being a generic class](https://user-images.githubusercontent.com/61093863/180902236-75621c2a-fdb5-4bd8-b603-6fb0adef0399.png)

The fix is fairly simple, as it is to simply allow `str` for `PathLike`, which gives this result: `os.PathLike[str]`

![PathLike with the implemented fix](https://user-images.githubusercontent.com/61093863/180902659-51b11455-6150-4596-b866-d36b3ac6a767.png)
![Actual code without any errors](https://user-images.githubusercontent.com/61093863/180902715-5d1fb7af-214a-45eb-96e3-6e442ce13f19.png)
(awesome! This issue's no longer a thing with this fix!)

There has some discussion about the same situation on this StackOverflow page: https://stackoverflow.com/a/69680089/13720113

I can make a PR for fixing this (Of course, with some testing, since there is Python version checks), as long as this issue is approved.

Thank you, hoping this issue get sorted soon!

**Comment by Byron** [comment]
Thanks for bringing this up. I think for correctness, the type should be `os.PathLike[str|bytes]` if this doesn't pose a problem. A PR for that would definitely be welcome, thanks for offering.

**Comment by Predeactor** [comment]
Hi,

I'll try to make a PR by tomorrow to fix this issue, I won't be available
for the next few days after then so hopefully you need anything else from
me!

**Comment by Predeactor** [comment]
So, after digging thing a bit deeper, my error I had in #1474 was because I was trying to convert `git.repo.Repo.working_tree_dir` (With the "corrected" type hint) to a `pathlib.Path` object (Which should implement `os.PathLike` too), but `pathlib.Path` refuses the corrected type hint with `bytes` because `pathlib.Path` does not support bytes when creating a new instance of it.

![image](https://user-images.githubusercontent.com/61093863/182848297-871e70ca-1f3c-4b5d-9bd5-bd311b69ef6a.png)

My wonder here is why, actually, should I add bytes?
I sure would have not questioned if it was all good, but as for right now, I have wonder since `pathlib.Path` does not accept it...

**Comment by Byron** [comment]
Thanks for the follow-up. `bytes` are the correct choice on unix platforms which represent paths as bytes, no encoding can be assumed for that reason which would be the case for paths that are `str`, which in python is an interpreter controlled encoding that can change depending on many factors. It appears that Python made its choice and given the history of encoding errors I have witnessed with GitPython in the past decade I wonder what they are thinking. Now there seems to be no way around it being broken.

Accepting that, then not adding bytes would be the way to go and leaving the PR as is, right? If so, please feel free to remove `bytes` once again and it should be OK to merge. Thank you.
