### ISSUE TITLE
Exception on repo().active_branch.name

### ISSUE THREAD

**Issue by grumpyp** [gitpython-developers/GitPython#1479]
### Setup

Running on `GitPython==3.1.27`

`MacOS monterey`, `Python 3.10.5`

### Reproduce the bug

`git checkout <commit>`  -> leads to a detached HEAD

```
from pathlib import Path
from git import Repo

def repo() -> 'Repo':
    from git import Repo  # type: ignore
    return Repo(Path(__file__).parent, search_parent_directories=True)

repository = repo()
repository.active_branch.name    
```

### Error log

```
❯ python3 test.py
Traceback (most recent call last):
  File "/test.py", line 9, in <module>
    repository.active_branch.name
  File "/venv/lib/python3.10/site-packages/git/repo/base.py", line 797, in active_branch
    return self.head.reference
  File "/venv/lib/python3.10/site-packages/git/refs/symbolic.py", line 294, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '7sfaslkhfuhajkfnjaksdhfc4ede32c'
```

### visual proof

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/75830792/185588493-d8f8066e-5098-4e12-953c-c6f6d0bc002c.png">

**Comment by Byron** [comment]
This is intended behaviour, despite not being 'nice'.

The exception is not just any exception, but it states exactly why there is no active branch:

```
TypeError: HEAD is a detached symbolic reference as it points to '7sfaslkhfuhajkfnjaksdhfc4ede32c'
```

At this point, there is no way to fix this property, but in case you would like to add a new one, like `try_active_branch` or something that returns `None` instead, PRs are always welcome.

**Comment by grumpyp** [comment]
Hi @Byron, probably a fix in the documentation would help users as well.

I was looking for an error in my code for a while until I noticed that it's not my fault.

Thanks.

**Comment by Byron** [comment]
Definitely, if exceptions are used to communicate errors [they should be documented](https://github.com/gitpython-developers/GitPython/blob/6aa7fc525c81681bd7fd42dd1c025cbad92e34d7/git/repo/base.py#L859:L861), and a PR for that is welcome as well.

**Comment by grumpyp** [comment]
@Bryon opened a PR [here](https://github.com/gitpython-developers/GitPython/pull/1481)

For everyone else:

You can prevent the execution of the `Exception` by doing something like this:
```
if repo().head.is_detached:
   print("foo")
```
