### ISSUE TITLE
Commit object should have co-author information

### ISSUE THREAD

**Issue by itsluketwist** [gitpython-developers/GitPython#1480]
It's possible for a commit to have multiple authors, currently the Commit object only gives access to the 'main' author. I'd like to add a method on the Commit object that returns the list of co-authors, by parsing the commit message to find them.

Co-author details: https://github.blog/2018-01-29-commit-together-with-co-authors/

**Comment by Byron** [comment]
Thanks for letting me know about this, it does seem desirable to support returning these as well and a PR is definitely welcome.

**Comment by itsluketwist** [comment]
Issue resolved in [PR1482](https://github.com/gitpython-developers/GitPython/pull/1482), closing! 👌
