### ISSUE TITLE
TypeError: Protocols cannot be instantiated

### ISSUE THREAD

**Issue by namandalsania** [gitpython-developers/GitPython#1494]
The error occurs when the following line of code is run on VSCode:

`streamlit run "filename.py"`

The error can be seen in the following image.
![Screenshot (933)](https://user-images.githubusercontent.com/86463390/190925720-425e9948-b115-4618-b466-76a09a184f23.png)

What can be the issue ? And how to fix it ?

**Comment by Byron** [comment]
From the looks of it it's unclear how GitPython is involved at all.

Generally speaking, if an error related to typing occours, maybe it's possible to turn type-checks off.
