### ISSUE TITLE
Unknown option 'rebase' error

### ISSUE THREAD

**Issue by sgwilliams-ebsco** [gitpython-developers/GitPython#1528]
Hello!

We have a project which uses GitPython to automate interacting with Git for GitOps based deployments. After the 3.1.30 release we started seeing an error in our integration tests:

```bash
failed on setup with "git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v -- origin --rebase
  stderr: 'error: unknown option `rebase''"
```

We believe it was introduced with [this PR](https://github.com/gitpython-developers/GitPython/pull/1518).

The code that is failing is:

```python
repository = _initialize_repository(working_directory, remote_repository_url, token)
repository.remotes['origin'].pull('--rebase')
```

Any help would be greatly appreciated!

**Comment by stsewd** [comment]
Options should be passed as kwargs, the argument from pull() is a git reference (like a branch name).

haven't tested if this works

```
repository.remotes['origin'].pull(rebase='')  # or rebase=True?
```

**Comment by sgwilliams-ebsco** [comment]
Thanks for the quick response! We'll test out the `kwargs` approach and report back.

**Comment by sgwilliams-ebsco** [comment]
We've confirmed that

```
repository.remotes['origin'].pull(rebase='') 
```
and

```
repository.remotes['origin'].pull(rebase=True)
```
both work.

I wonder if this should have a been a bump to the major version since it changes the behavior of several of the core git methods. Admittedly, we were passing the options to the pull command incorrectly.

Anyway, our tests are passing again. 

Thanks for the help!

**Comment by Byron** [comment]
> I wonder if this should have a been a bump to the major version since it changes the behavior of several of the core git methods. 

It's the trade-off between not causing surprises during automated upgrades and protecting unsuspecting uses of GitPython from harm. For critical fixes GitPython will always choose a patch release even if these have the potential to break some users.
