### ISSUE TITLE
commit trailers should be a list instead of a dictionary

### ISSUE THREAD

**Issue by nickbroon** [gitpython-developers/GitPython#1533]
Consider for example this linux kernel commit: https://gitlab.com/linux-kernel/stable/-/commit/1382999aa0548a171a272ca817f6c38e797c458c which has following trailers that include multiple `cc` and `signed-off-by` trailers:

```
Link: https://lore.kernel.org/lkml/7cbe96cf-e0b5-ba63-d1b4-f63d2e826efa@suse.cz/


Cc: stable@vger.kernel.org # 6.1+
Reported-by: default avatarVlastimil Babka <vbabka@suse.cz>
Suggested-by: default avatarLinus Torvalds <torvalds@linux-foundation.org>
Acked-by: default avatarLuigi Semenzato <semenzato@chromium.org>
Cc: Peter Huewe <peterhuewe@gmx.de>
Cc: Jarkko Sakkinen <jarkko@kernel.org>
Cc: James Bottomley <James.Bottomley@HansenPartnership.com>
Cc: Johannes Altmanninger <aclopte@gmail.com>
Signed-off-by: Jason Donenfeld's avatarJason A. Donenfeld <Jason@zx2c4.com>
Signed-off-by: default avatarLinus Torvalds <torvalds@linux-foundation.org>
```

And `git interpret-trailers --parse ...` will return all of these.

However the `trailers()` function returns a dictionary with only the last value for each token.

**Comment by itsluketwist** [comment]
@Byron - happy for me to fix this up? 😄

**Comment by Byron** [comment]
Of course, that would be much appreciated. Thanks for offering.
