### ISSUE TITLE
GitConfigParser().get_values() does not load sections properly.

### ISSUE THREAD

**Issue by kf-novi** [gitpython-developers/GitPython#1534]
To replicate this bug, first do the following in your CLI

```
git config --global --add safe.directory /some/directory/here
```
Then run this python script
```
from git import GitConfigParser
from git.config import get_config_path

config = GitConfigParser(get_config_path("global"), read_only=False)
config.get_values("safe", "directory") # This throws a KeyError
```
There is a workaround:
```
config.get_value("safe", "directory")
config.get_values("safe", "directory") # This works
```

I will be taking a look at the code to see if I can submit a PR for this.

**Comment by Byron** [comment]
Closing as it's fixed by #1555 .

**Comment by larstobi** [comment]
I'm still getting the` KeyError: 'safe'` in version 3.1.43 (using Python 3.12.4), but only if the safe section is not already present in the git config. The above workaround with calling `.get_value()` first still works, though.
@Byron 
#1555

**Comment by Byron** [comment]
Maybe you can contribute a test that reproduces the issue. From there it should be possible to fix the issue for good. Thanks a lot.
