### ISSUE TITLE
Problem when checking for ignored files

### ISSUE THREAD

**Issue by Lightborne** [gitpython-developers/GitPython#1543]
Hello,
I stumbled on an issue that i think calls for an update to the GitPython's `ignored` function.

I have a script that performs certain format checks on all files in a repository.  Simple things like removing trailing whitespace.  This script is written to only run on files that have been added to the repository, and it is written to not run on any untracked or ignored files.

My script generates a list of all the files in the workspace, and then it removes untracked and ignored files from that list.  something like this
    
    self.file_list # all the files in the repo
    self.ignored_files = repo.ignored(self.file_list) # should return all ignored files 

Our company's working environment requires us to run several tools within the workspace that holds the repo.  These tools all put their output into directories that we have ignored with `.gitignore`.  But some of these tools create symbolic links within these directories.

Now, GitPython's implementation of `repo.ignored` is basically a wrapper around git's built in `check-ignore` sub-command.  When you try to check if a file behind a symbolic link is ignored using this sub-command, git throws a fatal error:

    # This is the good case - git correctly tells me that both of these are ignored.
    git check-ignore ignore_file.txt ignore/target/ignore.txt 
    ignore_file.txt
    ignore/target/ignore.txt

    # This is the bad case - git simply bails with a fatal error
    git check-ignore ignore_file.txt ignore/link/ignore.txt 
    fatal: pathspec 'ignore/link/ignore.txt' is beyond a symbolic link

GitPython's `repo.ignored` implementation does not catch this fatal error.  What it does is return an empty list.  

So my script was failing because it was trying to format_check a bunch of stuff that was buried in an ignored directory!

I think what needs to happen is that the `repo.ignored` function needs to be enhanced to raise an exception when git throws this fatal error.  Then, I could trap that exception and parse my file list, removing any entries that are hidden behind symbolic links.

**Comment by Byron** [comment]
Thanks for the detailed description of the issue.

I totally agree that it shouldn't squelch errors, and a PR to address that would be much appreciated.

**Comment by Lightborne** [comment]
Sounds good, I think I can get something put together. 

One question - I cloned the repo and got the pytest requirements installed.  I am seeing some failing tests:

    Results (36.61s):
     405 passed
      10 failed
         - test/test_diff.py:62 TestDiff.test_diff_with_staged_file
         - test/test_docs.py:27 Tutorials.test_init_repo_object
         - test/test_docs.py:210 Tutorials.test_references_and_objects
         - test/test_refs.py:196 TestRefs.test_head_reset
         - test/test_refs.py:575 TestRefs.test_tag_message
         - test/test_remote.py:433 TestRemote.test_base
         - test/test_repo.py:1350 TestRepo.test_do_not_strip_newline_in_stdout
         - test/test_repo.py:1325 TestRepo.test_rebasing
         - test/test_submodule.py:729 TestSubmodule.test_git_submodules_and_add_sm_with_new_commit
         - test/test_submodule.py:711 TestSubmodule.test_list_only_valid_submodules
       2 skipped

Is this normal or do you think I have something messed up on my end?

**Comment by Lightborne** [comment]
Pull request is here:

https://github.com/gitpython-developers/GitPython/pull/1545

**Comment by Byron** [comment]
Thanks a lot!

Closing as the PR was merged.
