### ISSUE TITLE
i was trying to train a yolov5 model when i try to import the training file.py from my folder i had this error

### ISSUE THREAD

**Issue by Ali-abdelrahman23** [gitpython-developers/GitPython#1562]
![Screenshot 2023-03-11 220022](https://user-images.githubusercontent.com/127018905/224509212-3585abbd-fb49-4ff5-957d-b7ea66643a53.png)
![Screenshot 2023-03-11 215928](https://user-images.githubusercontent.com/127018905/224509215-04ef429e-a05e-420c-88f1-cbd4f8117765.png)
![Screenshot 2023-03-11 220001](https://user-images.githubusercontent.com/127018905/224509217-8fb659e0-a1cc-47f6-9110-62560f25a6a3.png)

**Comment by Byron** [comment]
The error message says it all. Besides, you may want to address all issues to the makers of `yolov5` first.
