### ISSUE TITLE
Update Repo.config_reader to support user $HOME/.config/git/config

### ISSUE THREAD

**Issue by jzempel** [gitpython-developers/GitPython#160]
Support for this second user-specific configuration file was added to git in [v1.7.12](https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.12.txt). See [commit comments](https://github.com/git/git/commit/21cf32279120799a766d22416be7d82d9ecfbd04) and [git documentation](https://www.kernel.org/pub/software/scm/git/docs/git-config.html#FILES) for details. Consider adding a "user" [config_level](https://github.com/gitpython-developers/GitPython/blob/11e0a94f5e7ed5f824427d615199228a757471fe/git/repo/base.py#L78) to [Repo.config_reader](https://github.com/gitpython-developers/GitPython/blob/11e0a94f5e7ed5f824427d615199228a757471fe/git/repo/base.py#L335) between "system" and "global".

**Comment by Byron** [comment]
You can see how this was implemented in [this youtube video](http://youtu.be/yOcTjonUcDU).

**Comment by jzempel** [comment]
@Byron thanks for the fix & the video. I think you're close. But it's not quite right.

Your code would be looking for either `$XDG_CONFIG_HOME/.config/git/config` or `$HOME/.config/git/config`. Per the git documentation, it should be `$XDG_CONFIG_HOME/git/config`.

Please see my Repo class override workaround for details: https://github.com/jzempel/continuity/blob/master/continuity/services/git.py#L38-L58

**Comment by Byron** [comment]
Thanks a bunch - you are totally right and I have basically put in the code in your override. Additionally I had a look at the c-git source and it is indeed implemented similarly.
