### ISSUE TITLE
installation with pip successfully happens despite missing git

### ISSUE THREAD

**Issue by inashivb** [gitpython-developers/GitPython#1602]
Hi, all! :)

I was installing `GitPython` on a fresh minimalistic docker image with `pip3` which did not have `git` installed. Yet, the installation with pip happened successfully.

```
Successfully installed GitPython-3.1.31
```

I was only able to understand the issue when I tried to import something and there was error about bad git executable.

Is this the intended behavior? 
Thank you for your time!

**Comment by Byron** [comment]
Yes, it's intended for GitPython to check for `git` at runtime, and not at install time. Arguments can be made for improving the messaging during installation, but I doubt it's going to happen - setup.py is messy enough as is 😅.
If you feel strongly about this, contributions are always welcome though.
