### ISSUE TITLE
Creating a more readable Quickstart guide

### ISSUE THREAD

**Issue by LeoDaCoda** [gitpython-developers/GitPython#1605]
Hello, I have used this project for my own project and I found it to be incredibly useful. But, the documentation was not very straightforward. I propose adding a Quickstart guide that shows programmers how to do some basic Git operations using GitPython. I would love to complete this work myself. Linked below is a notebook example for the git.Repo object getting started section. I planned to make sections for Remote, Tree, Blob, Commit, and Index objects.

https://colab.research.google.com/drive/1U6WWAkEN6zyBydJ9sQc0nVCLcQIuWPTe?usp=sharing

I am open to criticism

 Thanks!

**Comment by Byron** [comment]
Thanks a lot for the effort, a quick-start guide would be great to have.

I think it's perfectly valid to write what would have helped you, so anything goes.

As a word of caution, I recommend trying to get from the notebook to the actual documentation system of `GitPython` as soon as possible, as it will take some adaptation. You will see what I mean if you take a look at `test_docs.py` and the respective tutorial (restructured text). The idea here is that the documentation is part of the test suite and is executable to prevent any rot from creeping in, and the quick-start guide would use the same (or improved) system to integrate with the documentation. I do recommend pushing for having an early draft integrated as soon as possible to not have the burden of having to translate 20 pages from one system to another.
