### ISSUE TITLE
Failing test on fresh clone

### ISSUE THREAD

**Issue by LeoDaCoda** [gitpython-developers/GitPython#1607]
## Error Summary

```
FAILED test/test_submodule.py::TestSubmodule::test_git_submodules_and_add_sm_with_new_commit - git.exc.GitCommandError: Cmd('/usr/bin/git') failed due to: exit code(128)
FAILED test/test_submodule.py::TestSubmodule::test_list_only_valid_submodules - git.exc.GitCommandError: Cmd('/usr/bin/git') failed due to: exit code(128)
```

## Steps to reproduce

1. Fork and cloned repo
2. ran `./init-tests-after-clone.sh`
3. created a python venv
4. ran `pip install -r test-requirements.txt`
5. `pytest`

## Environment

OS: Ubuntu 20
Python 3.8

Attached is the output
[test_log.txt](https://github.com/gitpython-developers/GitPython/files/11986963/test_log.txt)

**Comment by Byron** [comment]
Thanks for reporting! 

In all fairness, it's likely this issue will stay open forever unless you pick it up yourself. If it's not an impediment for you, I recommend ignoring the failures and focussing the actual goal and closing this issue.

**Comment by LeoDaCoda** [comment]
ok thanks for the quick response!
