### ISSUE TITLE
line numbers for diff

### ISSUE THREAD

**Issue by CDKnightNASA** [gitpython-developers/GitPython#1612]
As with the Repo.blame() method, for all M modifications (heck, also for A) I would like a list of line numbers.

I currently have code that does the git diff and parses the @@ line number info and I use it in combination with tools like pylint to report only issues with modified code in a CI job.

**Comment by Byron** [comment]
I am closing the issue as GitPython is in maintenance mode, thus requests for additional features are rejected by default. 
PRs with additional features will always be reviewed though.
Thanks for your understanding.

**Comment by CDKnightNASA** [comment]
Thanks, I mostly filed the issue to see if it was already being worked on or if anybody had any cautionary tales. I'll see if I can work up a PR for this.
