### ISSUE TITLE
Pull/Push blocked with Git 1.9.4 and GitPython 3.1.18

### ISSUE THREAD

**Issue by simjan** [gitpython-developers/GitPython#1613]
Hi developpers,

I just solved an issue with GitPython by upgrading git from 1.9.4 to 2.24.1 (working with GitPyhton 3.1.18 on W10)

The problem was a blocking of the process in the stderr processing (git/cmd.py line 102)

I suppose the old git version print in stdout and not in stderr as the new one does, but not sure...

I don't wait a fix or something else, it's just to notify a possible problem with a supported version of Git (which has to be > 1.7.x)

**Comment by Byron** [comment]
Thanks a lot for reporting, I hope onlookers will find this information useful.
