### ISSUE TITLE
Reading from Blob data stream results in ValueError exception when run under ipython

### ISSUE THREAD

**Issue by uzytkownik** [gitpython-developers/GitPython#1627]
Unfortunately I cannot share stacktrace as it contains confidential information. I run into strange error - when I run following code from under ipython, GitPython throws ValueError saying it cannot decode SHA and a line from beginning of file. It seems to work when run as script:

```python
repo = git.Repo(...)
blob = git.Blob(repo, b'...')
print(str(blob.data_stream.read()))
```

**Comment by Byron** [comment]
I don't think with the amount of provided information that a fix is possible. Thanks for your understanding.
