### ISSUE TITLE
Python 3.12: ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by hugovk** [gitpython-developers/GitPython#1640]
The [Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) is out! :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

See also https://dev.to/hugovk/help-test-python-312-beta-1508/

Python 3.12.0 final will be released in one month: https://peps.python.org/pep-0693/

---

However, when adding 3.12 to the CI like https://github.com/hugovk/GitPython/commit/427164b56ac4dec10b7d3fea27e7485643550776, it [fails](https://github.com/hugovk/GitPython/actions/runs/6063520672/job/16450971945#step:7:333) with:

```pytb
―――――――――――――――――――――― TestInstallation.test_installation ――――――――――――――――――――――

self = <test.test_installation.TestInstallation testMethod=test_installation>
rw_dir = '/tmp/test_installationo1a7a3rg'

    @with_rw_directory
    def test_installation(self, rw_dir):
        self.setUp_venv(rw_dir)
        result = subprocess.run(
            [self.pip, "install", "-r", "requirements.txt"],
            stdout=subprocess.PIPE,
            cwd=self.sources,
        )
        self.assertEqual(
            0,
            result.returncode,
            msg=result.stderr or result.stdout or "Can't install requirements",
        )
        result = subprocess.run(
            [self.python, "setup.py", "install"],
            stdout=subprocess.PIPE,
            cwd=self.sources,
        )
>       self.assertEqual(
            0,
            result.returncode,
            msg=result.stderr or result.stdout or "Can't build - setup.py failed",
        )
E       AssertionError: 0 != 1 : Can't build - setup.py failed

test/test_installation.py:39: AssertionError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/home/runner/work/GitPython/GitPython/setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by EliahKagan** [comment]
This happens because, while the `setuptools` build backend remains supported including for projects like this one with `setup.py` files containing nontrivial logic, running `setup.py` directly is deprecated and, starting in Python 3.12, Python virtual (and global) environments no long automatically have the `setuptools` package. The solution is to use `pip install .` instead (or `pip install -e .` when an editable install is desired).

I've opened #1654, which includes a fix for this issue.
