### ISSUE TITLE
3.1.34 not available on github

### ISSUE THREAD

**Issue by dvzrv** [gitpython-developers/GitPython#1641]
Hi! I'm packaging this project for Arch Linux and we are no longer relying on sdist tarballs from PyPI.

Can you please tag the version 3.1.34 properly (it is available on pypi.org but not as tag in this repository), so that I may build this as a package? Thanks!

**Comment by Byron** [comment]
Thanks for the heads-up, sorry for the hassle.

It's [available now](https://github.com/gitpython-developers/GitPython/releases/tag/3.1.34).
