### ISSUE TITLE
`@NoEffect` appears in general documentation examples

### ISSUE THREAD

**Issue by EliahKagan** [gitpython-developers/GitPython#1674]
`@NoEffect` annotations appear in code examples [in at least one place](https://gitpython.readthedocs.io/en/stable/tutorial.html?highlight=%40NoEffect#understanding-objects) in the generated and published documentation.

This appears to have been to suppress output from some analysis tool that has been used. I don't know if they are ever still needed in the code itself or, if not, if they may ever be needed again. If not, this can be fixed by removing them. Otherwise, there may or may not be a reasonable way to have them omitted from the documentation.

In #1673, as it currently stands, I have worsened this situation by expanding them into `# noqa: B015  # @NoEffect` to also suppress the corresponding warning from `flake8`. But if they are no longer needed, then the suppression comments could be removed altogether, and instead [`per-file-ignores`](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-per-file-ignores) can be used to configure `flake8` not to issue B015 for any code in test modules from which documentation is generated. This is a broader suppression than the current one, but it would leave other checks intact even in those couple modules, and I think the tradeoff would be worthwhile.

**Comment by Byron** [comment]
I think the current tooling is happy *without* these annotations, they can safely be removed. That would be my preference as well.
