### ISSUE TITLE
Add git merge-base command into GitPython

### ISSUE THREAD

**Issue by jwir3** [gitpython-developers/GitPython#169]
It would be nice if there was a way in the GitPython API to do the following native git command:

```
git merge-base <commit 1> <commit 2>
```
For example, it would be nice to be able to perform the following:
```
from git import *

repo = Repo('/path/to/repo')
base = repo.find_last_common_ancestor('de1f33', '78dd34')
print(base)
```
The expected output, assuming the least common ancestor of 'de1f33' and '78dd34' was '6ff871', (obviously all of these commits have fictional SHAs) would be:
```
<git.Commit "6ff871652e0f3b9fa991bbd9b42e520f91723436e">
```

**Comment by ereOn** [comment]
Note that the `merge-base` command does not take only two commits but any number of commits so the implemented solution should offer that possibility as well.

**Comment by Byron** [comment]
`Repo.merge_base()` [was implemented](https://github.com/gitpython-developers/GitPython/blob/master/git/repo/base.py#L463), including [a rather straightforward test-case](https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_repo.py#L742).
All the requested are supported, after all, I am just calling the cgit implementation and interpret its return values.

**Comment by Byron** [comment]
You can watch the development video [on youtube](http://youtu.be/3YscFdxYHtc)

**Comment by sonicfly** [comment]
This implementation doesn't support "--is-ancestor" flag very well, it returns empty list for both 0 and 1 status code case.

**Comment by Byron** [comment]
Can you please open a new issue with some information about the version of GitPython and python you are using, along with how I can reproduce the issue ?
Thanks a lot !

**Comment by lahirug** [comment]
Does this support getting the common ancestor commit of two given branches ?
ex: git merge-base origin/release/1.30 origin/release/1.31 
639ea92cd1c57f056e9e1a1a237fdef22533f53
