### ISSUE TITLE
Submodule.remove `module` parameter doc is unclear or incomplete

### ISSUE THREAD

**Issue by EliahKagan** [gitpython-developers/GitPython#1712]
The docstring for [`Submodule.remove`](https://github.com/gitpython-developers/GitPython/blob/main/git/objects/submodule/base.py#L941) documents the `module` parameter this way:

https://github.com/gitpython-developers/GitPython/blob/6f765a2028e45a14853bf06801104cc6d22e053e/git/objects/submodule/base.py#L951-L959

A sentence trails off in "if you have modifications in the" and it appears material is missing. This should be revised, but it is is unclear exactly what the intended meaning is, so I don't know for sure how to fix it.

The current phrasing appears to be the effect of an unsuccessful or incomplete [attempt](https://github.com/gitpython-developers/GitPython/commit/8e0e315a371cdfc80993a1532f938d56ed7acee4#diff-0d77f7389366948adb9b48c092150ac5c03033de1d89250748ae9add1e548eb5R512-R519), in 8e0e315, to fix a similar misphrasing. Compared to the [original wording](https://github.com/gitpython-developers/GitPython/commit/3d061a1a506b71234f783628ba54a7bdf79bbce9#diff-b783f55c358d34650a259d030b6ed9b67b611d205ed239027c861cad71b67d93R337-R345) in 3d061a1, the change was:

```diff
         :param module: If True, the module we point to will be deleted 
             as well. If the module is currently on a commit which is not part 
             of any branch in the remote, if the currently checked out branch 
-            is ahead of its tracking branch,  if you have modifications in the
             working tree, or untracked files,
+            is ahead of its tracking branch,  if you have modifications in the
             In case the removal of the repository fails for these reasons, the 
             submodule status will not have been altered.
             If this submodule has child-modules on its own, these will be deleted
```

So the original wording also trailed off in mid-sentence, but differently, with "working tree, or untracked files,".

I can *guess* the intended meaning:

> If True, the module checkout we point to will be deleted as well. If the module is currently on a commit which is not part of any branch in the remote, if the currently checked out branch is ahead of its tracking branch, or if there are modifications to the working tree or untracked files, then the removal will fail.

If that revision is correct, it could be clarified by a small amount of further rewording:

> If True, the checked out module we point to will be deleted as well. If that module is currently on a commit outside any branch in the remote, or if it is ahead of its tracking branch, or if there are modified or untracked files in its working tree, then the removal will fail.

However, I am not sure enough that this is the intended meaning to have put either of those changes in a PR at this time.

**Comment by Byron** [comment]
Thanks for bringing this up.

I am also not sure and I suppose the tests or the code itself could reveal more of the story. In the meantime, I think it's OK to go with the second version of the proposed correction as *seemingly correct* seems better than *incomplete and nonsensical*.

The submodule implementation is another wart of the project, unfortunately, as it's a half-baked attempt to improve git submodules which has many, many issues.

**Comment by EliahKagan** [comment]
> In the meantime, I think it's OK to go with the second version

Sounds good. I've done this in #1714.
