### ISSUE TITLE
Unclear why fun.py (and others?) shouldn't have a module docstring

### ISSUE THREAD

**Issue by EliahKagan** [gitpython-developers/GitPython#1733]
While working on #1725 I noticed the `git.index.fun` module has this comment at the top:

https://github.com/gitpython-developers/GitPython/blob/d5fc6e5337011d54fd2f3ff5aac71dbb38e43ee6/git/index/fun.py#L1-L2

Actually, that exact comment is due to my revision in that PR, but it's revised from:

https://github.com/gitpython-developers/GitPython/blob/add46d9daa7664628ba3512297a2401981694c98/git/index/fun.py#L1-L3

This was introduced in 9ccd777, at which time an existing module docstring was converted to a comment instead. Various other module docstrings were also converted to comments. But some modules today do have docstrings. Running `make -C doc html` seems to work fine; I ran it a number of times on Ubuntu and Windows while working on that PR and since.

I didn't want to assume it was okay to turn that back into a docstring. But either it (and any other top of module comments) should be turned into docstrings, *or* the reason they should not be should be made clearer (and any module docstrings causing problems fixed or converted back to comments).

**Comment by Byron** [comment]
That's an interesting find and I don't have an answer as to why that was necessary then. Ideally, that would have been in the commit message that introduced the comment, but here we are.
My guess is that it's alright to change it back and see what happens, I'd expect it to work as well.
