### ISSUE TITLE
0.3  test_fetch_info (git.test.test_remote.TestRemote) fails parsing FETCH_HEAD

### ISSUE THREAD

**Issue by hashar** [gitpython-developers/GitPython#180]
Running the 0.3 branch tests I have a failure:

    ======================================================================
    ERROR: test_fetch_info (git.test.test_remote.TestRemote)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/amusso/projects/GitPython/git/test/test_remote.py", line 454, in test_fetch_info
        fetch_info_line_fmt % 'remote-tracking branch')
      File "/Users/amusso/projects/GitPython/git/remote.py", line 265, in _from_line
        raise ValueError("Failed to parse FETCH__HEAD line: %r" % fetch_line)
    ValueError: Failed to parse FETCH__HEAD line: "c437ee5deb8d00cf02f03720693e4c802e99f390 not-for-merge   remote-tracking branch '0.3' of git://github.com/gitpython-developers/GitPython"

Seems GitPython is not fully compliant with FETCH_HEAD format. My file has:

    $ cat .git/FETCH_HEAD 
    27c577dfd5c7f0fc75cd10ed6606674b56b405bd		branch '0.3' of https://github.com/gitpython-developers/GitPython
    90d73cd6ffa6e848da59cb2a35dec74e0fabd00a	not-for-merge	branch '0.1' of https://github.com/gitpython-developers/GitPython
    ec97ed84d114ef131fa98acee4ce7be32f8c591f	not-for-merge	branch '0.2' of https://github.com/gitpython-developers/GitPython
    77587cd44b2f3b40dfeb753a34d33fe1a820ab06	not-for-merge	branch 'gh-pages' of https://github.com/gitpython-developers/GitPython
    a66cfe99c1af3d745e929da6a61e1257e3a376b1	not-for-merge	branch 'master' of https://github.com/gitpython-developers/GitPython

**Comment by Byron** [comment]
The test is verified to be working and able to parse `not-for-merge` fetch head information correctly. I believe this was fixed through a PR at some point.
