### ISSUE TITLE
Note in GitCmdObjectDB should be removed or updated

### ISSUE THREAD

**Issue by EliahKagan** [gitpython-developers/GitPython#1849]
Somewhat similar to #1845, the `git.db.GitCmdObjectDB` docstring contains this note:

https://github.com/gitpython-developers/GitPython/blob/87b8035c733018d6e8c097f79b61ad19a987f0d4/git/db.py#L34-L35

I think that note can simply be removed now, since as far as I know, it does not correspond to a current goal and is not needed to understand the code or how to use it. But I am not confident of this, because I am not sure exactly *what* it is actually referring to. If more features were implemented, would this have been:

- A change to `GitCmdObjectDB` itself?
- Switching back from `GitCmdObjectDB` to `GitDB`?
- A combination of the two, or something else related?

That only needs to be answered if it affects what should happen in that docstring (or elsewhere), which is why I've made this an issue rather than a discussion question.

I plan to remove it in a forthcoming PR with a number of other docstring revisions, but I'm opening this in case my understanding is mistaken.

**Comment by Byron** [comment]
Thank you for sharing your findings!

That note was definitely referring to having a built-in implementation of the Git Object Database, which never manifested, and what was there was obviously too slow.

Thus, I think it's absolutely fair to remove the note.
