### ISSUE TITLE
Should Repo.tags return tags sorted by date, not alphabetical?

### ISSUE THREAD

**Issue by duncanmmacleod** [gitpython-developers/GitPython#185]
At present, `git.Repo.tags` returns the list of tags sorted alphabetically. It might be more helpful to have the list of tags sorted by the `committed_date` of the relevant `Commit`.

For example, I have a repository with the following tags:

```python
>>> import git
>>> repo = git.Repo('.')
>>> print(repo.tags)
[<git.TagReference "refs/tags/v0.1a1">,
 <git.TagReference "refs/tags/v0.1a10">,
 <git.TagReference "refs/tags/v0.1a2">,
 <git.TagReference "refs/tags/v0.1a3">,
 <git.TagReference "refs/tags/v0.1a4">,
 <git.TagReference "refs/tags/v0.1a5">,
 <git.TagReference "refs/tags/v0.1a6">,
 <git.TagReference "refs/tags/v0.1a7">,
 <git.TagReference "refs/tags/v0.1a8">,
 <git.TagReference "refs/tags/v0.1a9">]
```

Here the ordering is misleading, since the v0.1a10 tag is the most recent. Does it make sense to sort this list before returning?

```python
>>> print(sorted(repo.tags, key=lambda t: t.commit.committed_date))
[<git.TagReference "refs/tags/v0.1a1">,
 <git.TagReference "refs/tags/v0.1a2">,
 <git.TagReference "refs/tags/v0.1a3">,
 <git.TagReference "refs/tags/v0.1a4">,
 <git.TagReference "refs/tags/v0.1a5">,
 <git.TagReference "refs/tags/v0.1a6">,
 <git.TagReference "refs/tags/v0.1a7">,
 <git.TagReference "refs/tags/v0.1a8">,
 <git.TagReference "refs/tags/v0.1a9">,
 <git.TagReference "refs/tags/v0.1a10">]

This may also be helpful for other reference lists.

**Comment by Byron** [comment]
I had a look into this and found the [spot of the sorting](https://github.com/gitpython-developers/GitPython/blob/master/git/refs/symbolic.py#L598). After comparing it to the way `git tag` handles this, I believe that sorting alphabetically after all is the right thing to do.
In case different sorting orderings are required, it is easy enough to apply them after obtaining the alphabetically sorted list of items, as presented in your example too.

```python
sorted(repo.tags, key=lambda t: t.commit.committed_date)
```

I hope my explanation is enough to justify closing this issue without actually making a change. If not, please let me know.

**Comment by Byron** [comment]
The development video related to this issue can be found [on youtube](http://youtu.be/WXPUST4MaOw)
