### ISSUE TITLE
assert_never raises different exception than documented

### ISSUE THREAD

**Issue by EliahKagan** [gitpython-developers/GitPython#1857]
`git.types.assert_never` is documented to raise `AssertionError` if `raise_error` is `True` and `exc` is `None`:

https://github.com/gitpython-developers/GitPython/blob/b2c3d8b72301dc4723e83de676fd7086d5c3c381/git/types.py#L83

But it actually raises `ValueError` in this situation, its full implementation being:

https://github.com/gitpython-developers/GitPython/blob/b2c3d8b72301dc4723e83de676fd7086d5c3c381/git/types.py#L85-L89

For comparison. there is an `assert_never` function in Python's `typing` module since 3.11 (and in `typing_extensions`). This function is similar but only has one parameter--which the first parameter of `git.types.assert_never` corresponds to--and it documents *that* it raises an exception if called at runtime, but does not document the type of exception raised. At least currently in Python 3.12, [it raises `AssertionError`](https://github.com/python/cpython/blob/0a9356ce6ddca117588c95480f0ef1ef33df03cb/Lib/typing.py#L2406).

The GitPython function is a public member of `git.types`, and it is used internally in GitPython. I don't know if the docstring should be fixed to describe the existing behavior, or if that behavior should itself be considered the bug here and changed to match the docstring.

**Comment by Byron** [comment]
Thanks for letting me know.

It does seem a bit strange to me that functions related to testing are part of the `git` public API in the first place, but it's probably nothing that can truly be fixed anymore.

With that said, even tough there mere existence could be considered a bug, I tend to leave it and its behaviour alone while fixing the docstring.
