### ISSUE TITLE
Using create submodule doesn't create the correct submodule structure

### ISSUE THREAD

**Issue by aliencrash** [gitpython-developers/GitPython#1867]
Hi,

I'm using GitPython to manage repository but I'm having some issues with submodule.
This is a snipped of my code.
![image](https://github.com/gitpython-developers/GitPython/assets/10322162/7e9a44bd-e460-4000-a7cd-129a259c77ee)

What I'm trying to do is to create the sub-modules when they don't exist.
The method does everything right until I run the following code that is to add the folder with all submodules 'saas_env', create commit and push.
![image](https://github.com/gitpython-developers/GitPython/assets/10322162/c3f5f913-333e-47e4-b756-dfdabcd6c9dd)

The result of push is 
![image](https://github.com/gitpython-developers/GitPython/assets/10322162/b4c26d20-2df2-45dd-851f-e56bd4e510ed)

But then I'm not able to clone the repository.  

It's something I'm doing wrong?

**Comment by Byron** [comment]
Thanks for reporting and showing (probably) all the relevant pieces of code that lead to the unexpected behaviour (even though I don't necessarily understand what that is).

However, as general advice: try to use `repo.git.submodule(…git arguments…)` instead, as the built-in submodule implementation is old and can't be trusted. When that is done, it might already work as `create_submodule()` probably also can't be trusted.

**Comment by Byron** [comment]
As submodules are known to be wonky, and GitPython is in maintenance mode, I am closing this issue as 'not planned', and thank you for your understanding.

However, if you discover anything that would allow improvements, the issue can be reopened if it would aid the creation of a PR.

**Comment by aliencrash** [comment]
Ok Thank you.

**Comment by EliahKagan** [comment]
Although #1859 will not fix a bug like this, in working on it I've been looking at, and shall be looking more at, the code in `git/objects/submodule/base.py`. If you do end up finding more information that could point the way to a fix, then I might be able to do something with it, or help you (or another contributor) to do so.

So please feel free to `@`-mention me if you do find something, and I'll take a look. I emphasize though that I cannot promise anything and this is *not* a request for you to investigate this further, which I cannot predict would be worthwhile for you to do.
