### ISSUE TITLE
Missing pygit2 

### ISSUE THREAD

**Issue by jean** [gitpython-developers/GitPython#191]
Running tests reports:
  `Could not find 'pygit2' in the PYTHONPATH - pygit2 functionality is not available`

Probably a missing requirement, I'll investigate if I find time ..

**Comment by Byron** [comment]
Just for the record: former branch `0.3` is now `master`, and former `master` is now `experiment-2012`, which is not developed anymore.
Pygit2 is not required by the current master, which makes this a non-issue.
