### ISSUE TITLE
mypy is confused by property aliases

### ISSUE THREAD

**Issue by PatrickMassot** [gitpython-developers/GitPython#1934]
Thank you very much for this very useful python package. Unfortunately mypy is very confused by property aliases such as 

```python
    @property
    def references(self) -> "IterableList[Reference]":
        """A list of :class:`~git.refs.reference.Reference` objects representing tags,
        heads and remote references.

        :return:
            ``git.IterableList(Reference, ...)``
        """
        return Reference.list_items(self)

    # Alias for references.
    refs = references
```

that can be found in [`git/repo/base.py`](https://github.com/gitpython-developers/GitPython/blob/4c21e514cd9b5acdc34891fc4b52e9b599810b3e/git/repo/base.py#L405C1-L416C22) or the analogous alias `branches` for `heads`. See https://github.com/python/mypy/issues/6700

You can reproduce the issue with the following `test.py`:
```python
from git.repo import Repo

repo = Repo()
for branch in repo.branches:
    print(branch)
```
about which `mypy` says:
```
test.py:4: error: "Callable[[], IterableList[Head]]" has no attribute "__iter__" (not iterable)  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

I am not aware of any fix that would not uglify the code here, and that mypy issue doesn’t seem likely to see improvement in the near future. This is sad, but doing all the work to add type annotations and still having users facing incomprehensible error messages in perfectly legitimate code is also sad. 

Could you please tell me whether you would welcome a PR “fixing” this?

**Comment by Byron** [comment]
Thanks for reporting! Yes, please feel free to submit a PR with a fix, as long as it's not done by a breaking change in the current API.

If the API needs to change, an alternative one to the what already exists can be provided. Maybe, and this is my hope, the typing itself can be improved.

**Comment by PatrickMassot** [comment]
Ok, I submitted a minimal fix. There is no API change here, only more verbose code.
