### ISSUE TITLE
Read the Docs addons

### ISSUE THREAD

**Issue by EliahKagan** [gitpython-developers/GitPython#1957]
[Read the Docs](https://about.readthedocs.com/) has [various addons](https://docs.readthedocs.io/en/stable/addons.html#read-the-docs-addons), most or all of which look useful and appropriate for GitPython's documentation on Read the Docs, that [can be enabled](https://docs.readthedocs.io/en/stable/addons.html#enabling-read-the-docs-addons).

This feature is to some extent an increase in RTD-specific functionality. But it also, if I understand correctly, [moves the RTD-specific changes out of the build process](https://about.readthedocs.com/blog/2024/07/addons-by-default/), so that RTD and non-RTD (e.g. local) builds are more similar.

[The instructions for enabling add-ons explicitly](https://docs.readthedocs.io/en/stable/addons.html#enabling-read-the-docs-addons) mention that they will be enabled automatically for all projects "some time in the second half of 2024." But examining the [classic dashboard](https://readthedocs.org/projects/gitpython/builds/25346602/) for a preview build reveals that this will happen in about three weeks from now, which [the official blog post confirms](https://about.readthedocs.com/blog/2024/07/addons-by-default/#deprecation-timeline).

I recommend explicitly enabling addons and selecting any that are desired, which I suspect will be all or most of them, in order to identify any problems before that time, thereby avoiding disruption. Any problems related to the overall change itself or to specific addons that are wanted can thus be solved before then, while any addons that are not wanted at all can be turned off.

(One of the addons that I think may be prove especially useful is DocDiff, which is part of [pull request previews](https://docs.readthedocs.io/en/stable/pull-requests.html). I believe this does *not* require any further [integration](https://github.com/gitpython-developers/GitPython/issues/1842#issuecomment-1962387351) than is [currently done](https://github.com/gitpython-developers/GitPython/issues/1842), because it's a change to the previews themselves.)

It does not look like this feature can be enabled by alternative means such as editing the `.readthedocs.yml` file, which is why I'm opening this issue about it rather than a PR.

**Comment by Byron** [comment]
Thanks for making me aware!

What follows is the settings as I saw them, and it looks like all I could (and did) do was to check `Enable AddOns`
<img width="837" alt="Screenshot 2024-08-18 at 21 47 38" src="https://github.com/user-attachments/assets/ef24fa94-a509-4e0a-b306-0e11d1576b0c">

Do you think anything else should be done?

**Comment by EliahKagan** [comment]
This looks great to me. I haven't looked into the options for flyout sorting, so I'm not sure what the others are or what is best.

Analytics is the one addon that I didn't see a lot of value to for this project, and that's the one you've unchecked, so that makes sense. If you do think it would be valuable but are concerned about visitor privacy, then I can look into that issue. But I am not advocating any change there.

**Comment by Byron** [comment]
Indeed, I am not interested in additional numbers related to documentation specifically, so I think it's good to not have it collect more data. My feeling is that RDT collects  as much as it can anyway, and this checkbox just provides some of that information to the admin as well.
But I happily pass.
