### ISSUE TITLE
untracked_files empty on Windows8

### ISSUE THREAD

**Issue by giordi91** [gitpython-developers/GitPython#199]
HI, I am having this problem on windows 8 (I did not test windows7 yet but I ll do that asap), where the untracked_file argument result as empty no matter what, I double tested same code on CentOs and everytihng is fine. here is a simple code I am running:

repo = git.Repo("C:/Users/Marco\WORK_IN_PROGRESS/python/animshader")
print repo.git.status()
print repo.untracked_files

Here is the log:
---------- status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    attributes/shader_float3_attr.py

nothing added to commit but untracked files present (use "git add" to track)
---------- untracked
[]

So as you can see the status() can correctly see the untracked file but for some reason the property untracked_files is failing along the line.
Any guess?

**Comment by Byron** [comment]
![screen shot 2015-01-07 at 09 21 27](https://cloud.githubusercontent.com/assets/63622/5642719/b9fb6164-964e-11e4-863e-1023aa371936.png)

I just verified this is working. Besides, the respective test is not failing on windows either.
Please be sure to use the latest version available on pypi (currently 0.3.4).
