### ISSUE TITLE
git config parser dosn't account for included files in a .gitconfig

### ISSUE THREAD

**Issue by arecarn** [gitpython-developers/GitPython#201]
The git config parser don't look into files that are [included](http://git-scm.com/docs/git-config#_includes) into the .gitconfig file.

For example:

---

**~/.gitconfig**
```
[user]
    name = Ryan Carney
    email = email@personal.com
[include]
    path = ~/.gitconfig_local
```

**~/.gitconfig_local**
```
[user]
    email = email@work.com
```

**gitpython_test.py**
```
import git
repo = git.Repo("test_repo")
reader = repo.config_reader()
print reader.get("user", "email")
```
---
Given the above configuration you would expect **gitpython_test.py** to print `email@work.com` but instead it prints`email@personal.com`

**Comment by Byron** [comment]
The development log for this issue [can be watched on youtube](http://youtu.be/3TDAzIabos0).
