### ISSUE TITLE
How to remove deleted files to a git repository

### ISSUE THREAD

**Issue by t00f** [gitpython-developers/GitPython#212]
Hi guys,

I am using `GitPython` to automatically update a git repository. I am able to get all diffs using `repo.diffs(None)` call and them add all to the index like the following code:

``` python
repo.index.add([diff.a_blob.path for diff in diffs])
repo.index.commit(message)
```

When the difference is actually a file that has been deleted or moved, it throws an exception `OSError: [Errno 2] No such file or directory`. According to the document, I should add path of an existing file.

How can I actually tell the index that the file does not longer exist ?

Thanks for your help!

**Comment by Byron** [comment]
Closed due to inactivity.
