### ISSUE TITLE
'Git' object attribute 'GIT_PYTHON_TRACE' is read-only

### ISSUE THREAD

**Issue by techtonik** [gitpython-developers/GitPython#222]
I want to trace https://github.com/arc90/git-sweep/issues/29 and trace just a single call, but GitPython only allows to control debug output with environment options, which is inconvenient.

**Comment by Byron** [comment]
You can still set this variable, but will have to do that through the type, not the instance of it. The latter will try to create a new instance variable and fail thanks to slots.
For example:
```python
type(repo.git).GIT_PYTHON_TRACE='full'
```

**Comment by techtonik** [comment]
Looks like a hack to me. Too late anyway.

**Comment by techtonik** [comment]
Just for the reference - I went down to my `site-packages` and removed `__slots__` definition manually from installed GitPython. That appeared to be the fastest way to `fix things`.
