### ISSUE TITLE
test_index_mutation compares full dereferenced and non-dereferenced paths

### ISSUE THREAD

**Issue by yarikoptic** [gitpython-developers/GitPython#224]
```
======================================================================
ERROR: test_index_mutation (git.test.test_index.TestIndex)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/deb/gits/python-git/git/test/lib/helper.py", line 112, in repo_creator
    return func(self, rw_repo)
  File "/home/yoh/deb/gits/python-git/git/test/test_index.py", line 482, in test_index_mutation
    [os.path.abspath(os.path.join('lib', 'git', 'head.py'))] * 2, fprogress=self._fprogress_add)
  File "/home/yoh/deb/gits/python-git/git/index/base.py", line 684, in add
    paths, entries = self._preprocess_add_items(items)
  File "/home/yoh/deb/gits/python-git/git/index/base.py", line 546, in _preprocess_add_items
    paths.append(self._to_relative_path(item))
  File "/home/yoh/deb/gits/python-git/git/index/base.py", line 536, in _to_relative_path
    raise ValueError("Absolute path %r is not in git repository at %r" % (path, self.repo.working_tree_dir))
ValueError: Absolute path '/tmp/tmpX75gjinon_bare_test_index_mutation/lib/git/head.py' is not in git repository at '/home/yoh/.tmp/tmpX75gjinon_bare_test_index_mutation'
```

since I have 
```
$> ls -ld $TMPDIR
lrwxrwxrwx 1 yoh yoh 5 Nov 10  2010 /home/yoh/.tmp -> /tmp//
```
so may be in_to_relative_path should deref both paths before comparison?

**Comment by Byron** [comment]
It would be worth investigating where the path-mismatch is introduced. This is exactly where it's fixed ideally.
If this is the only failing test on your system due to this issue, I would be somewhat relieved though.

**Comment by yarikoptic** [comment]
it is coming from the use of abspath to obtain absolute path for a local file
```
$> git grep -2 abspath git/test/test_index.py 
git/test/test_index.py-        # same file
git/test/test_index.py-        entries = index.reset(new_commit).add(
git/test/test_index.py:            [os.path.abspath(os.path.join('lib', 'git', 'head.py'))] * 2, fprogress=self._fprogress_add)
git/test/test_index.py-        self._assert_entries(entries)
git/test/test_index.py-        assert entries[0].mode & 0o644 == 0o644
```

IIRC, at some point I have looked into this issue, and there were no reliable way to obtain un-dereferenced current directory to then create "abspath" without actually dereferencing the path.  Apparently IIRC it is more of a 'shell gimmick' to know that it is e.g. under ~/.tmp instead of physically being under /tmp (as OS would report, and thus abspath and getcwd).  So I wondered if it might be worth dereferencing ```repo.working_tree_dir``` from the beginning.  I see already a use of os.path.realpath in  ```read_gitfile``` ...

I have some other failures still but I believe they are not related to this one

**Comment by Byron** [comment]
All tests should work natively now even with a symbolic link as TMPDIR. My solution is to not use `realpath` at all, but instead operate on paths consistently. That should save the IOPs otherwise necessary to obtain such a realpath (which as to read and follow symlinks).

**Comment by Byron** [comment]
Videos can be found here:

* [youtube part 1/2](http://youtu.be/Er1GImzxs84)
* [youtube part 2/2](http://youtu.be/X4g4uf5N9BI)

**Comment by yarikoptic** [comment]
OMG -- I am in a movie! ;)  Quite cool of you to produce those -- I didn't know, quite a nice idea, may be the *net will hear my angry russian cursing at some point as well ;)

**Comment by ryneeverett** [comment]
@Byron I'm confused by your conclusion that `os.path.realpath` "wasn't required afterall" in ede325d15ba9cba0e7fe9ee693085fd5db966629.

43e430d7fa5298f6db6b1649c1a77c208bacf2fc seems to be the only commit that doesn't throw the above `ValueError` when a non-normalized absolute path is added to the index. E.g.:

```python
>>> my_path = '/home/user/./repo/file'
>>> os.path.isabs(my_path)
True
>>> repo.index.add([my_path])
...
ValueError: Absolute path '/home/user/./repo/file' is not in git repository at '/home/user/repo'
>>> my_path = os.path.realpath(my_path)
>>> repo.index.add([my_path])
<success>
```

**Comment by Byron** [comment]
I would still state that `realpath` isn't required. In your case, `normpath`is advised and it should work. In the recording, I might have come to the conclusion that application should sanitise their paths themselves, gitpython seems sufficiently low-level to be able to expect that.
This is just my current opinion though, and if you want to make a statement towards including `normpath` in the index implementation, I could certainly do so.

**Comment by ryneeverett** [comment]
@Byron True. I'd like to at least see it stated in the API reference that paths need to be normalized.
