### ISSUE TITLE
line is missing tab separator

### ISSUE THREAD

**Issue by yarikoptic** [gitpython-developers/GitPython#225]
As I have whined about in #216, I have a few hits into

```
======================================================================
ERROR: test_base (git.test.test_reflog.TestRefLog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/deb/gits/python-git/git/test/test_reflog.py", line 48, in test_base
    reflog = RefLog.from_file(rlp_master_ro)
  File "/home/yoh/deb/gits/python-git/git/refs/log.py", line 154, in from_file
    return cls(filepath)
  File "/home/yoh/deb/gits/python-git/git/refs/log.py", line 128, in __init__
    self._read_from_file()
  File "/home/yoh/deb/gits/python-git/git/refs/log.py", line 140, in _read_from_file
    self._deserialize(fmap)
  File "/home/yoh/deb/gits/python-git/git/refs/log.py", line 289, in _deserialize
    self.extend(self.iter_entries(stream))
  File "/home/yoh/deb/gits/python-git/git/refs/log.py", line 180, in iter_entries
    yield new_entry(line.strip())
  File "/home/yoh/deb/gits/python-git/git/refs/log.py", line 86, in from_line
    raise ValueError("line is missing tab separator")
ValueError: line is missing tab separator
```
```
(Pdb) print line
0000000000000000000000000000000000000000 609237d8b5a47d5e68babea116712e5d41e8a949 Yaroslav Halchenko <debian@onerussian.com> 1418863256 +0000
```
in my case it looks like fields are separated by the space.   Where tab should have been? ;)
 I am also a bit confused with 2 in ```info, msg = line.split('\t', 2)``` since it would result in up to 3 elements in the list, thus might overfill info, msg pair

**Comment by Byron** [comment]
Indeed, the `.split` call should be limited to two tokens, so the two literal should be a 1 instead. Usually these lines have a tab character right after the timestamp, separating information from the comment.
Apparently, lines without a comment are valid too unless you tell me you have truncated the line accidentally.
In any case, it's probably a good idea make the parser a little less error prone.

**Comment by yarikoptic** [comment]
On Sun, 04 Jan 2015, Sebastian Thiel wrote:

>    Indeed, the .split call should be limited to two tokens, so the two
>    literal should be a 1 instead. Usually these lines have a tab character
>    right after the timestamp, separating information from the comment.
>    Apparently, lines without a comment are valid too unless you tell me you
>    have truncated the line accidentally.

oh those mornings -- things are so much clearer ;)

So I have looked back at that file.  And indeed it does have tabs but
not in the first line, which I didn't truncate manually anyhow.

$> cat /home/yoh/deb/gits/python-git/.git/logs/HEAD | sed -e 's,\t,<TAB>,g'
0000000000000000000000000000000000000000 609237d8b5a47d5e68babea116712e5d41e8a949 Yaroslav Halchenko <debian@onerussian.com> 1418863256 +0000
609237d8b5a47d5e68babea116712e5d41e8a949 3b88fc1c16c4056b4ae1ca975d8559cb81b52b64 Yaroslav Halchenko <debian@onerussian.com> 1418863446 -0500<TAB>commit: -3 was released a while back but I guess forgotten to be committed
3b88fc1c16c4056b4ae1ca975d8559cb81b52b64 2ae97e71df2237976fd642da08ecf3d7bc99c859 Yaroslav Halchenko <debian@onerussian.com> 1418863550 -0500<TAB>commit: Changelog for 0.3.2.1-1 to be uploaded to experimental
2ae97e71df2237976fd642da08ecf3d7bc99c859 869dd572cebf559ce1070fd50ec23c736d734418 Yaroslav Halchenko <debian@onerussian.com> 1418863680 -0500<TAB>commit: includes debian/patches/dont-choke-on-rc-version.patch
869dd572cebf559ce1070fd50ec23c736d734418 b91ab20d9b17d5a0ccfe3ce2e7a3e953fe00420b Yaroslav Halchenko <debian@onerussian.com> 1418875082 -0500<TAB>commit: enable build-time testing


>    In any case, it's probably a good idea make the parser a little less error
>    prone.

so here you go
https://github.com/gitpython-developers/GitPython/pull/226

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik
