### ISSUE TITLE
GitPython subprocess doesn't pass the $HOME environment variable correctly

### ISSUE THREAD

**Issue by sonicfly** [gitpython-developers/GitPython#227]
When I try to push with GitPython, it always complain that my user.name, user.email and push.default is unset. I trace down and find when GitPython call git command through subprocess, the $HOME directory is not correctly set, the problem can be easily reproduce by following code segment.
<pre>
_repo = git.repo.Repo(myRootPath)
_git = _repo.git
print(_git.config("-l","--global"))
</pre>

**Comment by sonicfly** [comment]
Suggest to change line 347 of cmd.py to
env={"LC_MESSAGES": "C", "HOME": os.getenv("HOME")},

**Comment by Byron** [comment]
It's odd, as the environment starts out with a [full copy](https://github.com/gitpython-developers/GitPython/blob/master/git/cmd.py#L356) of the initial environment. Looking at the different line numbers, it may be you are not using the latest version ?

What does `git.__version__` say ?

**Comment by sonicfly** [comment]
Hmm, that's different from my local source, my version is 0.3.2.1. Seems like updating to latest solve resolve this issue.

**Comment by sonicfly** [comment]
Confirmed the latest version fixed this issue already.
