### ISSUE TITLE
Deleted 0.3 tag

### ISSUE THREAD

**Issue by olethanh** [gitpython-developers/GitPython#230]
Hello, 

we were installing GitPython via git using the 0.3 tag but it seems to not exists anymore? What happened?

**Comment by Byron** [comment]
There never was a tag with that name, but a branch.
The latter was renamed to master, and the former master was renamed to experiment-2012.
Therefore you can install from the master branch, or from pypi in case you want to use a more stable version.
Hope that helps, if not please let me know in the comments.

**Comment by olethanh** [comment]
you were right it was a branch, which was bad practice on our part, we will install from pypi from now on. Thanks for the prompt response.

**Comment by Byron** [comment]
Don't blame yourself, after all it was me who didn't update pypi (and the project) for years. Installing from branch 0.3 was the best one could do for quite a while.
