### ISSUE TITLE
ImportError: cannot import name BadName

### ISSUE THREAD

**Issue by Utumno** [gitpython-developers/GitPython#231]
```
import git
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\_\Python27\lib\site-packages\gitpython-0.3.4-py2.7.egg\git\__init__.py", line 36, in <module>
    from git.refs import *
  File "C:\_\Python27\lib\site-packages\gitpython-0.3.4-py2.7.egg\git\refs\__init__.py", line 4, in <module>
    from .symbolic import *
  File "C:\_\Python27\lib\site-packages\gitpython-0.3.4-py2.7.egg\git\refs\symbolic.py", line 11, in <module>
    from gitdb.exc import (
ImportError: cannot import name BadName
```

**Comment by niyaton** [comment]
It's a bug from update of gitdb.
I think this problem will be solved in a few days because next release of gitdb is already mentioned in gitpython-developers/gitdb#17.

**Comment by Utumno** [comment]
Yes I updated gitPython to latest master and gitdb to 6.3 and apparently gidb has not the BadName

Anyway please see this as an opportunity to revisit install instructions for gitPython

I am on windows and I can assure you `pip install gitpython` is not docs enough

I am using `"C:\_\Python27\Scripts\easy_install-2.7.exe" GitPython` and resort to alchemy - and I am not alone into this

**Comment by Byron** [comment]
Currently when using master of gitpython, you will need to use master of gitdb as well. This is a known issue.
Just to be sure, I have installed gitpython from pip, which works just fine.
```bash
virtualenv gitpython-install
cd gitpython-install
./bin/pip install gitpython
./bin/python -c "import git" && echo "OK"
```

Nonetheless, I will keep this issue open and close it just before a new pypi release is made.

**Comment by Byron** [comment]
[gitdb was released on pypi](https://pypi.python.org/pypi/gitdb/0.6.4), which will fix the error described here.
