### ISSUE TITLE
easy_install prefered install method?

### ISSUE THREAD

**Issue by guettli** [gitpython-developers/GitPython#235]
According to the docs easy_install is the prefered install method:

http://gitpython.readthedocs.org/en/stable/intro.html#installing-gitpython

Is this really true? Most people use pip these days.

Update the docs?

**Comment by Byron** [comment]
Thanks for letting me know.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](http://youtu.be/AWsLtWuaz_o)
