### ISSUE TITLE
Tutorial improvement: init repo, add file, commit.

### ISSUE THREAD

**Issue by guettli** [gitpython-developers/GitPython#236]
Please provide a simple example on how to:

1. init a git repo
2. add a file (foo.txt)
3. commit.

I tried it and get message like this: 

{{{
ValueError: Reference at 'refs/heads/master' does not exist
}}}

**Comment by Byron** [comment]
There indeed is no example that shows this explicitly, and I will see where I can fit in a custom example.

Something you might be looking for is the [IndexObject](http://gitpython.readthedocs.org/en/stable/tutorial.html#the-index-object), which is used for preparing and making commits.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](http://youtu.be/AWsLtWuaz_o)
