### ISSUE TITLE
fetch('+refs/pull/*:refs/heads/pull/*') fails

### ISSUE THREAD

**Issue by dachary** [gitpython-developers/GitPython#243]
<pre>
>>> r.remotes.origin.fetch('+refs/pull/*:refs/heads/pull/*')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 613, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress or RemoteProgress())
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 555, in _get_fetch_info_from_stderr
    for err_line, fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 555, in <genexpr>
    for err_line, fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/usr/local/lib/python2.7/dist-packages/git/remote.py", line 292, in _from_line
    raise TypeError("Cannot handle reference type: %r" % ref_type_name)
TypeError: Cannot handle reference type: u"'refs/pull/1/head'"
</pre>
with the command line
<pre>
$ git fetch origin +refs/pull/*:refs/heads/pull/*
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 9 (delta 2), reused 9 (delta 2)
Unpacking objects: 100% (9/9), done.
From http://github.com/loic-bot/testrepo
 * [new ref]         refs/pull/1/head -> pull/1/head
 * [new ref]         refs/pull/1/merge -> pull/1/merge
 * [new ref]         refs/pull/2/head -> pull/2/head
 * [new ref]         refs/pull/2/merge -> pull/2/merge
 * [new ref]         refs/pull/3/head -> pull/3/head
 * [new ref]         refs/pull/3/merge -> pull/3/merge
</pre>

**Comment by Byron** [comment]
I could reproduce the issue and am pretty sure there will be a fix today, along with a v0.3.6 release.

What happens is that the fetch succeeds, but it can't make sense of the `refs/pull/...` paths for some reason and thus fails to wrap it into a corresponding object.

**Comment by dachary** [comment]
cool :-)

**Comment by Byron** [comment]
Your can watch the archived live-stream [on youtube](http://youtu.be/8YERpO2sRZY).
