### ISSUE TITLE
remote fetch generates exception when kwargs is set to prune=True

### ISSUE THREAD

**Issue by CedricSchmeits** [gitpython-developers/GitPython#249]
```
origin.fetch(prune=True)
...
ValueError: Control character 'x' unknown as parsed from line ' x [deleted]         (none)     -> origin/feature/testPrune'
```

**Comment by Byron** [comment]
Interesting, indeed its mapping doesn't contain this character, whereas the one for handling push information does.
Apparently doing this was uncommon back in the days, so gitpython doesn't know it yet.
For future reference, please name the version of git-python you are using, just to be sure we are on the same page.

**Comment by Byron** [comment]
Actually I was wrong about my initial assertion, and it turned out that the latest version of gitpython, `0.3.6` already handles this case correctly by ignoring it.

**Comment by Byron** [comment]
You can watch the archived [development live-stream on youtube](http://youtu.be/4HQP8Fsxx8E).
