### ISSUE TITLE
remind me what those two failures are about

### ISSUE THREAD

**Issue by yarikoptic** [gitpython-developers/GitPython#259]
silly me tried to reincarnate my evil attempts to setup travis to test across multiple debian/ubuntu releases via chroots... for some reason for me they all (?didn't check all but few, some have additional failures) have:

```
======================================================================

ERROR: test_init_repo_object (git.test.test_docs.Tutorials)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/build/yarikoptic/GitPython/git/ext/gitdb/gitdb/test/lib.py", line 87, in wrapper

return func(self, path)

File "/home/travis/build/yarikoptic/GitPython/git/test/test_docs.py", line 66, in test_init_repo_object

assert repo.tags['0.3.5'] == repo.tag('refs/tags/0.3.5') # you can access tags in various ways too

File "/home/travis/build/yarikoptic/GitPython/git/util.py", line 686, in __getitem__

raise IndexError("No item found with id %r" % (self._prefix + index))

IndexError: No item found with id '0.3.5'

======================================================================

ERROR: test_repo_creation_from_different_paths (git.test.test_repo.TestRepo)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/build/yarikoptic/GitPython/git/test/lib/helper.py", line 111, in repo_creator

rw_repo.head.commit = rw_repo.commit(working_tree_ref)

File "/home/travis/build/yarikoptic/GitPython/git/repo/base.py", line 426, in commit

return self.rev_parse(text_type(rev) + "^0")

File "/home/travis/build/yarikoptic/GitPython/git/repo/fun.py", line 183, in rev_parse

obj = name_to_object(repo, rev[:start])

File "/home/travis/build/yarikoptic/GitPython/git/repo/fun.py", line 117, in name_to_object

raise BadName(name)

BadName: Ref '0.3.2.1' did not resolve to an object
```
see more at  https://travis-ci.org/yarikoptic/GitPython/builds/51467235

**Comment by Byron** [comment]
I think you should assure your .travis.yml does a similar `install` setup as the one in the source directory. Please try to [emulate this](https://github.com/gitpython-developers/GitPython/blob/master/.travis.yml#L13) and let me know if it works now.
Also your source repository doesn't have all the required tags, for some reason. Maybe you should push them from GitPython to your clone once again ?

**Comment by yarikoptic** [comment]
d'oh -- indeed some tags were missing.  install -- I do install git, python-nose and -mock from packages .  I have not installed flake8 and sphinx and disabled those "tests"  for now (one thing at a time).
My goal is to help testing so my backport builds later where I would use those packaged versions of the nose and mock.

**Comment by yarikoptic** [comment]
awesome -- after tags pushed, works now: failed only on elderly precise (https://travis-ci.org/yarikoptic/GitPython/jobs/51529837)... I should actually check -- may be I am not even updating those chroots as I should before the test

**Comment by Byron** [comment]
`Error: [Errno 2] No such file or directory: '/tmp/test_git_submodulesqI3_Aa/parent/module/config.lock'`

This one is fixed on Wheezy, and it showed git-python is very susceptible to the git version installed on the system now. Using the version [hardcoded here](https://github.com/gitpython-developers/GitPython/blob/master/git/objects/submodule/base.py#L140) is tries to understand when git started to use `.git files`. If this version is too high, git-python behaves incorrectly and things go awry.

If you check the git version installed on that system and adjust that hardcoded version, it should work.

**Comment by yarikoptic** [comment]
>    If you check the git version installed on that system and adjust that
>    hardcoded version, it should work.

that was the version in that chroot

Get:48 http://us.archive.ubuntu.com/ubuntu/ precise/main git amd64 1:1.7.9.5-1 [6087 kB]

**Comment by Byron** [comment]
Ok, I have made a commit which sets the hardcoded version to 1.7.0. Now your case should work.

**Comment by Byron** [comment]
I'd like to make a new release this week - do you think you could recheck this issue ?
Thanks

**Comment by yarikoptic** [comment]
Let's see how #277 goes -- merged your current master and created a PR for that attempt of mine.  Feel free to ignore -- we could keep it as my own check before your releases to merge/push ;)

**Comment by yarikoptic** [comment]
#277 seems have passed testing under various chroots -- cool ;)  With that -- I am closing this issue.
