### ISSUE TITLE
Error if branch and file of same name exits - fatal: ambiguous argument 

### ISSUE THREAD

**Issue by gitomator** [gitpython-developers/GitPython#264]
When calling the `iter_commits` method it throws an `fatal: ambiguous argument error` in case the provided branch has the same name as a file. 

Scenario:
```bash
> git branch -a
* test
> ls
test
```

python:
```python
r = git.repo.Repo(".")
b = r.branches[0]
[c for c in r.iter_commits(r)]
'git rev-list test' returned with exit code 128
stderr: 'fatal: ambiguous argument 'test': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

As of git I would simply add `--`, but what am I supposed to do in GitPython?

**Comment by gitomator** [comment]
damn, this was quick :D

**Comment by Byron** [comment]
It's kind of a critical bug I think. Just by pushing a file with a name 'master', I will make all current git-python code break. Gee, gotta push out *v0.3.7* sooner than later !

**Comment by Byron** [comment]
You can watch the development stream [on youtube](http://youtu.be/PRNWbnCEy18).
