### ISSUE TITLE
Can gitdb submodule be removed?

### ISSUE THREAD

**Issue by garious** [gitpython-developers/GitPython#268]
I see gitdb in the requirements.txt.  Can the submodule be removed?

**Comment by Byron** [comment]
It seems you are stating one solution to a problem you are having. Would you share information about that problem with me ?
Thanks

**Comment by garious** [comment]
The problem is confusion.  Is the submodule still in use or a legacy solution that predates `pip`?

**Comment by Byron** [comment]
No, it's not related to `pip` at all, but to developing git-python. The submodules are dependencies that you can just checkout, and run all the tests of git-python without installing any of these. That's what these are there for. `pip` doesn't see the 'ext' folder.
The given argument wouldn't be enough to make me remove these submodules, but maybe the explanation helps to disperse the confusion a little ?

**Comment by garious** [comment]
I think that a cleaner way to develop in that style would be to create a super-project (say gitpython-dev) that adds both GitPython and GitDB as submodules.  Another strategy might be to scrap the submodules and in the readme, suggest adding a `-e` line with a Github URL to requirements.txt.

**Comment by Byron** [comment]
You have been motivated enough to file an issue about this topic, but I still don't understand what this confusion is all about. The submodule 'gitdb' doesn't get in your way at all, it's just an empty folder after ordinary clone, and trying to run tests yields `ImportError: 'gitdb' could not be found in your PYTHONPATH`.
Those who follow the instruction in the README will get the submodule checkout and thus are fine. Others can use pip to get dependencies differently and be fine too.
Maybe some sort of `info.txt` in `git/ext` would help to get the part with the confusion under control. What do you think ?

**Comment by garious** [comment]
I'm just trying to understand why this Python repo is doing things differently than the others.  Thanks for the replies.  You can close this issue.

**Comment by Byron** [comment]
I think the answer to that one is that gitpython was my first bigger open source python project, and from day one I struggled with the standard tools python provided, namely setup tools. Using plain git to solve certain issues was easier for me than fumbling around with what might have been standard. The remnants of this ignorance are here to this day, and shall serve as signpost for others on how not to do it :).
