### ISSUE TITLE
GitPython not returning error

### ISSUE THREAD

**Issue by tardis4500** [gitpython-developers/GitPython#271]
When I run the command from the command line
    git push -u --all origin
 it fails with
    remote: import failed: User not permitted to commit
and exit code of 1.

But doing the same thing programmatically in GitPython does not show any error at all even though I can see the push was unsuccessful because the changes were not pushed.

**Comment by Byron** [comment]
I believe to have found the source of this issue: For some reason, it will only treat exit code 128 as error, as [can be seen here](https://github.com/gitpython-developers/GitPython/blob/master/git/util.py#L162).

This should probably just re-raise - at least I can't see why there is this kind of special treatment.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](http://youtu.be/5XQ4NOrpnBA).
