### ISSUE TITLE
git log -L rejected despite being correct

### ISSUE THREAD

**Issue by gausie** [gitpython-developers/GitPython#273]
GitPython seems to not understand the form `git log -L start,end:file` where start is a regex.

**Comment by Byron** [comment]
Will you please tell me what code you execute to get to which error, exactly ? Also:
* which version of GitPython are you using, and on which platform ?

Thanks

**Comment by gausie** [comment]
This is the bit of code I'm executing

```
command = '-L "^/function before/",+5:' + filepath

return repo.git.log(command)
```

I am using v0.3.6 on Linux.

**Comment by Byron** [comment]
I think what you should try to do is to pass each argument as a single string. GitPython executes git without a surrounding shell, so for git your command would look like "a very long single argument", even though it is in fact multiple ones.
Please close this issue if it works for you.

**Comment by gausie** [comment]
Well it *is* one long single argument

It's just `git log -L <argument to -L>`

**Comment by Byron** [comment]
What about this:

```python
repo.git.log('-L', '"^/function before/",+5:' + filepath)
```

**Comment by gausie** [comment]
Unfortunately I still get the same error.

**Comment by Byron** [comment]
An error you never posted here despite me asking for it. I'd like to see the full stack trace.

**Comment by Byron** [comment]
I have just had  a look at it again, and realized that I am totally out of ideas here. As there is absolutely no evidence that this is related to GitPython at all, you are just using the git command wrapper, I am closing this issue.
You may find asking a question on StackOverflow (using the `GitPython` tag) more helpful - also I recommend to be prepared to post more information right off the bat, including the note that says it is 'rejected'.
