### ISSUE TITLE
ez_setup not in requirements?

### ISSUE THREAD

**Issue by broganross** [gitpython-developers/GitPython#278]
I'm doing an install from source with version 1.0.0 from Pypi onto a CentOS 6.5 machine using python 2.7.3, and when I try running setup.py install I get an ImportError for ez_setup.  But ez_setup isn't in the requirements.txt.
That's all.

**Comment by Byron** [comment]
Thanks for the hint. Actually I don't know how this is supposed to be done in the python world, also I didn't write `setup.py`. Do you know that adding `ez_setup` (or `setuptools`) to requirement.txt would fix the issue ?
If so, that could easily be done I suppose. Thanks for your reply.

**Comment by broganross** [comment]
I'm honestly not sure.  I think ez_setup might be an odd ball.  Shortly after I ran into this I had to stop work on it.  I'll have to check it out when I get minute

**Comment by Byron** [comment]
Thanks, I will also see if I can reproduce this on a Centos VM, maybe even on a freshly installed one.

**Comment by broganross** [comment]
So, I guess since this installs fine with pip that it isn't really an issue.  Since that's what the requirements.txt is for.  I was doing a weird case where I'm building everything from source instead of just using pip, and the requirements.txt is a nice starting point to find the dependencies.
