### ISSUE TITLE
Brokenness fetching from a github repo which has merged a pull request

### ISSUE THREAD

**Issue by kergoth** [gitpython-developers/GitPython#28]
Try fetching from, for example, git://github.com/kergoth/oe-core-template.  The reason it blows up is as far as I can tell, the remote end has a ref (not a tag) which is outside of refs/heads/ and refs/tags/ (it's refs/pull/1/head and refs/pull/1/merge). When it fetches these remotes, the fetch_line has no ref type specified at all:

9e30b7d61417455edbbc4617eb9eef9341255bb5        not-for-merge   'refs/pull/1/merge' of git://github.com/kergoth/oe-core-template

And results in, as you'd expect:

  File "/home/kergoth/.local/lib/python2.7/site-packages/GitPython-0.3.1-py2.7.egg/git/db/cmd/base.py", line 119, in <genexpr>
    for err_line,fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/home/kergoth/.local/lib/python2.7/site-packages/GitPython-0.3.1-py2.7.egg/git/db/cmd/base.py", line 442, in _from_line
    raise TypeError("Cannot handle reference type: %r" % ref_type_name)
TypeError: Cannot handle reference type: "'refs/pull/1/head'"

**Comment by jantman** [comment]
@Byron thanks so much. I can confirm that 0.3.2.1 fixes the probelm when fetching GitHub remotes with pull refs (i.e. `fetch = +refs/pull/*/head:refs/pull/origin/*`)

**Comment by Byron** [comment]
Thanks for verifying this ! I am gladly closing this issue !
