### ISSUE TITLE
GitPython magles my .gitconfig

### ISSUE THREAD

**Issue by moben** [gitpython-developers/GitPython#285]
I have a couple of aliases in my .gitconfig (which I am slightly embarrassed to share, since they are horrible). When running the GitPython tests, these get mangled from

    [alias]
    	rbi = "!g() { git rebase -i origin/${1:-master} ; } ; g"
    	expush = "!f() { git branch -f tmp ; { git rbi $1 && git push ; } ; git reset --hard tmp ; git rebase origin/${1:-master}; } ; f"

into

    [alias]
    	rbi = !g() { git rebase -i origin/${1:-master}	expush = "!f() { git branch -f tmp ; { git rbi $1 && git push ; } ; git reset --hard tmp ; git rebase origin/${1:-master}; } ; f

**Comment by moben** [comment]
forgot to mention: 
cPython version: 2.7.9
GitPython version: current master 5fe80b03196b1d2421109fad5b456ba7ae4393e2

**Comment by Byron** [comment]
Thank you ! 
This seems *critical* as it implies that GitPython is rewriting your `~/.gitconfig` file while the tests are running ?
Can you confirm I understood this correctly ?

**Comment by moben** [comment]
yes, that is indeed the case. It also tries to rewrite /etc/gitconfig, as far as I can tell, but that fails of course.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](http://youtu.be/B7dNOXLc63E).

**Comment by moben** [comment]
Thanks for fixing this so fast!
