### ISSUE TITLE
__eq__ barfs with Non-git object comparisons

### ISSUE THREAD

**Issue by jerpat** [gitpython-developers/GitPython#310]
Obviously this partial stack trace isn't from master, but the problem is still in master

    if data in [None, ()]:
  File "/usr/lib/python2.7/dist-packages/git/util.py", line 347, in __eq__
    return self.name == other.name and self.email == other.email
AttributeError: 'NoneType' object has no attribute 'name'

__eq__ should return false if the other item is None, a native Python type or type() != <a git object>

**Comment by Byron** [comment]
Thanks for letting me know. 
If I remember correctly though, I didn't put in any checks as to me this is not expected to work. It didn't seem worth slowing down equality comparisons for something that shouldn't happen in the first place.

Would you provide an example where such a comparison of heterogenous types is natural ?

**Comment by Byron** [comment]
Closed due to inactivity. Please comment to get it reopened.
