### ISSUE TITLE
Provide/document a way how to find out the current version of GitPython

### ISSUE THREAD

**Issue by rholy** [gitpython-developers/GitPython#311]
Because of the problem which I've described under https://github.com/gitpython-developers/GitPython/commit/96c6ab4f7572fd5ca8638f3cb6e342d5000955e7, I'd like to ask you to provide this information so that one can use the GitPython version to write a software which must be compatible with different GitPython versions.

**Comment by Byron** [comment]
If GitPython was installed from *Pypi*, you can access version information like so:

```
import git
git.__version__
```

If a version from GitHub is used, the said variable will hold the value `git` though, which would make it hard to make a decision unless one would be willing to assume it is the very latest dev version.

Do you find this information helpful ?

**Comment by rholy** [comment]
If you document that there is this variable and how to parse it so that on can test whether the current GitPython version is greater that given version, I'd be perfectly satisfied :-)

**Comment by PonteIneptique** [comment]
Sorry to join without being invited, but wouldn't if be possible with normal tools such as : 

```python
from distutils.version import LooseVersion, StrictVersion
LooseVersion("2.3.1") < LooseVersion("10.1.2")
StrictVersion("2.3.1") < StrictVersion("10.1.2")
```
http://stackoverflow.com/questions/11887762/how-to-compare-version-style-strings

**Comment by Byron** [comment]
A new release was just made to pypi 😁 (*see #298*) !

**Comment by stsewd** [comment]
Agreed with https://github.com/gitpython-developers/GitPython/issues/311#issuecomment-161214616, this just needs documentation
