### ISSUE TITLE
Provide `datetime` version of `comitted_date` and `authored_date`

### ISSUE THREAD

**Issue by cool-RR** [gitpython-developers/GitPython#328]

**Comment by Byron** [comment]
Please see #327 for the reason this has been closed.

**Comment by cool-RR** [comment]
Is it not clear why this is needed? I need the date and time in which a
commit was made. I could make a function to translate to Python datetime,
but it would be best if I could get that information directly from the
commit object without converting.

**Comment by Byron** [comment]
The return value of the mentioned methods is exactly what is stored in git. Built-in conversion methods to all the suitable date and date-time representations out there seem unfeasible.
Therefore, clients will have to convert these values to match their specific requirements.

**Comment by cool-RR** [comment]
"all the suitable date and date-time representations" There's a very
standard model in Python for datetimes and that's the `datetime.datetime`
class. On it there is a method strftime which lets you format time in
whatever display standard you want. So supplying the datetime in
`datetime.datetime`
format would make life easy for people wanting to represent the datetimes
in whichever format they want. Note that this is the approach that Django
takes, among many other packages, when exposing datetime fields.
