### ISSUE TITLE
Prints to stderr from library

### ISSUE THREAD

**Issue by j2sol** [gitpython-developers/GitPython#33]
git/objects/commit.py has a few places where it will print to stderr if unable to decode a stream from the repo.  This has ill effect on client callers to the library.  In my case, I'm making use of GitPython in a git update hook, and this stderr print is making its way back to the user's console and confusing them when they push.

Can we make these prints optional?

**Comment by Byron** [comment]
Python logging is used in 0.3.3 already, which is now online on [pypi](https://pypi.python.org/pypi?:action=display&name=GitPython&version=0.3.3) too.
