### ISSUE TITLE
"Checking out files" not covered by operation names in RemoteProgress 

### ISSUE THREAD

**Issue by phaase** [gitpython-developers/GitPython#330]
When cloning a repository the following message is printed to stderr repeatedly: 
"Operation name u'Checking out files' unknown - skipping line 'Checking out files:   1% (216/11210)'".

1. Does it makes sense to add the operation 'Checking out files' to the list of operations in the RemoteProgress._parse_progess_line()? (see https://github.com/gitpython-developers/GitPython/blob/master/git/util.py#L162)
2. Shouldn't the error logged by using the logging mechanism and not printed to stderr directly? (https://github.com/gitpython-developers/GitPython/blob/master/git/util.py#L242)  

(Environment: Windows 7, Python 2.7.10, GitPython 1.0.1)

**Comment by Byron** [comment]
Thanks for posting this issue !

As a quick-fix the respective line was removed.

* About 1) - It seems like a good thing to do
* About 2) - I'd agree to that too !

If you like you could submit a PR with the changes. They should be easy to implement - your questions and code-links show that you are nearly there already.
What do you think ?
