### ISSUE TITLE
Is there a way to force a git push?

### ISSUE THREAD

**Issue by g12mcgov** [gitpython-developers/GitPython#334]
Hi guys, 

I'm using GitPython to commit and push some changes in my Python application. However, sometimes my developers and I want to force push the commit (```git push --force```) instead of sometimes the app failing because it's behind the HEAD of the repository. 

Is there an option you can pass into the ```git.push()``` method? I haven't seen it documented anywhere and I figured I might as well ask.

Thanks.

**Comment by g12mcgov** [comment]
Never mind, I made a random guess after reading through the source code, and found you can force it via the following keyword argument.

```python
repo.git.push(force=True)
```

And that will do it. This should be documented somewhere.

**Comment by Byron** [comment]
Great to hear that intuition led to the solution !
Indeed, the arguments to the `<repo>.git.*` methods are not documented in the tutorial, and I couldn't easily find explicit documentation about it elsewhere either. Users would certainly benefit from an update, and maybe you will feel like contributing to the documentation at some point - PRs are always welcome.

In short, this is how python arguments are translated to the command-line:

* `m=True` -> `-m`
* `m="foo"` -> `-mfoo`
* `message="foo"` -> `--message "foo"`
* `-somethingveryspecial` -> `-somethingveryspecial`
 - With non-keyword-arguments, the order is kept as is
