### ISSUE TITLE
git-add doesn't seem to work on submodules

### ISSUE THREAD

**Issue by kgadek** [gitpython-developers/GitPython#335]
It seems that `index.add` doesn't work with submodules. Found exactly same issue/question on [stackoverflow](http://stackoverflow.com/questions/31835812/gitpython-how-to-commit-updated-submodule).

Reproduction
---------

First, some shell:
```bash
git init master_repo
cd master_repo
echo "First" > progress_simulator
git add progress_simulator
git commit -m 'First commit'
git submodule add -b master git@github.com:gitpython-developers/GitPython.git subrepo
git commit -m 'Second commit: subrepo'
```

Now, the Python:
```python
import git
master_repo = git.Repo('.')
[subrepo_sm] = master_repo.submodules
subrepo = git.Repo(subrepo_sm.path)
with open('subrepo/interference.txt', 'w'): pass
subrepo.index.add(['interference.txt'])
subrepo.index.commit('My intrusion into this project')
master_repo.index.add([subrepo_sm])
```

Expected vs result
-------

I expected to see `master_repo` index acknowledge that the `subrepo` submodule pointer changed. However, nothing happens.

System info
-----

```bash
$ python -V
Python 3.4.3

$ git --version
git version 2.4.2
```

**Comment by Byron** [comment]
Thanks for the awesome issue ! I wished all of them would be made that thoroughly !

Even though I am working on figuring out the *GitPython* way, one should always be able to use git directly such as in `master_repo.git.add(subrepo_sm.path)`, which will add the submodule correctly. Now one will be able to commit the staged changes.

I shall keep you posted.

**Comment by Byron** [comment]
There now is a new test which shows how to do it in a pythonic fashion. The [stackoverflow question](http://stackoverflow.com/questions/31835812/gitpython-how-to-commit-updated-submodule/31898678#31898678) was answered showing the mentioned way, and a slightly simpler one.

Both ways show that a change in GitPython is not required, even though adding changed submodules to the index seems a bit more difficult/involved than one might hope when using *GitPython* directly.

**Comment by kgadek** [comment]
Thanks! I'll look at it tomorrow :)

**Comment by Byron** [comment]
That's a good idea ! Apparently the approach only works in py2.6 - travis fails in all other versions. It's ... odd.

**Comment by Byron** [comment]
Ok, just a bug in the test - I think chances are travis will confirm this is fixed now.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/_SeJbHP3_c4).

*`GitPython #19 [issue 335 - how to add submodules to the index]`*

[\![thumb](https://i.ytimg.com/vi/_SeJbHP3_c4/mqdefault.jpg)](https://youtu.be/_SeJbHP3_c4)
