### ISSUE TITLE
test_untracked_files UnicodeEncodeError:

### ISSUE THREAD

**Issue by yarikoptic** [gitpython-developers/GitPython#338]
```
======================================================================
ERROR: test_untracked_files (git.test.test_repo.TestRepo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/python-git-1.0.1+git137-gc8b8379/git/test/lib/helper.py", line 121, in repo_creator
    return func(self, rw_repo)
  File "/tmp/buildd/python-git-1.0.1+git137-gc8b8379/git/test/test_repo.py", line 340, in test_untracked_files
    fd = open(fpath, "wb")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 47: ordinal not in range(128)

----------------------------------------------------------------------
```

**Comment by Byron** [comment]
I cannot reproduce the issue with the code at c8b8379, neither using py2.7 or py3.4, on OSX.
Can you provide more information ?

**Comment by yarikoptic** [comment]
Partially my bad ;)  locale was set to C so encoding of the tricky unicode filename wasn't possible.  I will set it to utf8 for test.  If you would like you could make a safeguard for such cases such as the one we have in datalad

```python
    try:
        filesysencoding = sys.getfilesystemencoding()
        test_fpath_encoded = test_fpath.encode(filesysencoding)
    except UnicodeEncodeError:
        raise SkipTest("Environment doesn't support unicode filenames")
```
Feel free to close as is

**Comment by Byron** [comment]
Wow, that is unexpected ! I have set `LC_ALL` to C as well, and it still works fine.
In any case, I wouldn't have expected this to be able to fail on filesystem-level.

Thanks for the suggestion - for now I would probably prefer to just keep the test barking in case something is wrong with it, also in the hopes that you or I remember the case should it occour again.

Cheers !
