### ISSUE TITLE
Git.custom_environment not working for Repo.clone_from

### ISSUE THREAD

**Issue by daniel-yavorovich** [gitpython-developers/GitPython#339]
Dear Sirs/Madams,

I have problem with using Git.custom_environment and Repo.clone_from methods.

My code:
```
ssh_cmd = 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i {}'.format(ssh_key_path)
with repo.git.custom_environment(GIT_SSH_COMMAND=ssh_cmd):
        repo.clone_from(url, dst_path, branch=branch})
```

*clone_from* method not use custom ssh command.

it's my fault or problem is the code?

Thank you.

**Comment by Byron** [comment]
Hi Daniel,

The code you have been using doesn't work as `clone_from` is a class method. Thus it doesn't know the state of the configured `Repo` instance referred to by `repo`.

Instead what you could do is to use the `env` keyword parameter of `clone_from` such as in this example:

```python
Repo.clone_from(url, dst_path, branch=branch, env=dict(GIT_SSH_COMMAND=ssh_cmd))
```

Last but not least, please be sure you are using git 2.3 or newer, as `GIT_SSH_COMMAND` was only recently introduced. Additional notes about the `GIT_SSH_COMMAND` environment variable can be found in the [git-python docs][gp_docs].

I hope that helps !

[gp_docs]: http://gitpython.readthedocs.org/en/stable/tutorial.html#handling-remotes

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/9dsIIGew20c).

*`GitPython #20 [issue 339 - GIT_SSH_COMMAND and class-methods]`*

[\![thumb](https://i.ytimg.com/vi/9dsIIGew20c/mqdefault.jpg)](https://youtu.be/9dsIIGew20c)

**Comment by daniel-yavorovich** [comment]
This is awesome! Thank You for exhaustive response!

**Comment by daniel-yavorovich** [comment]
This is awesome! Thank you for exhaustive response!
