### ISSUE TITLE
Treating stdout and stderr at the same time

### ISSUE THREAD

**Issue by StyXman** [gitpython-developers/GitPython#342]
In functions like `FetchInfo._get_fetch_info_from_stderr()` you say:

        # TODO: Use poll() to process stdout and stderr at same time

Wouldn't it be just simpler to redirect `stderr` to `stdout`?

**Comment by Byron** [comment]
This line is not existing anymore in the latest version on github. As my credentials to Pypi are not working anymore, I am unable to provide updates through that channel either.

You might find that the underlying issue you were seeing is solved with the very latest version you will find here. Please let me know if that is indeed the case.

**Comment by Byron** [comment]
A new release was just made to pypi 😁 (*see #298*) !
