### ISSUE TITLE
How to get branch name on detached head?

### ISSUE THREAD

**Issue by sirvon** [gitpython-developers/GitPython#343]
I'm getting this error frequently....

```bash
TypeError: HEAD is a detached symbolic reference as it points to XXXXXXXXX
```
No way to avoid it, as I'm  not in control of the system at hand.

But I still need the branch name.

Is there anyway to get the branch name even with a detached head?

**Comment by Byron** [comment]
In fact there is no branch name if the `HEAD` reference is detached. Maybe [this resource](http://gitolite.com/detached-head.html) will be helpful to you.

Before asking for the name, one could check for the state of the symbolic reference using the `is_detached` property.

Please let me know if this solves it for you.

**Comment by Byron** [comment]
Closed due to inactivity. Please comment to get it reopened.
