### ISSUE TITLE
does not work with GITs 2.5 worktree feature

### ISSUE THREAD

**Issue by crepererum** [gitpython-developers/GitPython#344]
**Steps to reproduce (assumes GIT >= 2.5 and a repo with at least 2 branches)**
 - `git checkout <whatever>`
 - `git worktree add /tmp/foo another_branch`
 - go to `/tmp/foo`
 - execute: `import git; git.Repo('.')` in Python
 - results in `git.exc.InvalidGitRepositoryError`

**Comment by Byron** [comment]
Thank for letting me know !

As GitPython is in maintenance mode, I won't be adding any new features. However, I added a check to throw an exception specific to worktrees, letting people know the feature is not supported that way.

Thanks for your understanding

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/P9gLThg1cLE).

*`GitPython #23 [issue 344 - explicitly state worktrees are unsupported]`*

[\![thumb](https://i.ytimg.com/vi/P9gLThg1cLE/mqdefault.jpg)](https://youtu.be/P9gLThg1cLE)

**Comment by fooishbar** [comment]
@Byron Can this be reopened, with the advent of 2.x?

**Comment by Byron** [comment]
Hi @fooishbar , the reason for closing this issue is still valid, despite the recent major release. The latter just means there have been breaking API changes, that could affect people negatively.

**Comment by fooishbar** [comment]
@Byron That's a shame. Do you know of any other Python-based git libraries which are tracking new Git features, e.g. worktrees?

**Comment by Byron** [comment]
@fooishbar I don't, but that means nothing. Most people might help themselves by using GitPython to call git in a more pythonic fashion, which is why this library is still used a lot.

**Comment by fooishbar** [comment]
@Byron OK, thanks!

**Comment by KellyDeveloped** [comment]
Hi, I was wondering if there was any support for this issue yet?

**Comment by hilkoc** [comment]
It would be great if support for additional worktrees is added. Now I'll have to abandon GitPython and find another solution.

**Comment by KellyDeveloped** [comment]
For future reference - I figured out how to use worktree. It's not wrapped but interacting with Repo.git manually works perfectly fine.

Tutorial here; https://github.com/gitpython-developers/GitPython/issues/719
