### ISSUE TITLE
Multiple parent arguments for git.commit_tree()

### ISSUE THREAD

**Issue by StyXman** [gitpython-developers/GitPython#345]
I'm using `GitPython` for very advanced stuff, so it's possible that what I need is not really part of the intended public for this project. Anyways...

I'm calling `git.comit_tree()`, which in turn calls `git commit-tree`. the problem is that the command allows to specify several parents by using several times the `-p` option, but the way that `GitPython` creates these arguments for the command, it's not possible.

I was thinking of allowing things like `git.commit_tree(.., p=[p1, p2])` and the command processing core resolve that to `-p p1 -p p2`. What do you think?

**Comment by Byron** [comment]
What you could try is to explicitly state all arguments in order like so:

```python
repo.git.commit_tree('-p', 'p1', '-p', '-p2')
```

This can also be combined with *kwargs*:

```python
repo.git.commit_tree('-p', 'p1', '-p', '-p2', option_without_argument=True, option='value')
```

Please let me know if this works for you.

**Comment by Byron** [comment]
Closed due to inactivity. Please comment to get it reopened.
