### ISSUE TITLE
Config parser doesn't handle config files that have options with no value.

### ISSUE THREAD

**Issue by tomprince** [gitpython-developers/GitPython#349]
For example
```
[color]
ui
```

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/q86DSYO1Z9g).

*`GitPython #24 [issue 349 - handle config options with no values]`*

[\![thumb](https://i.ytimg.com/vi/q86DSYO1Z9g/mqdefault.jpg)](https://youtu.be/q86DSYO1Z9g)
