### ISSUE TITLE
'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by masarliev** [gitpython-developers/GitPython#35]
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'groups'
Exception Location:	/usr/local/lib/python2.6/dist-packages/git/diff.py in _index_from_patch_format, line 301
Python Executable:	/usr/bin/python
Python Version:	2.6.6

this happens when trying to "Swap two inputs" .

commit = repo.commit()
diff = commit.diff('HEAD~1', create_patch=True, R=True)

**Comment by Byron** [comment]
I have added [an assertion](https://github.com/gitpython-developers/GitPython/blob/master/git/diff.py#L305) to check for unusual diff formats that we might not be able to parse. It would be useful to know the repository that caused this issue, to help reproducing it.
However, for now I will close this issue, assuming that in the past years, the diff implementation was adjusted to the point it's actually working.
