### ISSUE TITLE
It should be straightforward to isolate GitPython from a user/system configuration.

### ISSUE THREAD

**Issue by tomprince** [gitpython-developers/GitPython#350]
When automating part of a build or release process, the behavior should not depend on the local developer configuration, thus, there should be a way to ignore that configuration.

**Comment by Byron** [comment]
In case you are referring to the [`Repo.config_reader(...)`](http://gitpython.readthedocs.org/en/stable/reference.html?highlight=config_reader#git.repo.base.Repo.config_reader) method, you will find that there is an option to specify the sources included in the configuration reader.

Also I made sure that the `Remote` implementation has no way of picking up non-repository configuration files, which previously would have been a possibility at least.

If this doesn't solve your issue, please feel free to leave a comment telling me how I exactly I can reproduce it.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/JmqMH9BejsE).

*`GitPython #25 [issue 350 - isolation of git configuration files]`*

[\![thumb](https://i.ytimg.com/vi/JmqMH9BejsE/mqdefault.jpg)](https://youtu.be/JmqMH9BejsE)
