### ISSUE TITLE
Can't create empty tree object

### ISSUE THREAD

**Issue by samskiter** [gitpython-developers/GitPython#355]
I'm trying to get the staged changes in a repo for a git hook I'm writing. In order to deal with empty repositories, git has a 'magic' sha: 4b825dc642cb6eb9a060e54bf8d69288fbee4904

I'm trying to diff index against this but getting a bad object exception. Code is:

```
repo = git.Repo()

try:
	repo.rev_parse("HEAD")
	against = "HEAD"
except BadObject:
	# the magic first commit
	against = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"

ag = repo.commit(against)
for fileName in repo.index.diff(ag):
	print fileName
```

Am I doing something wrong?

**Comment by Byron** [comment]
In GitPython, there is no magic behind `4b825dc642cb6eb9a060e54bf8d69288fbee4904`. `repo.index.diff` apparently attempts to convert the given SHA into an object using [`repo.rev_parse()`](https://github.com/gitpython-developers/GitPython/blob/master/git/index/base.py#L1195), which must fail as there is no such object.

The SHA mentioned here is indeed magic, and used behind `EMPTY_TREE_SHA1_HEX` in the git source code - there is special handling that GitPython completely ignores, i.e. does not implement. Therefore it currently seems impossible to deal with the empty-repository case more gracefully than to catching exceptions and falling back to manually parsing the output of `repo.git.status()`.

**Comment by samskiter** [comment]
`repo.index.diff(None, staged=True)` was ok for me for now. Worked in a brand new repo

**Comment by Byron** [comment]
Thanks for letting me know - hopefully this issue will help others as well.

If you mind me closing this issue, please let me know in the comment.
