### ISSUE TITLE
Windows : ImportError: No module named pwd on util.py

### ISSUE THREAD

**Issue by firm1** [gitpython-developers/GitPython#356]
When i try to build gitpython on Windows Server i have this error message.

```powershell
File "C:\project\.tox\back\lib\site-packages\git\objects\commit.py", line 318, in create_from_tree
    committer = committer or Actor.committer(cr)
  File "C:\project\.tox\back\lib\site-packages\git\util.py", line 416, in committer
    return cls._main_actor(cls.env_committer_name, cls.env_committer_email, config_reader)
  File "C:\project\.tox\back\lib\site-packages\git\util.py", line 386, in _main_actor
    default_email = get_user_id()
  File "C:\project\.tox\back\lib\site-packages\git\util.py", line 152, in get_user_id
    return "%s@%s" % (getpass.getuser(), platform.node())
  File "c:\python27\Lib\getpass.py", line 157, in getuser
    import pwd
ImportError: No module named pwd
```

After search, the only solution is try [this hack](https://t37.net/on-getting-the-running-process-user-under-python-and-supervisord.html) on [utiy.py](https://github.com/gitpython-developers/GitPython/blob/master/git/util.py#L14) file.

Then use this :  

```python
try:
    import pwd
except ImportError:
    import winpwd as pwd
import os

def get_user_id():
    """:return: string identifying the currently active system user as name@node"""
    return "%s@%s" % (pwd.getpwuid(os.getuid()).pw_name, platform.node())
```

instead of 

```python
import getpass

def get_user_id():
    """:return: string identifying the currently active system user as name@node"""
    return "%s@%s" % (getpass.getuser(), platform.node())
```

What do you think about that ?

**Comment by Byron** [comment]
`getpass.getuser` is supposed to be a [portable](https://docs.python.org/2/library/getpass.html) way of obtaining a user id, which is also used [in the latest version of GitPython](https://github.com/gitpython-developers/GitPython/blob/master/git/util.py#L150).

[GitPython 0.3.2.1](https://github.com/gitpython-developers/GitPython/blob/0.3.2.1/git/util.py#L126) is the first version with the fix - could it be that you are using a version older than that ?

**Comment by firm1** [comment]
I don't know why, but this function is not really portable (Windows Server 2012). I use the latest release (1.0.1) of gitpython.

**Comment by firm1** [comment]
On [this project](https://github.com/ansible/ansible/issues/7049) they are same issue with `pwd`.

**Comment by Byron** [comment]
As this seems to be an issue with the python distribution, there seems to be nothing GitPython can do. Please let me know if I have overlooked anything though,

**Comment by cblegare** [comment]
If anyone is struggling with this, here is a workaround:

Since `pwd` is only availble on Unix, Python tries to guess the current user's username from the following environment variables: 

- LOGNAME
- USER
- LNAME
- USERNAME

If for some reason none of these are set on your windows machine (it was my case when running tests on a build machine), find some way to define one of these variables in order to prevent python to try to import `pwd`.

**Comment by schlamar** [comment]
This is a tox issue: https://github.com/tox-dev/tox/issues/1455

A workaround would be to set in tox.ini

    [testenv]
    passenv = USERNAME

**Comment by nmz787** [comment]
`tox.ini` addition was the fix. Just in case search engine indexing might benefit from more keywords... I got here by searching:
`ModuleNotFoundError: No module named 'pwd' "getpass.py"`

and here was my traceback:
```
C:\Python36\lib\getpass.py:168: in getuser
    import pwd
E   ModuleNotFoundError: No module named 'pwd'
```

**Comment by eric-wieser** [comment]
#1314 should fix this.
