### ISSUE TITLE
Do diffs detect renamed files properly?

### ISSUE THREAD

**Issue by ondrowan** [gitpython-developers/GitPython#36]
I'm using following code for detecting changes between commits:

```python
diff = commit.diff(*parents, R = True, M = True)
```

Everything works ok in except of renames. When I use ```M = True``` it should detect renames instead of add / deletions. However, when I use it, it doesn't return anything. Is this a bug or did I just misunderstand how to use it?

The thing I noticed in ```git log -M``` is that instead of ```R``` it shows me ```R100``` (not really sure whether it's normal or not):

> commit a8b61b9d18350a3d44e50fc9614279a2654b646d
> Author: ondrowan <...>
> Date:   Sat Nov 5 12:16:21 2011 +0100
>
> Moved thing
>
> R100    thing   newdir/moved_thing

**Comment by Byron** [comment]
The reason for this not working was that by default, it would only diff in `--raw` format, thus not creation patches. In that mode, previously it wouldn't support renames, which was explicitly enabled only if `create_patch=True`.
Now renames are always detected, and the [raw mode parser](https://github.com/gitpython-developers/GitPython/blob/master/git/diff.py#L347) will detect this as well.
The test suite was adjusted with an additional [test case](https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_diff.py#L59).
