### ISSUE TITLE
Specifying subprocess flags to disable popup of cmd in Windows environment

### ISSUE THREAD

**Issue by yocheah** [gitpython-developers/GitPython#360]
I am using py2exe with gitpython and wondering if there is a way to specify a flag in gitpython's use of subprocess that disables the popup of cmd in the Windows environment, something like
     
`creationflags=win32process.CREATE_NO_WINDOW`

I originally posted my corresponding question here (http://stackoverflow.com/questions/33310791/disable-popup-of-cmd-windows-when-using-gitpython-and-py2exe)

**Comment by yocheah** [comment]
Never mind about this. Found out that this can be resolved using Git.USE_SHELL=True

**Comment by Byron** [comment]
Thanks for letting me know how the issue was solved - I had absolutely no idea how to fix it. Great to see you updated the stackoverflow question as well - maybe others will find it useful.
