### ISSUE TITLE
Timezone offset from UTC is wrong when not in DST

### ISSUE THREAD

**Issue by pquentin** [gitpython-developers/GitPython#362]
It turns out that the `Europe/Paris` timezone just got **out** of DST and is now in UTC+1 back from UTC+2. It means that dates should currently be recorded with +0100. `date` does it correctly:

    $ TZ='Europe/Paris' date +"%Y-%m-%dT%H:%M:%S%z"
    2015-11-04T08:45:34+0100

However, GitPython uses `time.altzone` to guess dates in commits, which yields +0200 instead of +0100:

    $ TZ='Europe/Paris' python -c 'import time; print(-time.altzone/3600)'
    2.0

While the date is still correct, the timezone is now wrong. Indeed, using `time.altzone` is only correct when:

 1. `time.daylight` is non zero, eg. the current timezone has a DST defined at some point in the year (always true for Europe/Paris, but always false for Indian/Reunion)
 2. and DST is currently active, which you can check with `time.localtime().tm_isdst > 0`.

To fix this issue, you should [use this code to get the UTC offset in seconds](http://stackoverflow.com/a/3168394/481584).

    is_dst = time.daylight and time.localtime().tm_isdst > 0
    utc_offset = time.altzone if is_dst else time.timezone

You still need to multiply by -1 and divide by 3600, but you will get the correct offset this way.

Thank you!

**Comment by Byron** [comment]
Thanks for taking the time to create this awesome and informative issue ! It's much appreciated.

As I am unable to post new releases to pypi, I hope you will be able to use the latest version on HEAD and let me know if this fixes your problem.

**Comment by pquentin** [comment]
Thank you for the fix! It works perfectly.
