### ISSUE TITLE
`git diff --stat` is not implemented.

### ISSUE THREAD

**Issue by yiu31802** [gitpython-developers/GitPython#363]
I want to have `commit.stats.files`-like object for arbitrary Diff object.

**Comment by Byron** [comment]
As gitpython is in maintenance mode, no new features will be implemented by the maintainers.
Thus I am closing the issue, noting that you are welcome to submit a PR to get such a feature into master.

**Comment by ani-hovhannisyan** [comment]
Hi, sorry, is this issue still actual?
How can I use "git diff --stat commit2 commit1" command with GitPython ?
This is necessary as I'm going to count changed line numbers in particular files through the history of commits, can I do so?

**Comment by Byron** [comment]
It's definitely possible to run [arbitrary git commands](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly) and parse their output.
