### ISSUE TITLE
Accessing files committed by initial commit with GitPython

### ISSUE THREAD

**Issue by sztankatt** [gitpython-developers/GitPython#364]
I'm using GitPython for working with a git repository. To list the files added/deleted/changed I use the following code:

    diff_files = []
    for parent in commit.parents:
        diff_files += [x.b_path for x in commit.diff(parent)]

However, the first commit doesn't have any parents, so this approach fails. Any ideas how might I do it in a different way?

**Comment by Byron** [comment]
Maybe the questions are related, but do you think the *edit* portion of [this question on stackoverflow](http://stackoverflow.com/questions/33916648/get-the-diff-details-of-first-commit-in-gitpython) answers your question ?

```python
EMPTY_TREE_SHA = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"

if not i.parents:
    diff = i.diff(EMPTY_TREE_SHA, create_patch=True, **diffArgs)
else:
    diff = i.diff(i.parents[0], create_patch=True, **diffArgs)
```

**Comment by Byron** [comment]
Closed due to inactivity. Please comment to get it reopened.

**Comment by sztankatt** [comment]
Yes, sorry, since the I solved it similarly as you described in your comment.
