### ISSUE TITLE
Can't fetch the always-present bare tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904

### ISSUE THREAD

**Issue by JordanMilne** [gitpython-developers/GitPython#371]
The [empty tree `4b825dc642cb6eb9a060e54bf8d69288fbee4904` always exists](https://stackoverflow.com/questions/9765453/gits-semi-secret-empty-tree), even in bare git repositories with nothing in `.git/objects`:

```bash
~/tmp/bare_git $ git show 4b825dc642cb6eb9a060e54bf8d69288fbee4904
tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904

```

It's useful to have access to in GitPython for when you want to `.diff()` against a bare repo, but it doesn't always exist on disk, so GitPython can't always find it:

```python
>>> import git
>>> r = git.Repo(".")
>>> r.rev_parse("4b825dc642cb6eb9a060e54bf8d69288fbee4904")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "virtualenv/lib/python2.7/site-packages/git/repo/fun.py", line 304, in rev_parse
    obj = name_to_object(repo, rev)
  File "virtualenv/lib/python2.7/site-packages/git/repo/fun.py", line 120, in name_to_object
    return Object.new_from_sha(repo, hex_to_bin(hexsha))
  File "virtualenv/lib/python2.7/site-packages/git/objects/base.py", line 65, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "virtualenv/lib/python2.7/site-packages/gitdb/db/base.py", line 205, in info
    return self._db_query(sha).info(sha)
  File "virtualenv/lib/python2.7/site-packages/gitdb/db/base.py", line 192, in _db_query
    raise BadObject(sha)
gitdb.exc.BadObject: BadObject: 4b825dc642cb6eb9a060e54bf8d69288fbee4904
```

I've been hacking around it using `git.Tree(repo, binascii.unhexlify("4b825dc642cb6eb9a060e54bf8d69288fbee4904"))` but it might be useful to have easy access to it, or a simplified way to diff against a bare repo.

**Comment by Byron** [comment]
Thanks for posting. It's a known issue, and dealing with the empty tree similarly to how git does it was requested many times.
As git-python is in maintenance mode, I am relying on everyone else to chime in and make the necessary changes.
Thanks for your understanding.

**Comment by nvie** [comment]
Since v2.0, you can pass `git.NULL_TREE` to `.diff()` to do this! ;-)
See also the changelog for v2.0.0: https://github.com/gitpython-developers/GitPython/blob/master/doc/source/changes.rst
