### ISSUE TITLE
how to access remote upstream master branch tree

### ISSUE THREAD

**Issue by greenpau** [gitpython-developers/GitPython#373]
How do I access remote upstream branch tree?

```python
local_active_branch_tree = self.repo.heads[str(self.repo.active_branch)].commit.tree;
local_master_branch_tree = self.repo.heads.master.commit.tree;
remote_upstream_master_branch_tree = ???
```

the doc are silent about it. http://gitpython.readthedocs.org/en/stable/reference.html#module-git.remote
 
```python
class git.remote.FetchInfo(ref, flags, note='', old_commit=None, remote_ref_path=None)
```

**Comment by Byron** [comment]
For questions, please consider using stackoverflow instead, suitable [answers](http://stackoverflow.com/questions/34278837/how-to-access-the-remote-parent-branch-of-my-local-branch-with-gitpython-or-simi) are more likely there and will be made much faster. Just be sure to set the `gitpython` tag.

However, to answer your question explicitly, I believe that [`tracking_branch()`](http://gitpython.readthedocs.org/en/stable/reference.html#git.refs.head.Head.tracking_branch) would be what you are looking for.

```python
import git
repo = git.Repo()

local_active_branch_tree = repo.active_branch.commit.tree
local_master_branch_tree = repo.heads.master.commit.tree
remote_upstream_master_branch_tree = repo.heads.master.tracking_branch().commit_tree
```

**Comment by greenpau** [comment]
@Byron , thank you for the answer!

quick correction to the above:

```
remote_upstream_master_branch_tree = repo.heads.master.tracking_branch().commit.tree
```

**Comment by Abbyyan** [comment]
Thanks a lot. To get the remote branch of each local branch , It works.
```python
heads = repo.heads
for head in repo.heads:
     if str(getattr(repo.heads,str(head)).tracking_branch()) == "origin/master":
          print("yes")
     print(head," ",str(head),"  ",getattr(repo.heads,str(head)).tracking_branch())
```
