### ISSUE TITLE
Possible to send `-l` to `git tag`?

### ISSUE THREAD

**Issue by beedub** [gitpython-developers/GitPython#376]
Is there a way to provide options to `git tag` like `-l`? I tried to `git.TagReference.list_items(repo, '-l dev*')` but doesn't appear to be working

**Comment by Byron** [comment]
I don't think that this is possible directly, but believe it should be straightforward enough to filter tags yourself using python. Please note that `iter_items(...)` is more efficient in these cases.

If you seek a more elaborate reply, I recommend using Stackoverflow for questions, using the `GitPython` tag.
