### ISSUE TITLE
Questions on how to use GitPython

### ISSUE THREAD

**Issue by jgeerds** [gitpython-developers/GitPython#377]
I'm planning to use `GitPython` as a database for my next project and have some further questions that your documentation doesn't cover. The idea is to have a bare repository with a hierarchical structure (using git trees) and UUID named blobs for the data. 

1) Is it possible to commit stream data into a bare repository? The documentation states:
```
Our index implementation allows to stream date into the index, 
which is useful for bare repositories that do not have a working tree.
```
Is there an example for that?

2) What is the simplest workflow for creating new `Blob` objects?

The whole `GitPython` tutorial is rather high-level and just show how to work with existing `Blob` objects. But what is the preferred way to create new ones? What is the first step to get new data into the git store?

**Comment by Byron** [comment]
For questions, I recommend using stackoverflow along with the GitPython tag, as you will obtain answers much faster, and from a bigger audience.

**1)** You might find [this unit-test](https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_index.py#L761) helpful. It's likely you will find examples for all usages of the git index in there as well.

**2)** Please refer to the unit-tests for examples on how to stream into a repository, and obtain index entries.
