### ISSUE TITLE
clone with progress gives "Operation name 'Checking out files' unknown"

### ISSUE THREAD

**Issue by timblechmann** [gitpython-developers/GitPython#381]
cloning a repository with --progress git prints some "Checking out files" lines. gitpython doesn't know them and prints "Operation name 'Checking out files' unknown" to the command line

**Comment by Byron** [comment]
Please try using the latest version from this repository.
The stage mentioned [has been added already](https://github.com/gitpython-developers/GitPython/blob/84869674124aa5da988188675c1336697c5bcf81/git/util.py#L234).
