### ISSUE TITLE
It is not possible to set GIT_PYTHON_TRACE option from python script

### ISSUE THREAD

**Issue by Dmitriusan** [gitpython-developers/GitPython#393]
As documentation states, this option has to be set via environment. But it's impossible to set env variable from inside the program via os.environ. That simply would not work because it would be applied only to subprocesses and not to the program environment itself: http://stackoverflow.com/questions/1506010/how-to-use-export-with-python-on-linux

Why do I need that? For example, in order to implement -v option that is consistent (user should not have to set env variable in addition to specifying -v when launching my program in debug mode). 

BTW, other devs seem also to have a lot of confusion about that:
- http://academia.codeover.org/questions/34964465/gitpython-debug-logs-not-available
- https://github.com/gitpython-developers/GitPython/issues/222 

Thanks in advance

**Comment by Byron** [comment]
The only way to setting or adjusting the verbosity level at runtime is the one stated [in this comment](https://github.com/gitpython-developers/GitPython/issues/222#issuecomment-68597780).

As GitPython is in maintenance mode, features are only added by PR's, and you are welcome to submit one in case you come up with an interface or utility method that makes this clearer.

If you found my note acceptable, please close the issue.
Thanks

**Comment by Dmitriusan** [comment]
@Byron ,
thank you for reply. For now, close the issue and will try to use the way you pointed to, and will see how it goes.
