### ISSUE TITLE
Error messages from failed Git commands not being forwarded correctly

### ISSUE THREAD

**Issue by rrei** [gitpython-developers/GitPython#395]
GitPython version: 1.0.2
File: git/cmd.py
Line: 319
OS: Ubuntu 14.04LTS

The `Git.AutoInterrupt.wait()` method will fail reporting the correct error message from the underlying git command because, if the command exits with a non-zero status code, this method will attempt to read from the subprocess' stderr stream (which has already been closed at this point because of `wait()` I suppose). Therefore, `GitCommandError` is never raised because 'ValueError: I/O operation on closed file' is raised before.

**Comment by Byron** [comment]
When looking at the [code of the latest version](https://github.com/gitpython-developers/GitPython/blob/c4c6851c55757fb0bc9d77da97d7db9e7ae232d7/git/cmd.py#L318), it seems like this particular problem is already fixed.

It will therefore be part of the next patch release.

**Comment by rrei** [comment]
Alright, the new code seems to take care of the problem :) Thanks!
