### ISSUE TITLE
Suggestion: config writer objects as python context managers

### ISSUE THREAD

**Issue by rrei** [gitpython-developers/GitPython#399]
This is just a suggestion for what I think would be a bit more pythonic implementation of the config writer objects that exist throughout gitpython. The basic pattern is:

- get a config writer
- set some values
- call `release()` on the config writer object

```
cw = origin.config_writer
cw.set("pushurl", "other_url")
cw.release()
```

This pattern could be replaced with a context manager by providing the special methods `__enter__()` and `__exit__()` on the object returned by the `config_writer` property. The `release()` call would then occur automatically when the context is left.
The following example would be equivalent to the above:

```
with origin.config_writer as cw:
    cw.pushurl = "other_url"
```
This change could probably be done in a backwards-compatible manner, so everyone would be happy and this great library would become a tiny bit more pythonic :)

**Comment by Byron** [comment]
Thanks for the suggestion ! Someone had the idea already [and implemented it](https://github.com/gitpython-developers/GitPython/blob/c4c6851c55757fb0bc9d77da97d7db9e7ae232d7/git/config.py#L135).

Therefore the feature will be part of the next path release.
