### ISSUE TITLE
Is possible to support AWS S3 as storage?

### ISSUE THREAD

**Issue by abcjjy** [gitpython-developers/GitPython#401]
Use a bucket as central git repo can be very cheap and convenient. Is there an abstract storage layer in GitPython? How can I extend it to support more storage API?

**Comment by Byron** [comment]
I don't think it is as gitpython just uses the `git` commandline program to do any kind of transport (i.e. `fetch`, `push`).

Git-Dulwich, as a pure-python implementation of everything related to git might be a good testing ground for an upcoming implementation.
For GitPython however, I see no such feature coming up, especially as this project is in maintenance mode.
