### ISSUE TITLE
Diff fails on empty repository.

### ISSUE THREAD

**Issue by nemec** [gitpython-developers/GitPython#41]
If you have an empty repository (`git init` in an empty folder), then add files through GitPython, the repository isn't registered as "dirty" and diffs come back empty. For example:

    >>> r = Repo('.')
    >>> r.index.add(["README"])
    >>> r.is_dirty
    False
    >>> r.index.diff(None)
    []

The index.entries property shows the newly added file, but there doesn't seem to be a way to turn it into "this file has been added, but not committed".

**Comment by Byron** [comment]
A lot of time has passed, and plenty of changes were applied to `is_dirty()`. Additionally, there are plenty of tests checking all aspects of it.
Therefore I believe this issue can be closed for now.
