### ISSUE TITLE
1.1.0 release please please please

### ISSUE THREAD

**Issue by yarikoptic** [gitpython-developers/GitPython#416]
I know that I am the loudest whiner demanding releases (last time in https://github.com/gitpython-developers/GitPython/issues/383#issuecomment-183706242), but may be it is finally worth it? ;)

**Comment by nvie** [comment]
Haha, I think 1.1.0 is good to go. @Byron could you roll a release to PyPI?

**Comment by Byron** [comment]
Alright, I am on it just now. In the meanwhile, @nvie , what do you think about becoming a maintainer on PyPi as well ?

**Comment by Byron** [comment]
Oh, and considering we actually have two breaking changes now, I will make it 2.0.0 instead. The breaking ones are 
* drop py2.6 support
* `Diff` objects don't carry the '---' and '+++' strings anymore

**Comment by Byron** [comment]
"Es ist vollbracht !" - see the new [entry on pypi](https://pypi.python.org/pypi/GitPython).

**Comment by Byron** [comment]
It's quite amazing to see how many downloads GitPython still has, it seems to be a whopping 2 million per year !

**Comment by nvie** [comment]
Congrats with the 2.0 release, it's awesome to see it out there! I'll reach out to you over email about the PyPI maintainership, thanks!
