### ISSUE TITLE
Implement License information retrieval as provided in preview by GitHub

### ISSUE THREAD

**Issue by BrunoVernay** [gitpython-developers/GitPython#417]
GitHub does the job of parsing the repository's License file to extract License info https://developer.github.com/v3/licenses/#get-a-repositorys-license

It would be nice to have this available.

**Comment by Byron** [comment]
Thanks for the hint, this can certainly be done. Do you have an idea on how github detects this ?

**Comment by BrunoVernay** [comment]
My hint was to leverage the GitHub work and call their preview API to get the info, not to re-implement the License file parsing.

**Comment by Byron** [comment]
I understood the ticket as such: 

> When using the license file Api of github, it has trouble identifying the one used by gitpython. This ticket asks to adjust the way the license is presented or add more information to allow this to work.

Is this correct ?

**Comment by BrunoVernay** [comment]
Sorry, no : I was thinking about having a  `repo.license.name`  and a `repo.license.key` functions in the GitPython library.
It is a feature request.

**Comment by stsewd** [comment]
This looks like could be more useful as a separated package, don't see how it fits here. Also, it should be implemented to all providers, maybe some of them don't have this kind of feature.

**Comment by Byron** [comment]
Closed on the basis of GitPython being in maintenance mode, and no new features can be accepted unless provided by a PR.
