### ISSUE TITLE
Commit only applies to the HEAD branch in bare repos

### ISSUE THREAD

**Issue by kennethklee** [gitpython-developers/GitPython#418]
GitPython seems to only commit to the HEAD branch in bare repos. Also noticed the same issue with non-bare repos with the active branch (unless you checkout your target branch beforehand).

Though, maybe I'm doing something wrong.

```
import git
import gitdb
from StringIO import StringIO

bare_repo = git.Repo('bare.git')
assert bare_repo.bare
bare_branch = bare_repo.heads['my-branch'] # this branch should exist
bare_branch_index = git.IndexFile.from_tree(bare_repo, bare_branch)

# create new file
filename = 'test-file'
contents = 'foo bar'
buffer = StringIO(contents)
istream = gitdb.IStream('blob', len(contents), buffer)
repo.odb.store(istream)
bare_blob = git.Blob(bare_repo, istream.binsha, 0100644, filename)

# add file and commit to branch
bare_branch_index.add([bare_blob,])
bare_branch_index.commit('add ' + filename)

# at this point, running `git log HEAD` will have your new commit. `git log my-branch` will have not changed at all.

**Comment by kennethklee** [comment]
So it seems, it's me. After reading through the code, `index.commit` has parameters, `parent_commits` and `head`. In the case ^ above, the line `bare_branch_index.commit('add ' + filename)` can be replaced with `bare_branch_index.commit('add ' + filename, parent_commits=[bare_branch.commit], head=False)`

**Comment by kennethklee** [comment]
since the docs don't really tell you, anyone else with this issue can use the following example. note that the index and blob is in-memory.

```
import git
import gitdb
from StringIO import StringIO

# setup repo, branch, and index
repo = git.Repo('bare_repo.git')
branch = repo.create_head('my-new-branch', 'master')
index = git.IndexFile.from_tree(repo, branch)

# create a file
filename = 'test-file'
contents = 'foo bar'
istream = gitdb.IStream('blob', len(contents), StringIO(contents))
repo.odb.store(istream)
blob = git.Blob(repo, istream.binsha, 0100644, filename)

# add the file
index.add([blob,])

# create the commit in the branch
commit = index.commit('add ' + filename, parent_commits=[branch.commit], head=False)
branch.set_commit(commit)
```

**Comment by Byron** [comment]
@kennethklee Sorry for the late reply ! However, I am glad you posted your findings here for others to see - thanks for that ! (*I especially like the sample of how to do things in-memory, using `IStream`s*)
