### ISSUE TITLE
doc/ is missing from pypi tarballs

### ISSUE THREAD

**Issue by yarikoptic** [gitpython-developers/GitPython#420]
which breaks debian package which expects to be able to build -doc pkg

**Comment by yarikoptic** [comment]
actually may be doc/ was never shipped as a part of pypi upload... would you mind adding those files into source distribution? ;)

**Comment by nvie** [comment]
Is that as easy as adding an entry for `doc` [in here](https://github.com/gitpython-developers/GitPython/blob/master/MANIFEST.in#L1-L6)?

**Comment by yarikoptic** [comment]
I guess something like
```
recursive-include doc *
```

**Comment by yarikoptic** [comment]
@nvie do you think you could furnish a new release some time soonish with docs?  no pressure... I just want to know how to proceed (a workaround for now eg by packaging again a git snapshot) or just wait for a release

**Comment by nvie** [comment]
I'm unfamiliar with the build -doc pkg stuff in Debian. How does it work? "Just" including the doc directory with `recursive-include` will only include the doc _sources_ in reStructuredText format in there. I'm pretty sure that's not what you need. Did you mean compiling the docs and sticking the HTML output in the tar file? I'm not aware of any other packages that do this, perhaps link me to an example?

**Comment by yarikoptic** [comment]
On Thu, 28 Apr 2016, Vincent Driessen wrote:

>    I'm unfamiliar with the build -doc pkg stuff in Debian. How does it work?
>    "Just" including the doc directory with recursive-include will only
>    include the doc sources in reStructuredText format in there. 

that is the sources and that is what I need ;)
we then use sphinx to build them:

PYTHONPATH=. sphinx-build -b html doc/source debian/python-git-doc/usr/share/doc/python-git-doc/html


> I'm pretty
>    sure that's not what you need. Did you mean compiling the docs and
>    sticking the HTML output in the tar file? I'm not aware of any other
>    packages that do this, perhaps link me to an example?

nope... do not build anything, just provide doc/ as is in git within released
source tarballs and I would be happy ;)

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by nvie** [comment]
https://pypi.python.org/pypi/GitPython/2.0.2

Cheers!

**Comment by yarikoptic** [comment]
On Thu, 28 Apr 2016, Vincent Driessen wrote:

>    https://pypi.python.org/pypi/GitPython/2.0.2

awesome!  THANKS!

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik
