### ISSUE TITLE
Docs link in pypi is broken

### ISSUE THREAD

**Issue by stuaxo** [gitpython-developers/GitPython#422]
It points here  

http://gitpython.readthedocs.io/en/latest/

Which says
```

You've found something that doesn't exist.

What are you looking for?

Go to the top of the documentation.


        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \
```

**Comment by Byron** [comment]
I couldn't find the link on pypi myself, unfortunately, but can verify that it doesn't work.
Can you help me locate it ? Apparently it's also not mentioned in the source code.
Thank you

**Comment by stuaxo** [comment]
If you scroll down on this page

https://pypi.python.org/pypi/GitPython/2.0.2

underneath where it says "Author"

there is a link to "Documentation" that points at
http://pythonhosted.org/GitPython/

which redirects to

http://gitpython.readthedocs.io/en/latest/

**Comment by stuaxo** [comment]
I guess it's possible this is set in pypi itself, not the code ?

**Comment by stuaxo** [comment]
Maybe this helps ?
http://stackoverflow.com/questions/6521931/how-to-delete-documentation-from-pypi

**Comment by Byron** [comment]
Thanks for all the help, I couldn't have done it without it ! 
It still took me a while to get it done thanks to pypi's absolute awesomeness, but it is done now !
