### ISSUE TITLE
ValueError raised instead of GitCommandError when not authenticated

### ISSUE THREAD

**Issue by stuaxo** [gitpython-developers/GitPython#424]
I have a git repo that needs a key, if I don't enter the password for the key, when using Repo.clone_from or Repo.pull GitCommandError isn't raised.

```
  File "/home/stu/.virtualenvs/ng/local/lib/python3.5/site-packages/git/cmd.py", line 319, in wait
    raise GitCommandError(self.args, status, self.proc.stderr.read())
ValueError: read of closed file
```

^ which is because proc.stderr is closed at this point.

To reproduce, clone from a git repo using a key + a uri like

git@bitbucket.org:blah/blah.git

Then when it prompts you to unlock the key, just press enter (not unlocking) it - similar thing for pull as well.

**Comment by stuaxo** [comment]
Ideally there would be some sort of GitCommandError that let me know the key wasn't authenticated.

**Comment by stuaxo** [comment]
Or possibly GitPython could use paramiko somehow here.

**Comment by Byron** [comment]
Thanks for reporting. When trying to reproduce it, I got the following stacktrace:
```python
/Users/byron/Documents/dev/bdep-oss/lib/git-python/0.3/noarch/git/cmd.py in wait(self, stderr)
    326             if status != 0:
    327                 errstr = read_all_from_possibly_closed_stream(self.proc.stderr)
--> 328                 raise GitCommandError(self.args, status, errstr)
    329             # END status handling
    330             return status

GitCommandError: 'git clone -v git@bitbucket.org:blah/blah.git blah' returned with exit code 128
stderr: 'Cloning into 'blah'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
'

In [30]:
```

In the latest version, v2.0.2, the issue seems to be fixed, as `GitCommandError` is thrown as expected.

**Comment by stuaxo** [comment]
Cheers :)
