### ISSUE TITLE
Simple RemoteProgress example ?

### ISSUE THREAD

**Issue by stuaxo** [gitpython-developers/GitPython#425]
AFAICT from the docs, I can use a Progress object to get output during clone etc... but can't see a simple example of doing that, is it possible ?

I'm trying to work out why things lock up when I do Repo.clone_from ... it's may be related to my key issue in the other ticket, but I have no idea right now.

**Comment by Byron** [comment]
The lock-up could be related to a known issue occurring when one of the git-process channels, usually *stderr*, is full and is not processed by git-python. In any case, please be sure to use the latest version a few fixes have been applied in the meanwhile to alleviate that particular issue.

To answer this question, I may refer to [the gitpython tutorial](http://gitpython.readthedocs.io/en/stable/tutorial.html) - just search for 'progress' there to get an example for how to use the [RemoteProgress](http://gitpython.readthedocs.io/en/stable/reference.html?highlight=remoteprogress#git.remote.RemoteProgress) type.
