### ISSUE TITLE
repo.index create new index on ever reference - surprising

### ISSUE THREAD

**Issue by barry-scott** [gitpython-developers/GitPython#428]
was surprised to find that the index property of Repo created a new IndexFile object on each reference. This would have lead to code with terrible performance if I had not read the source and discovered this. At a minimum this needs a warning in docs.

I would suggest that you either make index stable until the user asked for it to be updated.
Or drop the property in favor of a function that returns a new IndexFile().

**Comment by barry-scott** [comment]
The same property does lots of work goes for untracked_files as well.

**Comment by Byron** [comment]
I agree, GitPython has some properties which can be costly, and the examples you provide are good ones indeed.
For now I think it's best to make this clear in the documentation.
