### ISSUE TITLE
ability to override with_stdout in remote.pull()

### ISSUE THREAD

**Issue by snihalani** [gitpython-developers/GitPython#432]
git pull -v prints a lot of output and using this method prints a lot of changed lines information that I don't need. Exposing with_stdout as a param would help. Thanks!

**Comment by Byron** [comment]
After reading this issue I am left with a lot of unknowns, and I am not sure I have understood what the actual problem is. Instead of telling you what I think you mean, would you mind going into more detail to help me understand what you are trying to do, and what you would like to have changed.

**Comment by barry-scott** [comment]
I raise 437 about pull printing to stdout.

Did you want to suppress the output?
Did you want to process the output?

**Comment by Byron** [comment]
Fixed with #437

**Comment by snihalani** [comment]
sorry for the late response folks. I wanted to filter some of the output -v provides.
