### ISSUE TITLE
Remote.pull -q flag unsupported with v=True in proc

### ISSUE THREAD

**Issue by itayav** [gitpython-developers/GitPython#439]
I tried to disable pull log messages with "q=True" argument in Remote.pull function (line 662) and the output still printed to stdout.
so, I checked git pull bash command, as you passed in:
self.repo.git.pull(self, refspec, with_stdout=False, as_process=True, v=True, **kwargs)
 '-v' flag before '-q'.
"git pull -q -v" and I got the same results.

but if "-q" was last flag - doesn't have any pull log messages ( as I expected).

by the way, why "-v" flag passed constantly to pull function?

thanks

**Comment by Byron** [comment]
Even though the order of arguments cannot be specified the way you like, I believe the intention is to silence all output. With the implementation of #437 , no output will be visible in the executing terminal anymore.

Please let me know in a comment if the latest version, v2.0.3, did not fix your issue to possibly reopen this one.
