### ISSUE TITLE
remote.pull losing info for error message

### ISSUE THREAD

**Issue by barry-scott** [gitpython-developers/GitPython#448]
When a pull cannot merge the changes it reports a list of files after the
error message. I need that list in my app to show the user.

I suggest that after seeing the error: line in the output that you collect up the following lines
and add them to the GitCommand error. 

The change would be made in remote.py _get_fetch_info_from_stderr.

Also does the raise prevent the sub process from being shutdown completely?

**Comment by Byron** [comment]
I think it's very possible that the process is left hanging, just as finalize process is not called. That should definitely be fixed, in any case.

With such a fix, it should be relatively easy to provide the remaining information provided by the git process in the `GitCommandError` instance. As mentioned, this [would be done here](https://github.com/gitpython-developers/GitPython/blob/902679c47c3d1238833ac9c9fdbc7c0ddbedf509/git/remote.py#L556).

Now as you already have some experience with the codebase and the software to test it, I believe you would be the one to find a nice and suitable API for this kind of issue. 

What's your opinion about it ?

**Comment by barry-scott** [comment]
Looks like the API exists GitCommandError has a stderr arg that looks like it is for this purpose.

I'm creating a PR for this problem.

**Comment by barry-scott** [comment]
PR in your queue for review.

**Comment by Byron** [comment]
@barry-scott Is this one already fixed by the PR mentioned here ? Unfortunately it is not linked, so I am a little lost on this one.

**Comment by barry-scott** [comment]
Yes it is fixed enough to close. Really needs that cmd rewrite to be clean.

Barry
