### ISSUE TITLE
add_progress does this version check really work?

### ISSUE THREAD

**Issue by barry-scott** [gitpython-developers/GitPython#449]
v = git.version_info
        if v[0] > 1 or v[1] > 7 or v[2] > 0 or v[3] > 3:
            kwargs['progress'] = True

I have stared [at this](https://github.com/gitpython-developers/GitPython/blob/902679c47c3d1238833ac9c9fdbc7c0ddbedf509/git/remote.py#L53) and I cannot see what the version check is attempted.
Why not simple something like: git_version_info > (1,7,0,3)?
Is that what this is attempting to do?

**Comment by Byron** [comment]
The logic on this check seems quite broken (i.e. inverted), as it would also kick in if the patch level for some reason is greater than 3. Thus is doesn't make much sense and probably attempts to do what you are suggesting.

Also I did a bit of digging, and found this commit 55eb3de3c31fd5d5ad35a8452060ee3be99a2d99 to be the on introducing it.

It looks like a fix is trivial, would you like to submit a PR for it ?

**Comment by barry-scott** [comment]
Sure. But since I do not trust I understand the test being made can you confirm what
version is being checked for? The commit log does not explain.
