### ISSUE TITLE
Cloning to existing location lost message with 2.0.5

### ISSUE THREAD

**Issue by bpoldrack** [gitpython-developers/GitPython#462]
When cloning into an already existing location, `GitCommandError` used to provide git's message "destination path already exists" in attribute `out`. This apparently is gone with 2.0.5. Now there is the non-telling exit code only. Is this intentional?

**Comment by Byron** [comment]
Can be reproduced like this:
```python
import git
git.Repo.clone_from('https://github.com/Byron/godi', 'godi')
# This will throw without any textual information
git.Repo.clone_from('https://github.com/Byron/godi', 'godi')
```
