### ISSUE TITLE
GitPython Commit corrupts .git/logs/refs/heads/pr-cmd-raise-with-stderr-on-error

### ISSUE THREAD

**Issue by barry-scott** [gitpython-developers/GitPython#464]
I think that the GitPython commit is causing a corruption of this file:
    .git/logs/refs/heads/pr-cmd-raise-with-stderr-on-error

I think it is supposed to be 1 line per commit with the first line of the commit at the end.
But I have all of the log message in the file that GitPython attempts to parse and errors out on.

Attached in the full file.

[pr-cmd-raise-with-stderr-on-error.txt](https://github.com/gitpython-developers/GitPython/files/300506/pr-cmd-raise-with-stderr-on-error.txt)

**Comment by barry-scott** [comment]
I have put in a clean pull request that fixes this bug.

**Comment by Byron** [comment]
Will be fixed by #469.

**Comment by barry-scott** [comment]
Fixed by #469
