### ISSUE TITLE
Repo.blame don't return multi lines.

### ISSUE THREAD

**Issue by niyaton** [gitpython-developers/GitPython#47]
According to API reference,
 -------------------------
 The blame information for the given file at the given revision.
 
 Parm rev:	revision specifier, see git-rev-parse for viable options.
 Returns:	list: [git.Commit, list: [<line>]] A list of tuples associating a Commit object with a list of lines that changed within the given commit. The Commit objects will be given in order of appearance.
 -------------------------
blame method returns list of lines but I think the method always returns only one line.
The method pick up the first line of lines which were written in same commit (other lines are skipped and method don't return its information).

The behavior come from the lien 620 of git/repo/base.py.
The variable 'info' is initialized only when a line is first line of same commit.
But 'info' will be None after processing a line (the lien is not commit information).

We have to initialize 'info' to process subsequent lines.

**Comment by Byron** [comment]
The latest version definitely supports multiple lines per blame object.
Additionally, I have added a [unit-test](https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_repo.py#L308) to verify this truly works.
