### ISSUE TITLE
AttributeError because of latin-1 encoding

### ISSUE THREAD

**Issue by saketgurukar** [gitpython-developers/GitPython#472]
Hi,

I am using GitPython for https://github.com/unclebob/fitnesse.git project.
For commit dfd73518ebb4705f3f65244da0bb9ca7d79c756f, I get attribute error for author attribute of commit.
If I set export PYTHONENCODING='latin-1' then I do not get attribute error. 
Please fix for 'utf-8' encoding.

**Comment by Byron** [comment]
I could not reproduce the issue after cloning the given repository and trying this line to reproduce it:
```
python -c "import git; r = git.Repo('./fitnesse'); c = r.commit('dfd73518ebb4705f3f65244da0bb9ca7d79c756f'); n = c.author.name; print(type(n));
```

It prints `unicode`, which indicates that the decoding worked correctly. Only if one tries to print it to the terminal with incorrect encoding set, one might see an error (which happened to me, as it tried to re-encode as ascii).

Please be sure you are using the latest version of GitPython.

In case this doesn't fix the issue for you, please provide steps for how to reproduce it in the latest version of GitPython in the comments.
