### ISSUE TITLE
Infinite loop: No any response when call origin.push(). 

### ISSUE THREAD

**Issue by fuckgitpython** [gitpython-developers/GitPython#481]
The push is successful.
But origin.push() cannot get any response. It's stuck.

**Comment by fuckgitpython** [comment]
OS X Got infinite loop in cmd.py when push.

``` python
        while True:
            # no timeout

            try:
                poll_result = poll.poll()
            except select.error as e:
                if e.args[0] == errno.EINTR:
                    continue
                raise
            # end handle poll exception

            for fd, result in poll_result:
                if result & CLOSED:
                    closed_streams.add(fd)
                else:
                    _dispatch_lines(fd, *fdmap[fd])
                # end handle closed stream
            # end for each poll-result tuple

            if len(closed_streams) == len(fdmap):
                break
            # end its all done
        # end endless loop
```

**Comment by fuckgitpython** [comment]
can this fix ?
``` diff
-               if result & CLOSED:
+               if fd & CLOSED:
```

**Comment by Byron** [comment]
@fuckgitpython I must admit that you are the first one to go through with it and even create a 'specifically themed username' to indicate what you think. For some reason, the title was changed shortly after, and I thought it was such a good match ;).

I'd really like to help, but it seems the issue will be hard to reproduce without any additional instructions. Usually it's a good thing to provide the version of GitPython you are using as well - maybe it doesn't matter in this case as the code shown here is still present unchanged.

Also I am closing the issue, hoping you will resubmit it with a username that doesn't contain profanity - there is no need to do that here, as we wish to treat each other respectfully.
Please also note that I have reported the user.
