### ISSUE TITLE
custom_environment with GIT_SSH_COMMAND

### ISSUE THREAD

**Issue by Winnak** [gitpython-developers/GitPython#484]
I feel dirty for submitting an issue that might come from my own incompetence, but I have exhausted my options now.

My issue is the following: 
```python
my_repo = git.Repo(r"..\coolrepo")
with my_repo.git.custom_environment(GIT_SSH_COMMAND="ssh -i id_rsa"):
    my_repo.remotes.origin.fetch()
```
returns
```
Traceback (most recent call last):
  File "...\gittest.py",
    my_repo.remotes.origin.fetch()
  File "...\Python35\lib\site-packages\git\remote.py", line 743, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "...\Python35\lib\site-packages\git\remote.py", line 640, in _get_fetch_info_from_stderr
    finalize_process(proc, stderr=stderr_text)
  File "...\Python35\lib\site-packages\git\util.py", line 155, in finalize_process
    proc.wait(**kwargs)
  File "...\Python35\lib\site-packages\git\cmd.py", line 332, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: 'git fetch -v origin' returned with exit code 128
stderr: 'fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
```
From this one might assert that `id_rsa` is not found or is not matching the public key on the server.
However the following line worked fine:
``` python
git.Repo.clone_from("git@bitbucket.org:user/coolrepo.git", r"..\coolrepo", env=dict(GIT_SSH_COMMAND="ssh -i id_rsa"))
```

I am unsure if I am doing something wrong or if it's an bug or what it is.

**Comment by Winnak** [comment]
Figured this out, it was just me being an idiot. The issue has nothing to do with GitPython.

The issue was that the GIT_SSH_COMMAND cannot have a windows path, even though the Repo constructor doesn't seem to mind. Why it worked fine with the clone_from, I don't know.
I think there is a case for an improvement to GitPython that converts the GIT_SSH_COMMAND path into the correct format, but this is not an issue. 

Please close this issue.

**Comment by Byron** [comment]
Thanks for letting us know ! If you believe GItPython truly could, and maybe should, help in making this easier, you could consider fleshing out such functionality in a separate issue (knowing that new features are not implemented anymore by the maintainers).
