### ISSUE TITLE
GitPython2.0.6

### ISSUE THREAD

**Issue by hgz6536** [gitpython-developers/GitPython#488]
how can I get git log with a list or a dictinonary

**Comment by hgz6536** [comment]
I got it.
`def git_log(repopath):
    repo = Repo(repopath)
    ver = repo.iter_commits('master', max_count=50)
    commlist = []
    for i in ver:
        commdic = {}
        message = repo.commit(i).message.rstrip('\n')
        date = repo.commit(i).committed_date
        commdate = datetime.utcfromtimestamp(
            date).strftime("%Y-%m-%d %H:%M:%S")
        name = repo.commit(i).author
        commdic['message'] = message
        commdic['commdate'] = commdate
        commdic['name'] = str(name)
        commdic['id'] = str(i)
        commlist.append(commdic)
    return commlist`

**Comment by hgz6536** [comment]
def git_log(repopath):
    repo = Repo(repopath)
    ver = repo.iter_commits('master', max_count=50)
    commlist = []
    for i in ver:
        commdic = {}
        message = repo.commit(i).message.rstrip('\n')
        date = repo.commit(i).committed_date
        commdate = datetime.utcfromtimestamp(
            date).strftime("%Y-%m-%d %H:%M:%S")
        name = repo.commit(i).author
        commdic['message'] = message
        commdic['commdate'] = commdate
        commdic['name'] = str(name)
        commdic['id'] = str(i)
        commlist.append(commdic)
    return commlist

**Comment by hgz6536** [comment]
> def git_log(repopath):
    repo = Repo(repopath)
    ver = repo.iter_commits('master', max_count=50)
    commlist = []
    for i in ver:
        commdic = {}
        message = repo.commit(i).message.rstrip('\n')
        date = repo.commit(i).committed_date
        commdate = datetime.utcfromtimestamp(
            date).strftime("%Y-%m-%d %H:%M:%S")
        name = repo.commit(i).author
        commdic['message'] = message
        commdic['commdate'] = commdate
        commdic['name'] = str(name)
        commdic['id'] = str(i)
        commlist.append(commdic)
    return commlist

**Comment by Byron** [comment]
For questions on how to use GitPython, please consult [the documentation](http://gitpython.readthedocs.io/en/stable/) or post on stackoverflow using the `gitpython` tag. Please note that on the latter platform, there will be some minimal requirements to meet to help those willing to answer understand the OPs intend.
