### ISSUE TITLE
GIT_PYTHON_TRACE environment variable not work

### ISSUE THREAD

**Issue by alexazhou** [gitpython-developers/GitPython#489]
Hi:

after ```export GIT_PYTHON_TRACE=full``` , I run repo.remotes['origin'].pull( ), and I havn't see any output from stdout,  is that a bug,or I used it in a wrong way?

 how can i get the output like run a git command in a bash like 

```
Alexa$ git pull
remote: Counting objects: 35, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 35 (delta 20), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (35/35), done.
From https://github.com/WRTX/LicaifanWeb
   92caee9..5491012  master     -> GitHub/master
Updating 5695833..c48b822

```

Thanks

**Comment by Byron** [comment]
I fell for the same issue once. As [you can see](https://github.com/gitpython-developers/GitPython/blob/2ff3a3e72b1ff79e75777ccdddc86f8540ce833d/git/cmd.py#L582), the logging module is used to perform all kinds of debug logging. By default, nothing will happen though if logging is not initialised.
It should work if you call the following before running GitPython:
```
import logging
logging.basicConfig()
logging.root.setLogLevel(logging.INFO)
```
If that doesn't work for you, please let me know in the comments and I will re-open this issue.

**Comment by alexazhou** [comment]
Thanks , It works.

And as I try the method is ``` logging.root.setLevel(logging.INFO)```

**Comment by nvie** [comment]
I was bitten by this once, and wanted to fix it back then, but I forgot. So I've done it now anyway, see a5e6676db845e10bdca47c3fcf8dca9dea75ec42.

**Comment by alexazhou** [comment]
Oh man, you are so nice~
