### ISSUE TITLE
How can I "git push --all"?

### ISSUE THREAD

**Issue by dchevell** [gitpython-developers/GitPython#491]
I need to push an entire repo to a new location for a project I'm working on. I tried `repo.push(all=True)`, similar to `repo.push(tags=True)` but it doesn't seem to work - only the master branch is pushed. How can I push the entire repo instead of just one branch, a la `git push --all` ?

**Comment by dchevell** [comment]
User error!

**Comment by visimo-jarod** [comment]
For any wayward travelers who found their way here and couldn't figure out how to do this, the "user error" is using the wrong method to push: you push like `<repo_variable>.remotes.<remote_name>.push(...)` and in that command you can use `all=True` and `force=True` and whatever else.
