### ISSUE TITLE
`repo.config_writer()`: stderr: 'git: 'config-writer' is not a git command

### ISSUE THREAD

**Issue by lzkelley** [gitpython-developers/GitPython#492]
I'm trying to modify a configuration file, but the `config_writer()` can't be created.  I keep getting the error:

```
  File "/Users/lzkelley/Research/catalogs/astrocats/astrocats/catalog/catalog.py", line 503, in git_pull_all_repos
    cw = grepo.config_writer()
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/git/cmd.py", line 463, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/git/cmd.py", line 929, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/Users/lzkelley/anaconda3/lib/python3.5/site-packages/git/cmd.py", line 713, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git config-writer' returned with exit code 1
stderr: 'git: 'config-writer' is not a git command. See 'git --help'.'
```

`git.__version___`: '2.0.6'  
python 3.5.1

**Comment by Byron** [comment]
This makes no sense to me, as the `config_writer()` call seems to be interpreted as git command. However, this cannot happen as the [respective method](https://github.com/gitpython-developers/GitPython/blob/a5e6676db845e10bdca47c3fcf8dca9dea75ec42/git/repo/base.py#L410) is defined on the `Repo` type.

I think what's actually happening here is that `grepo` is not a repository, but something obtained via `repo.git`.

Can you please verify you are using the correct instance ?

**Comment by lzkelley** [comment]
Ugh, yeah - you're exactly right.  My `repo` variable was being overwritten to one using `git.cmd.Git`.  Sorry!
