### ISSUE TITLE
_io.BufferedWriter in cmd.py

### ISSUE THREAD

**Issue by kylepjohnson** [gitpython-developers/GitPython#494]
I'm getting the following error my unit tests (Python 3.5.2; GitPython 2.0.7):

``` python
/Users/kyle/cltk/venv/lib/python3.5/site-packages/git/cmd.py:622: ResourceWarning: unclosed file <_io.BufferedWriter name='/dev/null'>
  **subprocess_kwargs
```

An unclosed handle isn't a big deal, however it clutters up my output. This error comes out of [this try/except in cmd.py](https://github.com/gitpython-developers/GitPython/blob/dc2ec79a88a787f586df8c40ed0fd6657dce31dd/git/cmd.py#L611).

I know there are a few ways to solve this (`with`, a new `except`, changing `stderr` and `stdout` paramters) and don't know what you'd prefer. If it helps, here's how IPython fixed this a few years back: <https://github.com/ipython/ipython/pull/5222/files>.

If you think this would be a fairly easy fix, let me know and I volunteer myself.

Thanks for this excellent package! My project uses it extensively.

**Comment by Byron** [comment]
@kylepjohnson Thanks for bringing to my attention what I believe is a pretty major issue, which I believe originates [here](https://github.com/gitpython-developers/GitPython/blob/788bd7e55085cdb57bce1cabf1d68c172c53f935/git/cmd.py#L618-L619). You might want to try to remove the redirection entirely, and if the issue goes away, maybe it's enough to just close the handle right after it was opened, assuming the subprocess will duplicate file-handles anyway.
If you could give it a shot and maybe even submit a PR, I'd be super happy.
What do you think ?

**Comment by kylepjohnson** [comment]
Hi @Byron I've tried to reproduce this and have not been able. (Background: Bug was introduced either from someone's dubious merge.)

So without being able to make this appear again, I am hesitant to suggest any fixes.

I will be sure to capture the bug more thoroughly, should it arise again! Thanks for your time and efforts.
