### ISSUE TITLE
CMD windows created for Windows GUI python programs

### ISSUE THREAD

**Issue by barry-scott** [gitpython-developers/GitPython#495]
Prevent CMD windows being shown when starting git in a subprocess.

This fixes a UI problem with using GitPython from a GUI python probgram.
Each repo that is opened creates a git cat-file processs and that provess will create
a console window with out this change.

[patch.txt](https://github.com/gitpython-developers/GitPython/files/390557/patch.txt)

**Comment by Byron** [comment]
Please note that the patch referred to by the OP is already part of #469. The issue can be closed when merged.

**Comment by barry-scott** [comment]
Oh I get it because I push master you see in the PR. I did not expect that.

**Comment by barry-scott** [comment]
Fixed by PR #469.
