### ISSUE TITLE
gpgsig not populated correctly

### ISSUE THREAD

**Issue by jamesmkwan** [gitpython-developers/GitPython#500]
Unlike the other attributes in a Commit object, the attribute [`gpgsig` is always set by the `Commit` constructor](https://github.com/gitpython-developers/GitPython/blob/df5095c16894e6f4da814302349e8e32f84c8c13/git/objects/commit.py#L133
). If you look at all the previous lines, they are guarded with a `if X is not None:`.

Since the Commit object can then be created with `gpgsig = None`, this causes the [`__getattr__ in LazyMixin`](https://github.com/gitpython-developers/gitdb/blob/13ad9b1199331a35e23f65c735acf482be09eae3/gitdb/util.py#L232) to not be called, which is responsible for calling [`_set_cache_`](https://github.com/gitpython-developers/GitPython/blob/df5095c16894e6f4da814302349e8e32f84c8c13/git/objects/commit.py#L139) which ultimately calls [`_deserialize` to populate `gpgsig`](https://github.com/gitpython-developers/GitPython/blob/df5095c16894e6f4da814302349e8e32f84c8c13/git/objects/commit.py#L496).

This unfortunately causes the bug that if `gpgsig` is the _first_ attribute read, it returns `None` even when the commit is signed. For example, if before reading `gpgsig`, we read another attribute like `message`, reading `gpgsig` will work. This made the bug hard to discover and debug. :disappointed:

I believe that this bug can be fixed just by adding a `if gpgsig is not None:` conditional in the line above.

**Comment by Byron** [comment]
Thanks for taking the time to create this super-informative issue.
Provided that travis likes it too, it will be fixed in the next release.
