### ISSUE TITLE
retrieving commits from branch names with UTF characters

### ISSUE THREAD

**Issue by valeriocos** [gitpython-developers/GitPython#515]
I'm using GitPython to retrieve all commits per branch from the rails repository (https://github.com/rails/rails). I'm encountering some problems when trying to get commits from the following branch: https://github.com/rails/rails/tree/%E0%B2%A0_%E0%B2%A0

Below you can find the code to replicate this issue:
```python
from git import *

GIT_REPO_PATH = "PATH_TO_RAILS_REPO"


def get_commits(repo, ref_name):
    commits = []
    for commit in repo.iter_commits(rev=ref_name):
        commits.append(commit)
    return commits


def main():
    repo = Repo(GIT_REPO_PATH, odbt=GitCmdObjectDB)
    for ref in repo.references:
        print ref.name
        print str(len(get_commits(repo, ref.name)))
        print "---"

if __name__ == "__main__":
    main()
```

**Comment by Byron** [comment]
Thanks for providing the script to reproduce it ! Unfortunately (or fortunately), on the latest version of GitPython, this is no issue anymore. Here is the respective part of the scripts output:
```
[...]
---
origin/unlock-minitest
59577
---
origin/v5.0.0.beta2
56231
---
origin/ಠ_ಠ
58198
---
list
23682
---
[...]
```
Please note that I am testing this on MacOS with `LC_CTYPE=UTF-8`, which can have a major impact on how python tries to encode its output.

Please feel free to comment on the issue, which I am closing now just to keep it easy for me. If you find something I can reproduce, I will happily reopen it though.

<details>
And this is my version of the reproduction script. It's just setting the path-to-repo accordingly.
```python

from git import *

GIT_REPO_PATH = "rails"


def get_commits(repo, ref_name):
    commits = []
    for commit in repo.iter_commits(rev=ref_name):
        commits.append(commit)
    return commits


def main():
    repo = Repo(GIT_REPO_PATH, odbt=GitCmdObjectDB)
    for ref in repo.references:
        print ref.name
        print str(len(get_commits(repo, ref.name)))
        print "---"

if __name__ == "__main__":
    main()
```
