### ISSUE TITLE
[Windows] Create_submodule fails due to use of hidden files

### ISSUE THREAD

**Issue by matthewwardrop** [gitpython-developers/GitPython#516]
On Windows, the .git files are given the hidden attribute. If a file is marked as hidden, it cannot be written to using the standard Python open(..., 'w') command. This is because the underlying win32 api errors unless the attributes of the open command match the attributes of the file, and this is not exposed in the Python API

For example, consider the following snippet:

```
import git
r = git.Repo('test')
r.create_submodule(name='testing', path='testing', url='https://github.com/matthewwardrop/python-parampy')
```

On Unix, this works fine. In Windows, however, it will crash with the following stack trace:

```
Traceback (most recent call last):
  ...
  File "c:\program files\python35\lib\site-packages\git\repo\base.py", line 306, in create_submodule
    return Submodule.add(self, *args, **kwargs)
  File "c:\program files\python35\lib\site-packages\git\objects\submodule\base.py", line 389, in add
    mrepo = cls._clone_repo(repo, url, path, name, **kwargs)
  File "c:\program files\python35\lib\site-packages\git\objects\submodule\base.py", line 253, in _clone_repo
    cls._write_git_file_and_module_config(module_checkout_path, module_abspath)
  File "c:\program files\python35\lib\site-packages\git\objects\submodule\base.py", line 292, in _write_git_file_and_mod
ule_config
    fp = open(git_file, 'wb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\matthewwardrop\\test\\testing\\.git'
```

There's probably a workaround using the raw git commands, but it would be nice to have this cleaned up.

**Comment by Byron** [comment]
Thanks for letting me know. If you can come up with a solution that works for you, I would be very happy about a PR. Windows is not a platform I can test on, and am therefore dependent on contributions in that realm.

**Comment by ankostis** [comment]
@matthewwardrop this must have been fixed by #519 (b8b025f719b2) where the file gets deleted before overwritting it.
I had the same problem, but I couldn't understand why this was happening; thanks for the tip!

Anyway, please check if it is ok, before closing the issue.

**Comment by Byron** [comment]
I am closing this issue as it had no interaction for more than 3 months. Please feel free to comment in case you need it to be reopened.

**Comment by matthewwardrop** [comment]
@Byron @ankostis Thanks for fixing this. Sorry for the huge delay. I don't often use Windows, so I guess I never got around to checking this. Given that things seem to work for you in appveyor, and people have not been reporting bugs against my project (the knowledge repo), it looks like these issues have been fixed. I really appreciate it!
