### ISSUE TITLE
enable testing of performance tests

### ISSUE THREAD

**Issue by yarikoptic** [gitpython-developers/GitPython#524]
according to https://codecov.io/gh/gitpython-developers/GitPython/tree/94ca83c6b6f49bb1244569030ce7989d4e01495c/git/test/performance  those aren't executed during travis run ATM (I guess because `performance` is not `tests_performance` or smth like that).  But better be done after #522 is merged to see the effect

**Comment by ankostis** [comment]
@byron what's the reasons for having these TCs disabled on Travis?

**Comment by Byron** [comment]
@yarikoptic @ankostis They are disabled to get travis feedback faster. Right now, the benchmark numbers produced by the performance tests are not stored or analysed in any way, thus a performance regression will not be discovered by them. If the two of you believe it would still be good to have thanks to even increased coverage, please feel free to put them in.

**Comment by yarikoptic** [comment]
On Sun, 09 Oct 2016, Sebastian Thiel wrote:

>    @yarikoptic @ankostis They are disabled to get travis feedback faster.
>    Right now, the benchmark numbers produced by the performance tests are not
>    stored or analysed in any way, thus a performance regression will not be
>    discovered by them. If the two of you believe it would still be good to
>    have thanks to even increased coverage, please feel free to put them in.

FWIW on my laptop it takes only 15sec

nosetests git/test/performance  15.04s user 1.12s system 102% cpu 15.753 total

and IIRC it does improve coverage a bit (besides its own tests code), so I
thought it would be worthwhile, to also make sure that that performance
measuring code doesn't get stale.
