### ISSUE TITLE
gitpython-2.0.9.dev0 has run-time dependency on nose

### ISSUE THREAD

**Issue by desbonnm** [gitpython-developers/GitPython#526]
Installing recently-released GitPython==2.0.9.dev0 results in  'No module named nose.tools' error on 'import git':

    $ rm -rf ~/tmp/test_gitpython; virtualenv ~/tmp/test_gitpython; ~/tmp/test_gitpython/bin/pip install  gitpython==2.0.9.dev0; ~/tmp/test_gitpython/bin/python -c 'import git'
    New python executable in /home/desbonne/tmp/test_gitpython/bin/python
    Please make sure you remove any previous custom paths from your /home/desbonne/.pydistutils.cfg file.
    Installing setuptools, pip, wheel...done.
    Collecting gitpython==2.0.9.dev0
      Using cached GitPython-2.0.9.dev0-py2.py3-none-any.whl
    Collecting gitdb>=0.6.4 (from gitpython==2.0.9.dev0)
    Collecting smmap>=0.8.5 (from gitdb>=0.6.4->gitpython==2.0.9.dev0)
    Installing collected packages: smmap, gitdb, gitpython
    Successfully installed gitdb-0.6.4 gitpython-2.0.9.dev0 smmap-0.9.0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/desbonne/tmp/test_gitpython/local/lib/python2.7/site-packages/git/__init__.py", line 36, in <module>
        from git.objects import *               # @NoMove @IgnorePep8
      File "/home/desbonne/tmp/test_gitpython/local/lib/python2.7/site-packages/git/objects/__init__.py", line 11, in <module>
        from .commit import *
      File "/home/desbonne/tmp/test_gitpython/local/lib/python2.7/site-packages/git/objects/commit.py", line 17, in <module>
        from .tree import Tree
      File "/home/desbonne/tmp/test_gitpython/local/lib/python2.7/site-packages/git/objects/tree.py", line 13, in <module>
        from .submodule.base import Submodule
      File "/home/desbonne/tmp/test_gitpython/local/lib/python2.7/site-packages/git/objects/submodule/base.py", line 42, in <module>
        from git.test.lib.helper import HIDE_WINDOWS_KNOWN_ERRORS
      File "/home/desbonne/tmp/test_gitpython/local/lib/python2.7/site-packages/git/test/lib/__init__.py", line 9, in <module>
        from .asserts import *
      File "/home/desbonne/tmp/test_gitpython/local/lib/python2.7/site-packages/git/test/lib/asserts.py", line 10, in <module>
        from nose.tools import (
    ImportError: No module named nose.tools

I realise that 2.0.9.dev0 is not installed by pip by default, due to being a dev version, but I'm getting gitpython as a transitive dependency via git-upstream, which has a pre-release constraint on gitpython:

    $ rm -rf ~/tmp/test_gitpython; virtualenv ~/tmp/test_gitpython >/dev/null; ~/tmp/test_gitpython/bin/pip install git-upstream | grep 'Collecting GitPython'
    Collecting GitPython!=0.3.2,>=0.3.2.RC1 (from git-upstream)

**Comment by ankostis** [comment]
Yeap, thanks for this one. It is due code disabling failing Windows TCs, enacted on #525. 
Will fix ASAP.

**Comment by ankostis** [comment]
@Byron I need to revert master in order to merge.  Can I?

**Comment by Byron** [comment]
@ankostis Please feel free to do whatever you think has to be done. You have my full trust. Sorry for the hassle, when I merged it was green on AppVeyor, at least according to github :/.
(Still on mobile, everything else in a bit)

**Comment by claytononeill** [comment]
Can we get a new release go go along with this fix?

**Comment by ankostis** [comment]
For that we are expecting the dependency projects *snmap* and *gitdb*, to release also in PyPi: https://github.com/gitpython-developers/smmap/issues/28

**Comment by claytononeill** [comment]
I'm afraid I don't follow.  Can you explain how that's related and when a release might happen?

**Comment by Byron** [comment]
@claytononeill I have just pushed dev1, which should contain the fix required to allow installations to work. I have also un-hidden the last non-dev version, which should hopefully allow installers to gravitate towards the stable version.

**Comment by Byron** [comment]
I have also hidden the previous dev release entirely, which ideally fixes the issue for good.
