### ISSUE TITLE
Minor release

### ISSUE THREAD

**Issue by bpoldrack** [gitpython-developers/GitPython#538]
Since #536 was merged, I wonder whether it would be possible to have a minor release, in order to be able to add this as a requirement for our project (https://github.com/datalad/datalad).

**Comment by Byron** [comment]
I also believe the patch-level release should be skipped in favour of an actual minor one. The latter will happen in the course of the day.

**Comment by Byron** [comment]
v2.1.0 was released on pypi.

**Comment by bpoldrack** [comment]
Thanks a lot!
