### ISSUE TITLE
2.0.9 fails on Python 2.6

### ISSUE THREAD

**Issue by andy-maier** [gitpython-developers/GitPython#540]
I was thankful to see your reaction to my issue #453, but unfortunately GitPython 2.0.9 has some issues on Python 2.6. GitPython 2.0.8 worked like a charm for us.

The issues are:
- uses of dictionary comprehension in `git/cmd.py` around line 800 (dict comprehensions were introduced in py27).
- use of SkipTest and skipIf from `unittest.case` in `git/util.py` and in several test cases (these were added to `unittest` in py27). Also, the Python `unittest` docs suggest they be imported from `unittest` and not from `unittest.case`, but that is minor.

I have fixed those locally and will create a PR for your review.

**Comment by hugovk** [comment]
PR #541 was merged on 8 Dec 2016. Can this issue be closed?

Whilst on the topic, is Python 2.6 still something you need to support, or might it be time to consider dropping it more fully?

Here's the pip installs for GitPython from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  82.08% |        466,982 |
| 3.6            |  10.07% |         57,285 |
| 3.5            |   4.88% |         27,754 |
| 3.4            |   2.58% |         14,663 |
| 2.6            |   0.23% |          1,333 |
| 3.7            |   0.10% |            571 |
| 3.3            |   0.06% |            321 |
| 3.8            |   0.00% |              5 |

Source: `pypinfo --start-date -39 --end-date -12 --percent --pip --markdown GitPython pyversion`

**Comment by Byron** [comment]
@hugovk  Thanks a lot for publishing some hard facts about its usage here! I wasn't even aware of download information once again being available.

I think you are providing a strong argument to indeed drop python 2.6 support, the next time we break it. Alternatively, if someone feels strongly about getting rid of it to improve the code climate for example, PRs are always welcome.

As the PR mentioned in this issue was merged, I think it's fair to close this ticket, too.

**Comment by hugovk** [comment]
Yeah, there's quite a lot of interesting stuff you can now get out of PyPI and pypinfo:  
https://github.com/ofek/pypinfo/blob/master/README.rst#usage

Here's some examples:
```console
$ pypinfo GitPython country
Served from cache: False
Data processed: 8.22 GiB
Data billed: 8.22 GiB
Estimated cost: $0.05

| country | download_count |
| ------- | -------------- |
| US      |        548,405 |
| IE      |         13,000 |
| DE      |         12,170 |
| FR      |          8,712 |
| GB      |          7,789 |
| FI      |          7,775 |
| CA      |          4,966 |
| EU      |          3,961 |
| NL      |          3,569 |
| CN      |          3,337 |

$ pypinfo GitPython system distro
Served from cache: False
Data processed: 13.59 GiB
Data billed: 13.59 GiB
Estimated cost: $0.07

| system_name | distro_name                     | download_count |
| ----------- | ------------------------------- | -------------- |
| Linux       | Ubuntu                          |        405,741 |
| Linux       | CentOS Linux                    |         87,623 |
| Linux       | Debian GNU/Linux                |         48,369 |
| Linux       | None                            |         25,180 |
| None        | None                            |         23,718 |
| Linux       | Red Hat Enterprise Linux Server |          7,750 |
| Linux       | Amazon Linux AMI                |          7,315 |
| Windows     | None                            |          6,645 |
| Linux       | Alpine Linux                    |          6,477 |
| Darwin      | macOS                           |          5,857 |
```

**Comment by Byron** [comment]
Super-interesting indeed! I wonder how these numbers are actually computed (_just a rhetorical question really_), just because they seem very, very high! Especially since it's just the monthly downloads. Could GitPython really be that popular :D?
