### ISSUE TITLE
git clone hangs sometimes

### ISSUE THREAD

**Issue by zikphil** [gitpython-developers/GitPython#547]
Hello,

Random issue i am having with the latest version of this repo along side latest Python 3. So i am doing a repository clone from 2-3 repo sequentially. Most of time it works fine but sometimes it hangs for no reason, and then when i CTRL+C to exit out of it, i get the following:

```
    containers_repo = git.Repo.clone_from(containers_repo_url, os.path.join('/tmp/project/' + project_config['name'] + '/' + timestamp, 'containers'), branch=branch)
  File "/usr/local/lib/python3.5/site-packages/git/repo/base.py", line 925, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)

  File "/usr/local/lib/python3.5/site-packages/git/repo/base.py", line 878, in _clone
    (stdout, stderr) = proc.communicate()  # FIXME: Will block if outputs are big!

  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)

  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1715, in _communicate
    ready = selector.select(timeout)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

I saw the #FIXME i am wondering if this has been resolved or if there are any workarounds out there.

Thanks,

Phil

**Comment by ankostis** [comment]
@philippelabat thanks for reporting it.

Normally `communicate()` should not hang, it just may consume much memory for big files; the comment you see was mine, and it [does not hold](https://github.com/gitpython-developers/GitPython/pull/529#pullrequestreview-4386600), I have to remove it.

- Can you specify the exact commit you tested?
- Does this happens with earlier versions?

**Comment by Byron** [comment]
I am closing this issue as it had no interaction for more than 3 months. Please feel free to comment in case you need it to be reopened.

**Comment by Abbyyan** [comment]
I've  meet the same problem now and it really bother me for a long time. Here are the details. https://github.com/gitpython-developers/GitPython/issues/969
