### ISSUE TITLE
Pass author to repo.git.commit

### ISSUE THREAD

**Issue by JarrenceMelie** [gitpython-developers/GitPython#548]
Hi, maybe someone can help with this issue...
I have the following code snippet:
```python
repo = Repo(dir_repo)
repo.git.add(filename)
repo.git.commit(a=True, m="commit message")
```

Is it possible somehow to pass author name through repo.git.commit?

**Comment by ankostis** [comment]
You have to set these infos in the repo-wide configurations.
Can you try this:

```python
with repo.config_writer() as cw:
    cw.set_value('user' 'name', 'foo')
    cw.set_value('user' 'email', 'foo@bar.com')
```

**Comment by JarrenceMelie** [comment]
Thank you, ankostis! 
You have missed commas after 'user', but it works.
