### ISSUE TITLE
Documentation on how to deal with tracking branch is difficult to understand

### ISSUE THREAD

**Issue by brunogirin** [gitpython-developers/GitPython#549]
The documentation is very difficult to understand to such a point that I cannot work out how to create a tracking branch. In practice I'm trying to do the equivalent of:

```
git push -u origin mybranch
```

If I look at the documentation on heads, I get:

```
set_tracking_branch(remote_reference)
```

but it doesn't clearly explain what a `remote_reference` is and it's definitely not the remote branch's name. I suspect it's a a git remote reference object but the documentation for `Remote` doesn't explain how to create one of those. It's not a `refspec` either in the sense used by `Remote.fetch` as far as I can tell.

So instead, I tried to use the `git` command direct by doing:

```
repo.git.execute(["push", "-u", remote.name, branch])
```

but the description of what needs to go in the `command` attribute is unclear and has no example. So I get the following error when doing this:

```
git.exc.GitCommandNotFound: Cmd('push') not found due to: FileNotFoundError('[Errno 2] No such file or directory: 'push'')
```

I am probably not using the API as intended but the documentation is not helpful in helping me identify what I'm doing wrong. Either the API reference needs examples of usage of most important functions or the tutorial needs more complete examples that follow real life situations.

**Comment by Byron** [comment]
Have you tried [the section on handling remotes](https://gitpython.readthedocs.io/en/stable/tutorial.html#handling-remotes) in the tutorial? I believe it contains a decent example on how to use the API.

As for the usage of the git command, it is meant to be used [as described in another part](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly) of the tutorial.

Please feel free to add more questions here in case the provided links to documentation don't help you.

**Comment by svenevs** [comment]
Hi @Byron,

I disagree, the documentation is not sufficient.  What the docs you link to demonstrate is how to push to a `remote` that already exists.  Without the `fetch()`, the `empty_repo.heads.master.set_tracking_branch(origin.refs.master)` will not work, because `origin.refs` is an empty list.

In my use case, I am creating things from scratch using this api, and the only way I can get it all to work out is at the end doing

`git.execute(["git", "push", "-u", "origin", "master"])`

AKA if the `remote` has no tracking information (as is the case with an empty repo on the `remote`), there is no way to set this.  I feel like the `push()` command could be a lot more flexible in this regard.

I also may have completely missed something...please inform ;)

**Comment by Byron** [comment]
It looks like despite the insufficient documentation, you figured something out that works for you. Equipped with that knowledge, you would be able to improve the docs to be better for those after you, and I would greatly appreciate a PR for that.

**Comment by svenevs** [comment]
I guess that was a poorly phrased question on too little sleep...sorry.  I feel like this functionality exists, I'm just not using the `origin` or initializing correctly or something.

The following is what I did, happy to adapt it to the test file that the docs are coming from if you think it is correct.  The framework essentially calls three methods in order:

1. initialize everything (`git init`, add README and gitignore)
2. copy a bunch of files and `git add` them with the `Repo` object
3. commit and push

Cutting out a large amount of logging and error checking, it looks something like this

```
import os
import shutil
from git import Repo

# leave_early() should be viewed as equivalent to `assert`
# or throwing an exception. it's returning a tuple of
# strings and other logging related items
def leave_early(msg):
    raise Exception(msg)

#
# input to all phase methods
###############################
repo_path      = "path/to/top/level"
git_directory  = os.path.abspath(repo_path)
secret_url     = "https://<oauth>@<github_url>/<github_org>/<repo_name>.git"
commit_message = "Some message about what is being dispatched."

#
# init phase
###############################
repo = Repo.init(git_directory)
if repo.__class__ is not Repo:
    leave_early("Unable to create repository [{}]".format(git_directory))

# Equivalent of `git remote add origin <secret url>`
origin = repo.create_remote('origin', secret_url)
if not origin.exists():
    leave_early("Unable to add the remote `origin {}`.".format(secret_url))

# my framework does text processing on the input readme,
# docs example maybe better to just assume valid paths
readme_source = "/path/to/input/README.md"
readme_dest   = "{}/README.md".format(git_directory)
try:
    shutil.copy(readme_source, readme_dest)
except Exception as e:
    leave_early("Unable to copy from [{}] to [{}]".format(readme_source, readme_dest))
# Add the README.md to the index of the git repository
readme_path = os.path.join(repo.working_tree_dir, "README.md")
repo.index.add([readme_path])

# (rinse lather and repeat for .gitignore)
# [[[ ... not included ... ]]]

# (then an arbitrary amount of files are copied into the directory)
# repo.index.add([list of paths to these])

#
# finalize phase
###############################
origin = repo.remotes.origin
repo.index.commit(commit_message)
git = repo.git
git.execute(["git", "push", "-u", "origin", "master"])
```

The only thing I can think of is that something goes wrong when `init` happens `origin = repo.create_remote('origin', secret_url)`, whereas in finalize I just grab `repo.remotes.origin`, but that seems unlikely.

Let me know what your thoughts are.

**Comment by Byron** [comment]
I like the formatting and readability of the code! It should be possible to integrate it into the existing `test_docs.py` file, probably easiest just using a new test-case.
Something I wouldn't encourage though is `git.execute` - after all, it should be easier for most to just run `repo.git.push('-u', 'origin', 'master')`. I also think that `Repo.init` will throw if something goes wrong.

**Comment by svenevs** [comment]
Ok cool!  I realize now, though, that it's basically impossible to test this automatically more than once.  The use case is for a bare `remote`, so even if some magic through the API was performed for the test suite to -- on test launch -- delete the remote and recreate it, things would break.

Additionally, no developers would be able to run tests locally unless they were given write permissions to the same repo chosen...

So perhaps the best option would be to include a separate section in the docs, with the above code just in the actual `rst` doc?

I was re-reading through the API and some of the methods talk about thread safety, is `repo.git.push` thread-safe?  My testing reveals that `git.execute` is **not**, I will test a more polished version of the above before submitting PR, but do you know if [`Git.get_object_data`](http://gitpython.readthedocs.io/en/stable/reference.html?highlight=thread#git.cmd.Git.get_object_data) or [`Git.stream_object_data`](http://gitpython.readthedocs.io/en/stable/reference.html?highlight=thread#git.cmd.Git.stream_object_data) are at play here?  I don't quite understand what the `stream_object_data` docstring

> This method is not threadsafe, you need one independent Command instance per thread to be safe !

refers to -- is `repo.push` an "independent Command instance"?

**Comment by Byron** [comment]
I think what you would need is [another one of these test-cases](https://github.com/gitpython-developers/GitPython/blob/72dddc7981c90a1e844898cf9d1703f5a7a55822/git/test/test_docs.py#L24-L26), which provide a new and writable directory which you don't have to worry about.

The conversation about thread-safety seems quite unrelated - as a general advice: nothing is thread-safe, and if you have to use GitPython across threads, each one must have its own `Repo` instance. Each `Repo` comes with its own `Git` instance.

**Comment by nhed** [comment]
In my uneducated opinion being able to set an upstream *just to a branch that exist in the remote* is a shortcoming.  My workflow has been for many years to set (via alias) the config vars for that branch [based on this]( http://stackoverflow.com/a/18647857/652904).

So for now I supplement calls to `create_head()` with 
```
       with gitpy_repo.config_writer(config_level="repository") as writer:
           writer.set_value(f'branch "{branch}"', "remote", "origin")
           writer.set_value(f'branch "{branch}"', "merge", f"refs/heads/{branch}")
           writer.set_value(f'branch "{branch}"', "rebase", "true")
```

just in case it helps anyone coming to this thread from search
