### ISSUE TITLE
Tracking Branch for branch containing a hash sign is wrong

### ISSUE THREAD

**Issue by msiemens** [gitpython-developers/GitPython#550]
When having a branch which has a remote tracking branch containing a hash sign (like `features/#123`), git will store it in the config file surrounded with quotes. Now, when requesting the branch's tracking branch with `Head(...).tracking_branch()`, it doesn't remove the quotes and returns something like `origin/"refs/heads/feature#123"`.

Example `.git/config` file:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = /var/folders/n8/s89552kd2s9_v1lcgbgwl07r0000gn/T/PyGitUp.2r0xiioq/master.issue-55/.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "feature#123"]
	remote = origin
	merge = "refs/heads/feature#234"
```

Reported in msiemens/PyGitUp#55

**Comment by Byron** [comment]
Thanks for posting the issue! It was nicely reproducible, and a new release with the fix should land today.

**Comment by msiemens** [comment]
Thank you, as always a pleasure to work with you guys!
