### ISSUE TITLE
Configparser does not follow includes

### ISSUE THREAD

**Issue by sedrubal** [gitpython-developers/GitPython#557]
There is a config like:

```ini
[core]
# ...
[include]
    path = ~/path/to/another/config
```

When using this code, all configs from the other config will be ignored:

```py
cfg = git.Repo().config_reader()
cfg.read()
```

**Comment by Byron** [comment]
The latest version of GitPython definitely implements this, including [resolution of the tilde character](https://github.com/gitpython-developers/GitPython/blob/c823d482d03caa8238b48714af4dec6d9e476520/git/config.py#L415).

Can you verify you are using the latest version, or provide a self-contained example that reproduces the issue? _Maybe the merge does not work as expected_, which leads one to believe that the inclusion does not work at all.

**Comment by sedrubal** [comment]
Oops I'm sorry. Fedora packaged `GitPython 1.0.1` which is damn old. With latest `GitPython 2.1.1` it's working as expected.
Thanks for pointing me in the right direction.
