### ISSUE TITLE
Ability to make pull --allow-unrelated-histories

### ISSUE THREAD

**Issue by PonteIneptique** [gitpython-developers/GitPython#560]
Currently, if we want to work with some pull request with GitPython, it is not possible afaik to allow unrelated histories.

> The default behavior has changed since git 2.9:
> 
>     "git merge" used to allow merging two branches that have no common base by default, which led to a brand new history of an existing project created and then get pulled by an unsuspecting maintainer, which allowed an unnecessary parallel history merged into the existing project. The command has been taught not to allow this by default, with an escape hatch "--allow-unrelated-histories" option to be used in a rare event that merges histories of two projects that started their lives independently.
> 
> See the git release [changelog](https://github.com/git/git/blob/master/Documentation/RelNotes/2.9.0.txt#L58-L68) for more information.
from http://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories

**Comment by Byron** [comment]
Unless I am misunderstanding the request, I believe this is already possible. Let me show this in an example
```python
import git
r = git.Repo('.')
r.remotes.origin.pull(allow_unrelated_histories=True)
# or
r.git.pull('--allow-unrelated-histories')
```

Just from the documentation it might be impossible to understand how to use python `kwargs` to pass on to the invoked git command.

I a closing this issue, but if there are any more questions on your side or clarification, please let me know in the comments.

**Comment by PonteIneptique** [comment]
Sorry @Byron, that's totally my fault : my local version was completely out of date, hence kwargs not working.
Thanks for the answer !
