### ISSUE TITLE
Exception triggered when lightweight tag points to blob/tree

### ISSUE THREAD

**Issue by edrawd** [gitpython-developers/GitPython#561]
# Bug summary
The Reference.TagReference.tag() function in the module git/refs/tag.py in Gitpython 2.1.0 (and potentially other versions after 2.0.8) does not properly handle lightweight tags that point to blobs or trees. 

Below I will demonstrate how to create a tag pointing to a blob or tree. Next I will demonstrate how to trigger the bug in gitpython. Finally, I will show an example popular git repo that contains a tag pointing to a tree. 

I do not have a suggestion for what the correct behavior of Reference.TagReference.tag() should be, but I do not think that it should trigger an exception when the tag points to a blob or tree.

# Sample script to create a repo with a tag pointing to a blob
```bash
git init foo
cd foo
echo foo > bar.txt
git add bar.txt
git commit -m baz
git tag quux `git hash-object bar.txt`
PAGER=cat git show quux
cd ..
```

# Python script to trigger the bug (using the above repo)
```python
# pip install gitpython==2.1.0

import git

tag_name = "quux"
repo_name = "foo"
repo_obj = git.Repo(repo_name)

tag_obj = repo_obj.tags[0]
assert str(tag_obj) == tag_name

if tag_obj.commit.type == 'commit':
    print("Is a commit")
else:
    print("Not a commit")

```
# Traceback from test script
```
Traceback (most recent call last):
  File "delme.py", line 10, in <module>
    if tag_obj.commit.type == 'commit':
  File "/usr/lib/python2.7/site-packages/git/refs/tag.py", line 33, in commit
    raise ValueError("Tag %s points to a Blob or Tree - have never seen that before" % self)
ValueError: Tag quux points to a Blob or Tree - have never seen that before
```

# Example from the wild: linux 
Here I will show an example of a popular git repo that includes a tag (v2.6.11) pointing to a blob or tree. Note that Linus Torvalds, the original author of git, probably created this tag, based on the fact that he authored the successively-named tag (v2.6.12-rc2). v2.6.11 does not contain metadata. 

Running these commands:
```bash
git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git linux-stable
cd linux-stable
git show v2.6.11
```
Produces this output:

<details>

```
tag v2.6.11-tree

This is the 2.6.11 tree object.

NOTE! There's no commit for this, since it happened before I started with git.
Eventually we'll import some sort of history, and that should tie this tree
object up to a real commit. In the meantime, this acts as an anchor point for
doing diffs etc under git.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.2.4 (GNU/Linux)

iD8DBQBCeV/eF3YsRnbiHLsRAl+SAKCVp8lVXwpUhMEvy8N5jVBd16UCmACeOtP6
KLMHist5yj0sw1E4hDTyQa0=
=/bIK
-----END PGP SIGNATURE-----

tree v2.6.11

COPYING
CREDITS
Documentation/
MAINTAINERS
Makefile
README
REPORTING-BUGS
arch/
crypto/
drivers/
fs/
include/
init/
ipc/
kernel/
lib/
mm/
net/
scripts/
security/
sound/
usr/
```

**Comment by Byron** [comment]
Thanks a lot for this downright perfect issue description!

As this assertion was [created by me](https://github.com/gitpython-developers/GitPython/blame/master/git/refs/tag.py#L32) some time ago, and I believe it should remain, but be modified to indicate the user should prefer to use the `.object` property instead.

Said exception should then be documented too to allow people to protect against it. That definitely is not a nice API, but one could argue that languages that use exceptions as exhaustively as python does have a trouble to communicate possible outcomes of any function call anyway :/.

**Comment by Byron** [comment]
@edrawd It would be great if you could let me know if you find the related commit adequate as an improvement - thank you.

**Comment by Byron** [comment]
I am closing this issue as it had no interaction for more than 3 months. Please feel free to comment in case you need it to be reopened.
