### ISSUE TITLE
Push a commit to a named branch

### ISSUE THREAD

**Issue by Jfach** [gitpython-developers/GitPython#567]
I've been reading through the documentation, and I'm probably missing something, but my question is how would I achieve the following through this library? I'm trying to do the equivalent of this: 

`git push origin master:some-remote-branch`

**Comment by Byron** [comment]
`push` works similarly to `fetch` regarding its parameters, and there is a `refspec` one that can be used for this purpose, please [see the docs for details](http://gitpython.readthedocs.io/en/stable/reference.html#git.remote.Remote.fetch).

The case presented here would be solved as follows:
```python
import git
r = git.Repo('.')
r.remotes.origin.push(refspec='master:some-remote-branch')
# or
r.git.push('master:some-remote-branch')
```
