### ISSUE TITLE
Gitpython command (repo.git.show()) is not pulling correct file from git when data in file has been deleted

### ISSUE THREAD

**Issue by RaghavendraDR048** [gitpython-developers/GitPython#568]
Hi,
We are very new to python and git. We are trying to pull the data from two different versions of same file using gitpython library. When we delete the data present in a file in git and then run the command repo.git.show('HEAD','Test_file2.txt') it doesn't reflect the deleted changes from file. Also if we run the command git show HEAD: Test_file2.txt from Git command prompt the data is displayed correctly.
Below is the code snippet we are using directly through python command prompt. Python version is 3.5.2
from git import Repo
import git
repo = Repo('C:\Raghavendra\GitRepository')
repo.git.show('HEAD','Test_file2.txt')

Test_file2.txt initial version is as below:
This is second.
We are testing git displaying the file.
Testing addition

Now we delete the second and third line and then commit in Git, so the file would look like:
This is second.

Below is the output from Git command prompt 
![image](https://cloud.githubusercontent.com/assets/24934298/21675934/bfbb1cee-d359-11e6-8fff-64cef7e1fb75.png)

Now if i run the same from Python we get below output:
![image](https://cloud.githubusercontent.com/assets/24934298/21675989/fc1212e2-d359-11e6-9712-6e246d9d0c6f.png)

Please could anyone of us know how to get the correct output from gitpython library.

**Comment by Byron** [comment]
By now you might have solved the issue already - it seems to be a misconception on how to pass arguments to the git command.

In your case, changing `repo.git.show('HEAD','Test_file2.txt')` to `repo.git.show('HEAD:Test_file2.txt')` should do the job, assuming the line `git show HEAD:Test_file2.txt` from the screenshot works as expected.

I am closing this issue, but feel free to ask follow-up questions in the comments.

**Comment by RaghavendraDR048** [comment]
Hi Sebastien

Thank you yes after I changed the command it worked properly.

I should have updated it sorry didn't do it.
