### ISSUE TITLE
cloning creates an extra directory

### ISSUE THREAD

**Issue by jfach** [gitpython-developers/GitPython#570]
I'm doing a clone from a github repository via the following:

```Python
repo = git.Repo.init(destination)
origin = repo.create_remote('origin', clone_url)
origin.fetch()
origin.pull(origin.refs[0].remote_head)
```

the tree of my repository when cloning from the command line looks like this: 

```
.
├── envs
│   ├── production
│   │   └── inventory
│   └── testing
│       └── inventory
└── README.md
```

when cloning using the method described above, I get the following tree:

```
.
├── envs
│   ├── production
│   │   └── inventory
│   └── testing
│       └── inventory
├── home
│   └── jordan
│       └── tenants
│           └── jfach
│               └── envs
│                   └── envs
│                       └── production
│                           └── inventory
└── README.md
```

I should note that both are being cloned to the same directory, which in this case is `/home/jordan/jfach/tenants/envs/` (yes the `/envs` in the tree is a directory in the repository)

**Comment by Jfach** [comment]
I should note that both are being cloned to the same directory, which in this case is `/home/jordan/tenants/envs/`

**Comment by Byron** [comment]
Which version of GitPython are you using? I would also need code that reproduces the issue.
Thank you

**Comment by Byron** [comment]
@Jfach Which version of GitPython are you using? I would also need code that reproduces the issue.
Thank you

**Comment by Byron** [comment]
Closed due to inactivity - please feel free to comment or reopen if the interest is rekindled.
