### ISSUE TITLE
Can it generate signed commits and tags?

### ISSUE THREAD

**Issue by ankostis** [gitpython-developers/GitPython#579]
I'm suspecting that #124 is only for parsing signed-commits.  ~~And there is no support for signed tags.~~
Is that correct?

How much effort would it be to support creating signed commits ~~& tags~~?

**Comment by Natim** [comment]
Did you try to add this in your `.git/config` or `~/.gitconfig`:

```ini
[commit]
gpgsign = true

[tag]
gpgsign = true
```

**Comment by ankostis** [comment]
Tag works, if you pass `-u` or `--sign` flags when creating tags.
For commits, I did try that and it didn't seem to work.

Actually I peaked at the code a little, and I think it does not use `git` command when committing, but *gitdb* pure-python library.  And this library (I think) does not know how to sign commits.

**Comment by Byron** [comment]
The pure-python implementation is rather minimal and does not support signing.
In these cases, please resort to using the git command directly via `repo.git.commit(<arg-to-commit-with-signature>)`.
Even though I am closing the issue, please feel free to leave additional comments.
