### ISSUE TITLE
On Windows, SymbolicReference._iter_items misses non-packed refs

### ISSUE THREAD

**Issue by dubois** [gitpython-developers/GitPython#586]
repo.branches was not seeing some of my newly-created branches. I tracked it down to https://github.com/gitpython-developers/GitPython/blob/master/git/refs/symbolic.py#L577

            if 'refs/' not in root:  # skip non-refs subfolders

This needs to honor os.sep, eg:

            if 'refs' not in root.split(os.sep):  # skip non-refs subfolders

**Comment by Byron** [comment]
Thanks a lot for letting us know, and for suggesting a viable fix!

**Comment by ankostis** [comment]
In order to support also CYGWIN Git, maybe it needs to check posix os.sep :-(

Is tm possible to have a simple TestCase to reproduce it in Appveyor?
