### ISSUE TITLE
GIT_WORK_TREE is ignored

### ISSUE THREAD

**Issue by tbhartman** [gitpython-developers/GitPython#587]
I have a repo set up such that my working directory is at:
```
d:\tmp\git_repo
```
and the git directory is at
```
d:\tmp\git_repo\files\git
```

I then have two environment variables set:
```
GIT_DIR=d:\tmp\git_repo\files\git
GIT_WORK_TREE=d:\tmp\git_repo
```

`GitPython` correctly uses the `GIT_DIR`, but ignores `GIT_WORK_TREE`.  I have a patch and will request a pull momentarily.

**Comment by Byron** [comment]
Thanks a lot! The PR has landed, and this issue can be closed!
