### ISSUE TITLE
Assertion on creating or adding files in bare repositories

### ISSUE THREAD

**Issue by clearclaw** [gitpython-developers/GitPython#59]
I can create new files from in-memory bytestreams in non-bare
repositories easily enough:

```
        repo = git.Repo (repopath)
        istream = IStream ("blob", len (filedata), StringIO (filedata))
        repo.odb.store (istream)
        blob = git.Blob (repo, istream.binsha, 0100644, filename)
        repo.index.add ([git.IndexEntry.from_blob (blob),])
        repo.index.commit (comment)
```

However this fails with bare repositories with an assertion error
around repo.working_tree_dir.

 /home/allura/scm/git/p/jcltest/code.git/<ipython-input-14-df7424503183> in <module>()
 ----> 1 repo.index.add ([git.IndexEntry.from_blob (blob),])

 /home/allura/anvil/local/lib/python2.7/site-packages/GitPython-0.3.0_beta2-py2.7.egg/git/index/util.pyc in  
 set_git_working_dir(self, _args, *_kwargs)
      73         def set_git_working_dir(self, _args, *_kwargs):
      74                 cur_wd = os.getcwd()
 ---> 75                 os.chdir(self.repo.working_tree_dir)
      76                 try:
      77                         return func(self, _args, *_kwargs)

 /home/allura/anvil/local/lib/python2.7/site-packages/GitPython-0.3.0_beta2-py2.7.egg/git/repo/base.pyc in working_tree_dir(self)
     174                 :raise AssertionError: If we are a bare repository"""
     175                 if self._working_tree_dir is None:
 --> 176                         raise AssertionError( "Repository at %r is bare and does not have a working tree directory" % self.git_dir )
     177                 return self._working_tree_dir/home/allura/scm/git/p/jcltest/code.git/<ipython-input-14-df7424503183> in <module>()
 ----> 1 repo.index.add ([git.IndexEntry.from_blob (blob),])

 /home/allura/anvil/local/lib/python2.7/site-packages/GitPython-0.3.0_beta2-py2.7.egg/git/index/util.pyc in set_git_working_dir(self, _args, *_kwargs)
      73         def set_git_working_dir(self, _args, *_kwargs):
      74                 cur_wd = os.getcwd()
 ---> 75                 os.chdir(self.repo.working_tree_dir)
      76                 try:
      77                         return func(self, _args, *_kwargs)

 /home/allura/anvil/local/lib/python2.7/site-packages/GitPython-0.3.0_beta2-py2.7.egg/git/repo/base.pyc in working_tree_dir(self)
     174                 :raise AssertionError: If we are a bare repository"""
     175                 if self._working_tree_dir is None:
 --> 176                         raise AssertionError( "Repository at %r is bare and does not have a working tree directory" % self.git_dir )
     177                 return self._working_tree_dir

**Comment by flying-sheep** [comment]
Would be cool to have a convenience method for this, like:

```py
def Repo.add_blob(self, path: PathLike, data: bytes, mode: int = 0o100644):
    istream = IStream('blob', len(data), io.BytesIO(data))
    repo.odb.store(istream)
    return git.Blob(repo, istream.binsha, mode, str(path))
```

**Comment by Byron** [comment]
@flying-sheep I like the idea, but wonder if the suggested implementation would be what most people expect when adding something to the repository. After all, without updating the index it's not obviously there.
However, generally GitPython would benefit from some higher-level functions that just do the right thing, and if you have ideas you are welcome to contribute them or discuss them in another ticket.

**Comment by flying-sheep** [comment]
Well, adding a `index: Union[IndexFile, bool] = False` to that method would also be possible, and point people in the right direction.
