### ISSUE TITLE
Allowing putting `Repo` object into `url` argument of `Repo.create_remote`

### ISSUE THREAD

**Issue by cool-RR** [gitpython-developers/GitPython#590]

**Comment by Byron** [comment]
I find using `repo.remotes.origin.url` acceptable.

**Comment by cool-RR** [comment]
Why origin? Isn't origin the remote rather than the repo itself? I want the repo itself to be used as an argument to `create_remote` for a different repo, what should I use?

**Comment by Byron** [comment]
If you want to clone from one local path to another, you would probably want to use `repo.git_dir` instead.
