### ISSUE TITLE
Allow working with alternative index file

### ISSUE THREAD

**Issue by cool-RR** [gitpython-developers/GitPython#593]
I need to work with a repo but with an alternative repo file that I specify. Currently it seems I can't do that with GitPython, so I have code calling Git with subprocess, but if I could do it with GitPython that would be better. Maybe the `Repo` constructor could also accept an optional argument to specify an alternative index file, defaulting to the default Git one?

**Comment by Byron** [comment]
Please have a look at the [`IndexFile`](https://github.com/gitpython-developers/GitPython/blob/72dddc7981c90a1e844898cf9d1703f5a7a55822/git/repo/base.py#L93) constructor, and you will see that an alternative path can be specified.
I don't think the `Repo` object should allow overriding this either, as it is easy enough to use the `IndexFile` directly.

**Comment by cool-RR** [comment]
I know that I can make an alternative `IndexFile` object, but then I can't
do a diff between it and HEAD, which is what I need. (The `@default_index`
decorator stops you.)

Currently I use subprocess for this because I can't figure out a way to do
this with GitPython. If you think of something, please let me know.
