### ISSUE TITLE
Change `__repr__` of `Blob` and `Tree` to show name too

### ISSUE THREAD

**Issue by cool-RR** [gitpython-developers/GitPython#594]
Looking at `tuple(tree)` is pretty frustrating because you just see a list of SHAs and whether they are blobs or trees. It would be helpful to see the names too.

**Comment by Byron** [comment]
Git objects are indeed just that - they do not know were they are in the tree structure. GitPython just reflects that. It would certainly be possible to pass in the parent-path at which an object ought to be when it was obtained via a tree, but it wouldn't come for free and is just good for debugging.
Please know that GitPython is in maintenance mode, and new features are likely to be rejected.
