### ISSUE TITLE
Some files are never closed

### ISSUE THREAD

**Issue by bochecha** [gitpython-developers/GitPython#60]
I'm working on a script using GitPython to loop over lots of Git repos, pull remote changes, etc...

At some point, I noticed that doing ``repo.is_dirty()`` was opening some files which never got closed until the process exits, which in turns causes the tool to crash with "too many open files" after iterating over enough repos:
```python
import os

import git

# Put here whatever Git repos you might have in the current folder
# Listing more than one makes the problem more visible
repos = ["ipset", "libhtp"]

raw_input("Check open files with `lsof -p %s | grep %s`" % (os.getpid(),
                                                            os.getcwd()))

for name in repos:
    repo = git.Repo(name)
    repo.is_dirty()

    del repo

raw_input("Check open files again")                 # files are still open
```

I tried digging deeper down the GitPython stack, but couldn't find the actual cause.

In case that's helpful, below is the same as the previous snippet, but using directly the lowest-level gitdb objects I could find to open the files:
```python
import os

import git
from gitdb.util import hex_to_bin

# Put here whatever Git repos you might have in the current folder
# Listing more than one makes the problem more visible
repos = ["ipset", "libhtp"]

raw_input("Check open files with `lsof -p %s | grep %s`" % (os.getpid(),
                                                            os.getcwd()))

raw_input("Check open files again")                 # files are still open

for name in repos:
    repo = git.Repo(name)
    sha = hex_to_bin("71acab3ca115b9ec200e440188181f6878e26f08")

    for db in repo.odb._dbs:
        try:
            for item in db._entities:               # db._entities opens *.pack files
                item[2](sha)                        # opens *.idx files

        except AttributeError as e:
            # Not all DBs have this attribute
            pass

    del repo

raw_input("Check open files again")                 # files are still open
```

But that's just where the files are open (well, in fact they are open even lower down but I didn't manage to go deeper), not where they are supposed to be closed.

**Comment by Byron** [comment]
The issue presented by @virgiliu seems to be fixed now (with the latest version of [smmap 0.9.0](https://pypi.python.org/pypi?:action=display&name=smmap&version=0.9.0)), but by artificially constraining the file limit to 64, I can still see that pipes are leaked.
For some reason, repository instances are never freed, and I will have to figure out why that would happen.
![screen shot 2015-01-07 at 17 57 37](https://cloud.githubusercontent.com/assets/63622/5649501/b3d9317e-9696-11e4-85a6-cbd50059bae8.png)

**Comment by Byron** [comment]
As `__del__()` is not reliably called in python 3, the tests leak heavily as no repository it ever used gets cleaned up, leaving plenty of the processes shown above. Each of them comes with three pipes, quickly using up the processes resources.

For example, it's possible to run all tests with `ulimit -n 64` in python 2, but needs `ulimit -n 140` in python 3.

**Comment by Byron** [comment]
It turned out I forgot to add a tear-down super class call, which was responsible for most of the test-leakage.
On the plus side, travis now checks for this as well. 
An improved leak-test was added, which clearly shows that repositories dispose of their file handles correctly.

**Comment by mricon** [comment]
Fantastic, thanks!

**Comment by smithsp** [comment]
I am still seeing this problem in version 1.0.1.  Here is a little test script:
```python
import git
repo = git.Repo('./')
for k in repo.iter_commits(max_count=25):
     print k
```
At the same time, look at the number of open files with `lsof | grep ".git"`.  I see that the number of open files increases by about 25.  The only way to decrease the number of open files is to close the python session.

**Comment by Byron** [comment]
I think it will work if you use the latest `HEAD` of this repository, which would be `v1.0.2` if I hadn't lost access to my pypi account.

In `v1.0.1`, you should be able to instantiate the `Repo` type with `git.Repo(path, odbt=GitCmdObjectDB)` to alleviate the issue.

If this works for you, I'd be glad if you cost let me know here as well.

**Comment by earwig** [comment]
I have some reports of the same issue in earwig/git-repo-updater#9, I think. Will ask people if GitPython HEAD fixes it.
