### ISSUE TITLE
BadObject on repo after git.gc()

### ISSUE THREAD

**Issue by nova77** [gitpython-developers/GitPython#61]
Example code:

```python
>>> r = Repo.init('/tmp/foo/', bare=False)
>>> print >> open('/tmp/foo/bar.txt', 'w'), 'some content'
>>> r.index.add(['bar.txt'])
>>> r.index.commit('commit bar.txt')
>>> print r.git.status() # all clear?
# On branch master
nothing to commit (working directory clean)
>>> r.git.gc()
''
>>> r.iter_commits() # kabooom!
...
BadObject: 39154e2f45f96bdbbb86aa4f1ffc72f224b88f31
```

Tested on GitPython 0.3.2.RC1

**Comment by Byron** [comment]
I have to consider this an issue that can't be fixed automatically, as the only solution would be to watch all commands issued through the `git` command generator instance. However, as it doesn't have access to it's parent repository, it can't watch for commands like `gc` and automatically update caches.

Alternatives are as follows:
* call `repo.odb.update_cache()` yourself after such a call
* initialise your repository with an ODB implementation that doesn't cache, like the `GitCmdObjectDB`, such as in `git.Repo('.', odbt=git.GitCmdObjectDB)`. The latter DB uses the git command to stream objects, which could also be faster depending on the task. Probably it would also cause less file handles to be used (see #150)
