### ISSUE TITLE
How to do merge --squash?

### ISSUE THREAD

**Issue by ScriptProdigy** [gitpython-developers/GitPython#617]
I'm looking to squash a few of the last commits of a repo into one commit programmatically using GitPython. Its fairly straight forward using the cli, 

git reset --soft HEAD~2
git merge --squash HEAD@{1}

then I can just commit it. I know how to reset using gitpython, though the squash merge I can't find much info about. Any help is much appreciated!

**Comment by ScriptProdigy** [comment]
At the moment Im just going to use subprocess to execute what I need, though this feature is requested.

**Comment by Byron** [comment]
It seems like what you want is covered in [this part of the documentation](http://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly).
