### ISSUE TITLE
Configparser does not respect order of config files with includes

### ISSUE THREAD

**Issue by DanielSiepmann** [gitpython-developers/GitPython#627]
When you have an include statement in the user `.gitconfig` there content will take precedence over the local `.git/config` of the repository.

E.g. the following code:
`entry = repo.config_reader().get_value('gitlab', 'url')`

With the following config setup:

`~/.gitconfig`:
```ini
[include]
    path = ~/.gitconfig-local
[gitlab]
    url = url1
```

`~/.gitconfig-local`:
```ini
[gitlab]
    url = url2
```

`.git/config`:
```ini
[gitlab]
    url = url3
```

Will return `url2` I would expect to receive `url3` instead as local config should take precedence as the include was in a more global config.

Looks like the issue resides inside the `read ` function e.g. https://github.com/gitpython-developers/GitPython/blob/c823d482d03caa8238b48714af4dec6d9e476520/git/config.py#L427 will just add the includes to the list, which is just wrong, as they should be read instantly to overwrite just the already known configs.

As the function is just to big, I'm not able to provide a fix.

Versions in use:
```
>>> import git; git.__version__
'2.1.3'
```

```
python --version
Python 2.7.13
```

**Comment by Byron** [comment]
@DanielSiepmann Thanks for the detailed description, and for the fix! Please have a look at my review - I hope to be able to merge the fix soon and create a new release accordingly.
