### ISSUE TITLE
TypeError When Calling repo.current_branch When HEAD is Detached

### ISSUE THREAD

**Issue by mam8cc** [gitpython-developers/GitPython#629]
Similar issue as https://github.com/gitpython-developers/GitPython/issues/510.
Example code (**detached.py**):
```
import git
from git import Repo

repo = Repo()
origin = git.remote.Remote(repo, 'origin')

print(repo.active_branch.name)
```

Example 
```
$ git status
On branch master
nothing to commit, working tree clean

$ python detached.py
master

$ gco a9f095e
Note: checking out 'a9f095e'.
HEAD is now at a9f095e... test

$ python detached.py
Traceback (most recent call last):
  File "detached.py", line 7, in <module>
    print(repo.active_branch.name)
  File ".../lib/python3.5/site-packages/git/repo/base.py", line 663, in active_branch
    return self.head.reference
  File ".../lib/python3.5/site-packages/git/refs/symbolic.py", line 251, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'a9f095e1689428696ee6dc479d4617de38a21a24'
```

System Details:
```
$ git --version
git version 2.12.0
$ pip freeze | grep GitPython
GitPython==2.1.3
$ python --version
Python 3.5.2
```

**Comment by nmaggioni** [comment]
+1

**Comment by Byron** [comment]
This is indeed a very similar issue as in the referenced one, I think we can have a conversation there instead.
Thus I am closing this one, hoping that any resolution will be applied to `current_branch` as well, which seems to be just an alias.

**Comment by stiliajohny** [comment]
Hi all 
Is there any movement on this issue ? 
@Byron @cgi1 @mam8cc @nmaggioni

**Comment by Byron** [comment]
No, _(unfortunately)_ detached head states are communicated with exceptions.

**Comment by spanthr** [comment]
Hi, Is there any movement on this issue?

**Comment by Byron** [comment]
I keep referring to [this comment](https://github.com/gitpython-developers/GitPython/issues/633#issuecomment-786710029) which invites folks to submit a PR to create the movement they require.
