### ISSUE TITLE
Can't list remote branches

### ISSUE THREAD

**Issue by NiQ1** [gitpython-developers/GitPython#631]
repo = git.Repo("...") // Directory that already has a cloned repository
repo.heads
[<git.Head "refs/heads/master">]

The repository has a whole bunch of remote branches but I only see the local one. Any way of getting a list of all remote branches?

**Comment by oerp-odoo** [comment]
I have same issue

**Comment by Byron** [comment]
You can access remote refs via `repo.remotes.origin.refs`. You will find more code in context by search for `refs` in [the tutorial](http://gitpython.readthedocs.io/en/stable/tutorial.html#handling-remotes).

**Comment by afghanistanyn** [comment]
data = Git().execute('git ls-remote -h git_url')
        branches = [ x.split('/')[-1] for x in data.split('\n') ]

**Comment by randyesq** [comment]
GitPython 3.1.2 and this still doesn't work.

**Comment by eighthave** [comment]
https://github.com/gitpython-developers/GitPython/issues/631#issuecomment-307583010 works for me
