### ISSUE TITLE
ImportError: No module named ez_setup

### ISSUE THREAD

**Issue by demmith** [gitpython-developers/GitPython#643]
Upon issuing `python setup.py install` the following exception occurs ...

`Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from ez_setup import use_setuptools
ImportError: No module named ez_setup`

This occurs no matter whether the repo was cloned or downloaded.

**Comment by njalerikson** [comment]
GitPython defaults to using `setuptools` for installation, it falls back to using `ez_setup` when `setuptools` is not available. If neither `setuptools` or `ez_setup` is available you will get the error you see.

It is most likely in your best interest to simply install `setuptools`:

```
pip install setuptools
```

And if you are only looking for the latest stable release of GitPython you likely do not want to clone or download this repo from GitHub but rather install from PyPA via `pip`:

```
pip install gitpython
```

If for whatever reason the `pip` command is not available for you see how to install it here: https://packaging.python.org/tutorials/installing-packages/#id10

**Comment by Byron** [comment]
I am closing this issue, as I believe it's an issue developers could have on a clone and that the issue was explained thoroughly to allow a workaround.
Thanks to everyone involved for describing the issue, and for helping to resolve it :).
