### ISSUE TITLE
Can't pass environment variables to Git.execute

### ISSUE THREAD

**Issue by AJMansfield** [gitpython-developers/GitPython#644]
This is needed for commands like `git-commit` and `git-commit-tree` in order to be able to specify author and committer information. While `git-commit` does provide the `--author` and `--date` to specify author information, there are no options for specifying committer information, and `git-commit-tree` is wholly dependent on environment variables.

For instance, the following code fails with `TypeError: type object got multiple values for keyword argument 'env'`.

```
def pipe_of(string):
	import os
	if type(string) is str:
		string = bytes(string, 'utf-8')
	r,w = os.pipe()
	os.write(w, string)
	os.close(w)
	return r
git = Repo('/path/ro/repo').git
blob = git.execute(['git', 'hash-object', '-w', '--stdin'], istream=pipe_of("my data"))
tree = git.execute(['git', 'mktree'], istream=pipe_of("100644 blob {}\tmy-file\n".format(blob)))
commit = git.execute(['git', 'commit-tree', tree], istream=None, env={
	'GIT_AUTHOR_NAME':'Author Name',
	'GIT_AUTHOR_EMAIL':'author@example.com',
	'GIT_AUTHOR_DATE':'1400000000+0000',
	'GIT_COMMITTER_NAME':'Comitter Name',
	'GIT_COMMITTER_EMAIL':'committer@example.com',
	'GIT_COMMITTER_DATE':'1500000000+0000',
	})
```

**Comment by AJMansfield** [comment]
Note that I'm currently working on a fix (https://github.com/AJMansfield/GitPython), just wanted to document the issue first.

**Comment by bpoldrack** [comment]
Isn't that, what `with custom_environment( ....)` is for?

**Comment by AJMansfield** [comment]
@bpoldrack Two reasons, one technical and the other semantic.

 - `with custom_environment( ... )` isn't thread-safe. I'm using this in a threaded context, and having to manage creating separate `Git` instances per-thread adds extra complexity.

 - It's not really the 'right' way to do it in my use case, as the author and committer data are genuinely parameters rather than configuration information for my use case - I'm copying existing information from another VCS over to git, not creating new info.
