### ISSUE TITLE
Allow max_chunk_size to be configurable

### ISSUE THREAD

**Issue by alexandernst** [gitpython-developers/GitPython#648]
[Here](https://github.com/gitpython-developers/GitPython/blob/cf8dc259fcc9c1397ea67cec3a6a4cb5816e3e68/git/cmd.py#L659) `max_chunk_size` will usually contain (depending on the platform) `8192`, which is a very high value for a chunk and won't trigger a `.write` (keep reading) until quite some output is printed to stdout. I propose to make that value configurable (maybe via an argument).

My use case:

I have the following class:

	class PipeIO(io.BytesIO):
		def __init__(self, cb):
			io.BytesIO.__init__(self)
			self.updater_cb = cb

		def write(self, b):
			buf = io.BytesIO.getbuffer(self).tobytes()
			progress = re.findall("(?<=\()\d+\/\d+(?=\))", buf.decode("utf-8"))

			try:
				self.updater_cb(progress[-1])
			except:
				pass

			return io.BytesIO.write(self, b)

And I use it like this:

    stdout = PipeIO(self.my_updater_callback)
    self.repo.git.filter_branch("-f", "--env-filter", s, output_stream = stdout)

This will cause my callback to parse the content of the buffer every time [`.write`](https://github.com/gitpython-developers/GitPython/blob/cf8dc259fcc9c1397ea67cec3a6a4cb5816e3e68/git/util.py#L127) is called, which is very useful if I want to provide progress updates while running a long git command (like `filter-branch`).

Possible solution:

Make it possible to call raw commands with one extra argument:

    self.repo.git.filter_branch("-f", "--env-filter", s, output_stream = stdout, max_chunk_size = 32)

**Comment by Byron** [comment]
Thanks for your suggestion. It should be relatively straightforward to make this value configurable, and I would be happy about a PR.
