### ISSUE TITLE
Silently opens repo for ancestor directory

### ISSUE THREAD

**Issue by ivesn** [gitpython-developers/GitPython#65]
Let /git be a git repo, suppose path /git/foo/bar exists (file or directory).

```python
>>> git.Repo('/git/foo/bar')
<git.Repo "/git/.git">
```

I think this is very dangerous behaviour. For example, in a testing environment one might use

```python
shutil.rmtree(some_repo.working_dir)
```

where, if some_repo was subject to the behaviour above, created from a path in a project's working directory, unhappiness might ensue.

**Comment by Byron** [comment]
The keyword was added as discussed.

Additionally, I recorded the process of fixing this one

* [Part 1 on youtube](http://youtu.be/zmrYoOhs6pc)
* [Part 2 on youtube](http://youtu.be/coUpfvG8Wxo)
