### ISSUE TITLE
Authentication over HTTP

### ISSUE THREAD

**Issue by strin** [gitpython-developers/GitPython#651]
Does GitPython support Authentication using HTTP protocol?

https://git-scm.com/book/en/v2/Git-on-the-Server-Smart-HTTP

**Comment by Byron** [comment]
It supports everything that the 'git' command-line supports, even though in many cases, you will have to use environment variables (works from within python) to configure the git-command accordingly.
In your specific case, you would have to see if that suffices, or if the system/runtime environment must be prepared before using GitPython.
