### ISSUE TITLE
When run py in systemctl or crontab,  'Permission denied (publickey).

### ISSUE THREAD

**Issue by FindHao** [gitpython-developers/GitPython#659]
Hi,
I use gitpython in a project like this:
```python
with open(os.path.join(current_project_path,'config'), 'r')as fin:
    text_project_base_path = "/home/test/test/"
    git_ssh_identity_file = "/home/test/.ssh/ras_key"
git_ssh_cmd = '/usr/bin/ssh -i %s' % git_ssh_identity_file
...
...
def git_pull():
    log = ''
    with Git().custom_environment(GIT_SSH_COMMAND=git_ssh_cmd):
        repo = Repo(text_project_base_path)
        g = repo.git
        log += g.pull()
        log += g.status()
    return log

git_pull()
```
When I run it in terminal, it works well. 
But when I run a systemd script like 
```systemd
[Unit]
Description=test
Wants=network-online.target
Requires=sshd.service
After=network.target NetworkManager-wait-online.service
[Service]
Type=simple
ExecStart=/usr/bin/python3 /home/test/test/entry.py
KillMode=mixed

```
There's  an error: 
```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
cmdline: git pull
stderr: 'Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.'
````
What's wrong with the code?

**Comment by FindHao** [comment]
[Specify private SSH-key to use when executing shell command with or without Ruby?](https://stackoverflow.com/questions/4565700/specify-private-ssh-key-to-use-when-executing-shell-command-with-or-without-ruby)
I do following the link, and it works. 
However, I don't think it's the best way to solve it.

**Comment by FindHao** [comment]
I change the `~/.ssh/config` file by adding `IdentityFile IdentitiesOnly`.

**Comment by Byron** [comment]
I think the problem lies within the context in which GitPython is run, and not GitPython itself. Thus I close the issue, and hope you have resolved this issue in the mean-time.
