### ISSUE TITLE
How to get the last commit?

### ISSUE THREAD

**Issue by niso120b** [gitpython-developers/GitPython#663]
How to get the last commit?

**Comment by njalerikson** [comment]
```
import git
repo = git.Repo("local/path/to/repo/")
commit = repo.head.commit
```

See documentation: https://gitpython.readthedocs.io/en/stable/tutorial.html#the-commit-object

**Comment by qneill** [comment]
Better - read docs, ask questions, e.g. on stackoverflow (it's not an issue).

See http://gitpython.readthedocs.io/en/stable/intro.html#getting-started

**Comment by Byron** [comment]
I believe this question has been answered.

**Comment by av1m** [comment]
For those passing through here : https://stackoverflow.com/a/21431791/11120444
