### ISSUE TITLE
Archive method does not support paths parameter

### ISSUE THREAD

**Issue by maurociancio** [gitpython-developers/GitPython#67]
In the following code you are not able to supply what paths you would like to archive (and not all the repo).

    repo = git.Repo("/git/repo")
    repo.archive(ostream=temparchive, treeish="master", format="tar")

Meanwhile, if you use the git archive command you can suplly what paths you would like to archive.
An extra kw args could be the list of paths you want in the tar file.

**Comment by Byron** [comment]
You can now watch the live-coding session [on youtube](http://youtu.be/pE0WrRjcl3s).
