### ISSUE TITLE
How to generate hash-object

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [gitpython-developers/GitPython#672]
Is there a command similar to ```git hash-object <my-file>```?
Can not found one in the docs...

**Comment by Byron** [comment]
You could use `repo.git.hash_object('<my-file>')` to accomplish this. If something is not directly provided by `GitPython`, you can always  [call git directly](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly).

**Comment by Jorgen-VikingGod** [comment]
thx - will try it
