### ISSUE TITLE
How to check whether a tag exists or not in a repository

### ISSUE THREAD

**Issue by cpILW** [gitpython-developers/GitPython#675]
I was reading through the docs and couldn't find the method to check whether a tag exists in a repo.
Does such a method exist?  If not, how would I check if a tag exists?

https://gitpython.readthedocs.io/en/stable/reference.html?highlight=push#module-git.objects.tag

The way of doing this from CMD line is $  git ls-remote <remote-name> refs/tags/<tag-name>
but what's the equivalent way using GitPython?

Thanks

**Comment by Byron** [comment]
I think you can accomplish this with the `repo.tags` dictionary.
The following usage example is taken from the tutorial, but what you are probably looking for is something along the line of this `tag_you_are_looking_for in repo.tags`.
I hope this answers your question.

<details>

```
tags = repo.tags
        tagref = tags[0]
        tagref.tag                  # tags may have tag objects carrying additional information
        tagref.commit               # but they always point to commits
        repo.delete_tag(tagref)     # delete or
        repo.create_tag("my_tag")   # create tags using the repo for convenience
```
