### ISSUE TITLE
VERSION file lists old version

### ISSUE THREAD

**Issue by JasonMWhite** [gitpython-developers/GitPython#698]
Somehow, the commit that bumped the VERSION file to 2.1.7 didn't make it into master. If you check out this repo and build it, `setup.py` lists the current version as 2.1.6.

**Comment by JasonMWhite** [comment]
I would just update the VERSION file in a PR, but then there's a conflict with the PyPi-released version and the git history on this repo. Perhaps it's just easier to release a 2.1.8?

**Comment by ankostis** [comment]
Or bump it to `2.1.7.post0` (and be PEP440 compliant)?

**Comment by Byron** [comment]
@JasonMWhite Thanks for the hint! I don't know how that happened actually, it should not be possible actually. Even though it probably points to some issue that should be understood, I prefer the 'fast way' and just go ahead with release 2.1.8 instead.
