### ISSUE TITLE
Wrong build order of arguments and options?

### ISSUE THREAD

**Issue by noisebleed** [gitpython-developers/GitPython#70]
Executing `repo.git.stash('save', keep_index=True)` turns into:

    git.exc.GitCommandError: 'git stash --keep-index save' returned exit status 1: Usage: git stash list [<options>]
       or: git stash show [<stash>]
       or: git stash drop [-q|--quiet] [<stash>]
       or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
       or: git stash branch <branchname> [<stash>]
       or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
                           [-u|--include-untracked] [-a|--all] [<message>]]
       or: git stash clear

The command built by GitPython is `git stash --keep-index save`. 

If using `git stash save --keep-index` (options first) then this works fine. Thoughts?

**Comment by Byron** [comment]
I confirm that the only way to control order is to use the `string` arguments form to invoke the git command, as it will maintain the given ordering of arguments.
This is a suitable workaround for the issue stated here.
Thanks for bringing this up, @millerdev .
