### ISSUE TITLE
Blame does not support complex revision queries

### ISSUE THREAD

**Issue by mitar** [gitpython-developers/GitPython#71]
For example, `git blame rev1..rev2 filename`. This one has one additional keyword before `filename`: `boundary` for those lines which are out of the specified range. And should be probably ignored.

**Comment by Byron** [comment]
I have added [a new test](https://github.com/gitpython-developers/GitPython/blob/master/git/test/test_repo.py#L318) which at least verifies that this kind of blame output can be parsed as I would expect it.

However, there might be something I am missing. If you have the time, please try the latest version on github or the upcoming *v0.3.5* to see if it suits your needs.
