### ISSUE TITLE
Update hash after tree modify

### ISSUE THREAD

**Issue by MillQK** [gitpython-developers/GitPython#712]
Why tree sha isn't updates after `TreeModifier.set_done` call?

**Comment by Byron** [comment]
Could you provide more information? Such as the GitPython version and python version you run on, as well as the code that allows to reproduce the issue at hand.
Thank you.

**Comment by MillQK** [comment]
GitPython version: 2.1.7
Python 3.6.3
Before actions:
Created bare empty repo. Clone that repo (not mirror). Committed and pushed two files in non-bare repo.
Then:
`bare_repo = Repo('/Users/jetbrains/gitTests/test/bare_rep')
root_tree = bare_repo.head.ref.commit.tree

root_tree.hexsha
'cabbb57ebc448eb116f5b64d014aeaf6b4fff528'

root_tree.blobs
[<git.Blob "eb18bc105c494e58ec7c35149ab2371f0f3470e1">, <git.Blob "d4e14de006c0fe7bed84cc799df208c4ebcc521a">]

root_tree.trees
[]

root_tree_cache = root_tree.cache
root_tree_cache.__delitem__('MY_BLOB')
root_tree_cache.set_done()

root_tree.blobs
[<git.Blob "d4e14de006c0fe7bed84cc799df208c4ebcc521a">]

root_tree.hexsha
'cabbb57ebc448eb116f5b64d014aeaf6b4fff528'`

After last Tree.hexsha expected new sha for tree with only one blob.

**Comment by MillQK** [comment]
GitPython version: 2.1.7
Python 3.6.3
Before actions:
Created bare empty repo. Clone that repo (not mirror). Committed and pushed two files in non-bare repo.
Then:
```
bare_repo = Repo('/Users/jetbrains/gitTests/test/bare_rep')
root_tree = bare_repo.head.ref.commit.tree

root_tree.hexsha
'cabbb57ebc448eb116f5b64d014aeaf6b4fff528'

root_tree.blobs
[<git.Blob "eb18bc105c494e58ec7c35149ab2371f0f3470e1">, <git.Blob "d4e14de006c0fe7bed84cc799df208c4ebcc521a">]

root_tree.trees
[]

root_tree_cache = root_tree.cache
root_tree_cache.__delitem__('MY_BLOB')
root_tree_cache.set_done()

root_tree.blobs
[<git.Blob "d4e14de006c0fe7bed84cc799df208c4ebcc521a">]

root_tree.hexsha
'cabbb57ebc448eb116f5b64d014aeaf6b4fff528'
```

After last Tree.hexsha expected new sha for tree with only one blob.

**Comment by Byron** [comment]
Thanks for the additional explanation!

I have had a look at the code, and it appears it's a low-level primitive which doesn't maintain a connection to the underlying git index. Thus I believe this won't be fixed, even though it appears unexpected at first.

If you indeed want maximum control over how things are done, you should use the `repo.index` and use its methods to alter the repository state, write it back and commit.

Otherwise it would be easier to just use higher level git commands.
I hope it works for you.

**Comment by MillQK** [comment]
Thanks for answers!
