### ISSUE TITLE
repo.git.diff not reading properly from remote

### ISSUE THREAD

**Issue by mattmoskwa** [gitpython-developers/GitPython#713]
GitPython 2.1.8
Python 3.6.2

I want to diff a file from the remote using `repo.git.diff("origin/master", "path/to/file")`, and I have confirmed that the command run from the cmdline does report a diff, but I am getting just an empty string back.

Interestingly, the commit reported by `repo.head.commit` is different from `HEAD` on the cmdline (gitpython reports that it's two commits ahead somehow).

**Comment by Byron** [comment]
I believe it's hard to help without a script that reproduces the situation you are in, and I hope you can provide that.
In the meantime, the example command provided would also just call the `git` executable, which would do exactly the same as what you would see if it was executed manually. You can enable `GIT_PYTHON_TRACE=full` to learn more about what GitPython ends up calling.

**Comment by mattmoskwa** [comment]
```
2017-12-28 18:41:10,783 INFO [git.cmd] git version -> 0; stdout: 'git version 2.13.3'
2017-12-28 18:41:10,790 INFO [git.cmd] git version -> 0; stdout: 'git version 2.13.3'
2017-12-28 18:41:10,926 INFO [git.cmd] git fetch -v origin
2017-12-28 18:41:16,933 INFO [git.cmd] git diff origin/development version.py -> 0
> run.py(50)check_version()
-> if version_diff:
(Pdb) print(repo.git.diff('origin/development', 'toaster-gradle/app/version.py'))
2017-12-28 18:41:54,060 INFO [git.cmd] git diff origin/development version.py -> 0

(Pdb) print(repo.head.commit)
2017-12-28 18:42:04,131 INFO [git.cmd] git cat-file --batch-check
# this is the tip of development, two commits ahead of my local repo
66138c7e6a4e47be14ad6fb30d8ab8d043f6833
```

from cmdline:
```
>  git log
commit 2e2f79a025b1050a90a8e44272df3da8048f3161 (HEAD -> development, master)
> git diff origin/development version.py
diff --git a/version.py b/version.py
index f0891e5..d93912e 100644
--- a/version.py
+++ b/version.py
@@ -1 +1 @@
-__version__ = '0.3.8'
\ No newline at end of file
+__version__ = '0.3.7'
```

**Comment by mattmoskwa** [comment]
I can't really provide a script that interacts with a private repository. Is there something else I could provide that could help?

**Comment by Byron** [comment]
@mattmoskwa  I think it would help if the issue is reduced to a minimal viable example, which can be posted here to help reproducing the issue. Chances are that in the course of this, this particular issue is understood better, too, to the point when it becomes clear what is causing it.

**Comment by Byron** [comment]
Closed due to inactivity - please feel free to comment or reopen if the interest is rekindled.
