### ISSUE TITLE
Prevent concurrent access from multiple processes

### ISSUE THREAD

**Issue by steffenschroeder** [gitpython-developers/GitPython#714]
Hi,
this is rather an issue than a call for help.
I have a Flask App which uses  GitPython. It has multiple worker processes.
The has 2 responsibilites:
1. receive Github webhook -> clone/pull Reposotories
2. answer web requests - the requests should determine the first tag which contains a commit. (basically a call to `git tag --contains <sha1>`)

Since there are many concurrent request, they might lock each other on file system level.

Is there any possibility to "serialize" the questests to the git repo (other than use a celery or others)

Any help is welcome.

Thanks,
Steffen

**Comment by Byron** [comment]
To me this reads like a question, even though it's stated that it's an issue. Maybe it's just semantics.
Any kind of synchronization among workers is something your application would have to do in some way. GitPython has no ability to wait for a lock to be released.
Generally it is advised to only use one GitPython instance per git repository.
Fixing this appears out of scope for this project, as the lock issue you run into is handled by the git program, not GitPython.
The latter could possibly be configured in some way by sneaking in the [`BlockingLockFile`](https://github.com/gitpython-developers/GitPython/search?utf8=%E2%9C%93&q=BlockingLockFile&type=), but there is no way to do that for the git program itself, as far as I know.

Even though I am closing this question, please feel free to leave more comments or remarks as you see fit.

**Comment by steffenschroeder** [comment]
Thanks for the reply.
Yes, it was more a question than an issue.
I agree that this is out of scope of this project.
I just thought you had heard this kind of requirement before.

Nevertheless, thanks for the prompt response :-)
