### ISSUE TITLE
how to delete git directory?

### ISSUE THREAD

**Issue by zhubangpei** [gitpython-developers/GitPython#716]
remove(self, items, working_tree=False, **kwargs)
index.remove(["/data/tmp/test.txt"],working_tree=True)  only delete file，but how
can I delete directory? index.remove(["/data/tmp/test.txt"],True,"r") this way is wrong

**Comment by stsewd** [comment]
Have you tried `index.remove(['data/tmp/'], True, r=True)`?

From the docs

> Remove the given path at all stages. If it is a directory, you must specify the r=True keyword argument to remove all file entries below it. If absolute paths are given, they will be converted to a path relative to the git repository directory containing the working tree

**Comment by Byron** [comment]
Thanks @stsewd , I believe your answer should help @zhubangpei to get the desired result.
Another alternative is always to use git directly, like in `repo.git.rm('./data/tmp', r=true)`.
