### ISSUE TITLE
GitConfigParser.set_value should support setting multiple values for an option

### ISSUE THREAD

**Issue by craftyguy** [gitpython-developers/GitPython#717]
GitConfigParser.set_value does not allow for setting multiple values for a given option.
One example of this is in [the refspec documentation for git](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec):

```
remote "origin"]
	url = https://github.com/schacon/simplegit-progit
	fetch = +refs/heads/master:refs/remotes/origin/master
	fetch = +refs/heads/experiment:refs/remotes/origin/experiment
```

If you try to call `set_value` twice with the two different refspecs above, only the last one will get set.. which makes sense since `set_value` seems to only support setting one value for a given option.

**Comment by Byron** [comment]
@ajdavis Yes, I am absolutely interested. The implementation will certainly require some effort. In order not to break the existing API, it might be easiest to add methods specifically for getting and setting multiple values.

**Comment by maiamcc** [comment]
FWIW, tangential to this ticket but I'd also appreciate it if there were a way to GET multiple values for a given option (equivalent to [`git config --get-all`](https://git-scm.com/docs/git-config#Documentation/git-config.txt---get-all)). Should I open a new issue?

**Comment by Byron** [comment]
By now this is implemented thanks to a generous PR.
