### ISSUE TITLE
Hang in git.Repo.clone_from() [Inter-process Communication Problem]

### ISSUE THREAD

**Issue by mandaarp** [gitpython-developers/GitPython#72]
Task: 
Clone from a remote repository having ssh://abc@domain.com/git/remote_repo format, which has submodules included from the outside of domain.com.

Problem:
current_repository = git.Repo.clone_from(r"ssh://abc@domain.com/git/remote_repo", r"d:\temp")

the remote_repo has 313 objects (files and folders). Above method call hangs after fetching 294 objects. Total size of remote_repo is 82 MB.

Observations:

1. Command Prompt: "git clone -v ssh://abc@domain.com/git/remote_repo d:\temp" works
2. Git Bash: "git clone -v ssh://abc@domain.com/git/remote_repo d:\temp" works
3. Python interpreter: os.system("git clone -v ssh://abc@domain.com/git/remote_repo d:\\temp") works

Possible but incomplete solution:

there is some problem with stderr=PIPE parameter of subprocess.Popen call in execute method of Python27\Lib\site-packages\GitPython-0.3.2.RC1-py2.7.egg\git\cmd.py. 

If I change the code to below:

                err_file = open("d:\\err.txt","w")
		# Start the process
		proc = Popen(command,
						cwd=cwd,
						stdin=istream,
						stderr=err_file,
						#stderr=PIPE,
						stdout=PIPE,
						close_fds=(os.name=='posix'),# unsupported on linux
						**subprocess_kwargs
						)
The process does not hang.

**Comment by Byron** [comment]
Process handling was improved to the point where pipes are unable to run full and block.
Please see the related ticket #145 .

**Comment by timblechmann** [comment]
@Byron unfortunately we've still seen this issue with gitpython 1.0.1 on windows. i didn't follow all the codepaths, but using `quiet=True` for my `fetch` and `clone_from` calls resoves this issue, so there must still be something fishy :/

i'm not exactly familiar with the implementation, but https://github.com/gitpython-developers/GitPython/blob/master/git/cmd.py#L661 still seems to have a codepath, which doesn't use the `.communicate` API ...

**Comment by Byron** [comment]
Indeed, by looking at the code linked by you, I'd think that a deadlock is possible here. However, it seems that this functionality is used just [once in an unrelated command](https://github.com/gitpython-developers/GitPython/blob/7b854878fb9df8d1a06c4e97bff5e164957b3a0d/git/repo/base.py#L905).

When looking at the code-path taken by fetch/pull, it becomes apparent that it will [enforce opening stdout](https://github.com/gitpython-developers/GitPython/blob/7b854878fb9df8d1a06c4e97bff5e164957b3a0d/git/remote.py#L653), even though it [never reads from it](https://github.com/gitpython-developers/GitPython/blob/7b854878fb9df8d1a06c4e97bff5e164957b3a0d/git/remote.py#L553) - this could be the deadlock you experience.

The `clone_from` codepath could have the same problem unless [a progress-handler](https://github.com/gitpython-developers/GitPython/blob/7b854878fb9df8d1a06c4e97bff5e164957b3a0d/git/repo/base.py#L827) is used. A change was made that could fix the clone-issue.

A few changes have been made, and you are welcome to test them with your setup. In case it works, please let me know.
