### ISSUE TITLE
How to check if a commit exists?

### ISSUE THREAD

**Issue by strokirk** [gitpython-developers/GitPython#721]
Like the title says. I'd like to check if a specific commit exists. 
Trying to run `iter_commits` over a rev that doesn't exists throws an exception, and I'd like to avoid that in order to provide nicer user output for my script.

Pseudocode:
```
if repo.exists(source):
    return list(repo.iter_commits("%s...%s" % (source, target)))
else:
    print("Couldn't find %s, you need to run git fetch")
```

**Comment by Byron** [comment]
I think the way to go is to catch the exception.
Exceptions are the way GitPython communicates errors in most (if not all) cases, and I believe there is no way around it.
As I hope this answered your question, I am closing the issue. Please feel free to keep posting here if you need clarification.

**Comment by leos313** [comment]
Hi Byron, your answer is clear, thank you. However, I think it is possible to keep the issue open for future improvement: it can be a feature that other people think is worth to have.
Thank you, Byron

**Comment by Byron** [comment]
If it should be a feature or change in behavior, please submit a new issue which presents the desired capabilities in a way that would allow discussion and/or contributions. Thank you
