### ISSUE TITLE
Why commit message dont match its SHA-ID?

### ISSUE THREAD

**Issue by imkoukou** [gitpython-developers/GitPython#727]
For test, I commit a new repo 3 three times.

c=list(repo.iter_commits("master"))
In [345]: c
Out[345]:
[<git.Commit "9d7fff7aecd2be5140f0e1d30d7430c66f4ce0cd">,    # 3rd commit' SHA
 <git.Commit "1a602b519db636fb1bd2ec5a26a56ff70a2adcd8">,  # 2nd commit' SHA 
 <git.Commit "155f8d2300d6e9512029771f183567b426d6a379">]  # 1st commit' SHA 

The SHA are all right.  But when I listed message of each commit, the message does not 
match the SHA. 
In [346]: m=[i.message for i in c]
In [347]: m
Out[347]: 
['test\n',   # message of 1st
'test 3\n', # message of 3rd
'test 2\n'] #message of 2nd 

In [352]: c[0].hexsha
Out[352]: '9d7fff7aecd2be5140f0e1d30d7430c66f4ce0cd'   # the SHA ID is 3rd commit, it is correct
In [353]: c[0].message
Out[353]: 'test\n'   # the message is 1st commit ???!

Did I do something wrong?

**Comment by Byron** [comment]
Interesting! Could you post information about the GitPython version you are using, at the very least?
It would also be nice to get a script that reproduces the issue clearly, maybe then it can be fixed.
Thanks a lot.

**Comment by imkoukou** [comment]
In fact, using the latest version I cannot reproduce this phenomenal. 
Because I tried directly to use much git commands. Maybe I missed some git command useage and caused this situation. 
Sorry for the lack of logs, I will close this issue.
