### ISSUE TITLE
Staging hunks

### ISSUE THREAD

**Issue by tomkcook** [gitpython-developers/GitPython#729]
I've tried googling and asking this on StackOverflow but got no response.

Is there a way to stage a hunk of a file as is possible with `git add -i`?  Could you please point me towards some example code to do so?

**Comment by tomkcook** [comment]
Or, alternatively, is there any way to add a version from memory to the index?

I'm thinking something like:
```
content = b'.....'
repo.index.add(path='path/to/file', content=content)
```

**Comment by Byron** [comment]
Re-implementing staging hunks is rather difficult, no matter what.
However, it would certainly work by determining which hunks to use by analyzing a diff, and creating a new object that contains the desired changes.
Objects can be added from memory using `repo.index` indeed, and I recommend [using the tutorial](http://gitpython.readthedocs.io/en/stable/tutorial.html#the-index-object) for a start.

I hope this already helps!
As there can be no time spent on actually helping with the implementation details, I believe it's fair to close the issue.
However, please feel free to add comments if something else pops up.

Everything else i
