### ISSUE TITLE
git pull failed sometimes and i had retried 6 times in my code 

### ISSUE THREAD

**Issue by huagui** [gitpython-developers/GitPython#735]
**my code :**
   repo = Repo(path)
   hexsha = repo.head.commit.hexsha  
   self.logger.info("git reset --hard HEAD to {path}".format(path=path))
   repo.head.reset(index=True, working_tree=True)
   origin = repo.remotes.origin
   self.logger.info("git pull {repository} to {path}".format(repository=repository, path=path))
   origin.pull()

**error message:**

Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v origin
  stderr: 'fatal: unable to access 'https://*********.git/': gnutls_handshake() failed: An unexpected TLS packet was received.'

**Comment by Byron** [comment]
This issue is clearly related to networking, and is nothing that can be fixed by `GitPython`.
