### ISSUE TITLE
gpgsig is undocumented

### ISSUE THREAD

**Issue by graingert** [gitpython-developers/GitPython#738]

**Comment by Byron** [comment]
This issue is too vague to trigger any change, which is why I have to close it.

Please consider amending to this issue in order to have a chance someone will pick it up.

**Comment by graingert** [comment]
Like is it a string or bytes or what?

**Comment by ankostis** [comment]
Dear @graingert is it possiblw to use [github permalink](https://help.github.com/articles/creating-a-permanent-link-to-a-code-snippet/) to identify the function(s) your are talking about?

**Comment by graingert** [comment]
It's an undocumented property on Commit and Tag

**Comment by ankostis** [comment]
Great, thanks.  Indeed it is missing from  the docstring.
