### ISSUE TITLE
Some command line arguments can not be used with 'remote.fetch' or 'remote.push'.

### ISSUE THREAD

**Issue by lexa** [gitpython-developers/GitPython#745]
remote.push has a following declaration:

` def push(self, refspec=None, progress=None, **kwargs):`

Because of **kwargs, all arguments must be keyworded, that mean that there is no way to pass command line options which don't require an argument, like '--force' or '--dry-run'.

**Comment by Byron** [comment]
I believe in that case, you can pass `force=true` or `dry_run=true`, which is when the argument will be [converted accordingly](https://github.com/gitpython-developers/GitPython/blob/master/git/cmd.py#L890). The details on why this works [can be found here](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly).

The workaround is certainly a sneaky one :) - but I think with the information above there should be no need for a fix.
If that didn’t help or work, please let me know and we can reopen the issue.
