### ISSUE TITLE
Repo.clone_from to take target branch

### ISSUE THREAD

**Issue by nagapavan** [gitpython-developers/GitPython#760]
GIT clone through CLI allows to specify target branch to be checked out - which is optional.

Syntax:
`git clone -b develop git@github.com:user/myproject.git`

Can Repo.clone_from() be updated to support this?

**Comment by Byron** [comment]
Yes, I think you can just pass additional options as `kwargs`, such as in `Repo.clone_from(url, b="develop")`. If that doesn't work, you might also try the long argument name in a similar fashion.

If that doesn't work for you, please let me know here.

**Comment by nagapavan** [comment]
Thanks @Byron.
