### ISSUE TITLE
Getting object 'Repo' has no attribute 'int' error

### ISSUE THREAD

**Issue by apaandiyan** [gitpython-developers/GitPython#766]
Problem Description - I am trying to get log files of branches in a Repository and write it to a file
Code - 
       
     if self.work_dir.exists():
                shutil.rmtree('*/GitHubTasks')

            Repo.clone_from(url='https://' + self.authorization_token.replace('token ', '') + 
            '@github.com/FileTrek/' +self.repository_name + '.git', to_path=self.work_dir)
            Repo.git.int(self.work_dir)
            Repo.git.checkout(self.source_branch_name

            f = open('source_branch_log.txt', 'w')
            f.write(Repo.git.log())
            f.close()

            Repo.git.checkout(self.new_branch_name)
            f = open('new_branch_log.txt', 'w')
            f.write(Repo.git.log())
            f.close()

**Comment by Byron** [comment]
The problem here that `.git` only exists on a `Repo` instance, not on the class.
If you use the result of `Repo.clone` like `repo = Repo.clone(...)` and go ahead with `repo.git.anything(...)`, it will work as you expect.
