### ISSUE TITLE
Why the hooks are executed manually?

### ISSUE THREAD

**Issue by KOLANICH** [gitpython-developers/GitPython#770]
https://github.com/gitpython-developers/GitPython/blob/0857d33852b6b2f4d7bc470b4c97502c7f978180/git/index/base.py#L941

**Comment by Byron** [comment]
The short answer is: hooks don't execute themselves.

Can you elaborate and explain what the underlying problem is?
Even though I am closing the issue as the questions seems sufficiently well answered, please feel free to comment nonetheless.

**Comment by KOLANICH** [comment]
I mean why don't we rely on git to call them?

**Comment by Byron** [comment]
If you wish to do that, you can. It's a great question to ask though, as it might be unclear what the benefits of using this library are. I guess primarily it's the pythonic interface to git, which appears hard to achieve while relying solely on the `git` program.
