### ISSUE TITLE
Help: how do I amend a commit?

### ISSUE THREAD

**Issue by timur-tabi** [gitpython-developers/GitPython#772]
I've searched all over Google for an answer, but I couldn't find anything, and so I have to ask here.  How do I amend a commit in GitPython? I have this code:

```
parent = commit.parents[0]
repo.git.checkout(parent)
message = commit.message + 'Change-Id: I%x' % random.getrandbits(4 * 40)
new_commit = repo.index.commit(message)
```

But all this does is create an empty commit.  What I want to do is take an existing commit and amend it with only a new description.

**Comment by Byron** [comment]
There is no such capability in GitPython. However, you could just resort to using the command-line with `repo.git.commit("--amend", ...)` or implement it yourself by creating a new commit, to which the current HEAD is forcefully reset.
I am closing this issue, but please feel free to add more comments or notes as you see fit.
