### ISSUE TITLE
Reading and writing global configuration parameters

### ISSUE THREAD

**Issue by andy-shev** [gitpython-developers/GitPython#775]
There is no way to get global configuration parameters without `Repo` object.
`config_reader()` **must** be repository independent. So does `config_writer()` and accompanying methods.

Simplest (and ugly) hack is to allow `path=None` in `Repo()`.

**Comment by Byron** [comment]
Thanks for letting us know! Out of the back of my head, no simpler solution comes to mind.

**Comment by andy-shev** [comment]
Better workaround if anybody is interested.

    import git
    import os

    class GitConfig(git.Repo):
        def __init__(self, *args, **kwargs):
            #
            # Work around the GitPython issue #775
            # https://github.com/gitpython-developers/GitPython/issues/775
            #
            self.git_dir = os.path.join(os.getcwd(), ".git")
            git.Repo.__init__(self, *args, **kwargs)

Usage:

    r = GitConfig().config_reader()
    print (r.get_value('user', 'name')

**Comment by bthayer2365** [comment]
@andy-shev Thank you! Solution worked for me too.

@Byron Are you open to PRs? It seems like this is mostly a matter of where to put the relevant code. If I figure out something logical, can I submit a PR and we discuss from there?

**Comment by Byron** [comment]
@bthayer2365 Absolutely, GitPython runs on PRs! Thanks for your participation :).
