### ISSUE TITLE
Add repo.archive_all()

### ISSUE THREAD

**Issue by rubenwardy** [gitpython-developers/GitPython#777]
`git archive` only does the root repo, whereas `git archive-all` also does submodules

**Comment by Byron** [comment]
As described in the [codes documentation](https://github.com/gitpython-developers/GitPython/blob/1ca25b9b090511fb61f9e3122a89b1e26d356618/git/repo/base.py#L990) you are able to pass arbitrary arguments to `git archive` using `kwargs`.
This would allow you to pass additional arguments which may be helpful.
There is no `git archive-all` command.
Including submodules in the `archive` method would be a feature request which requires you to put much more work into the issue you file to allow others to pick that up.
Even though I am closing the issue, please feel free to comment as you see fit.
