### ISSUE TITLE
how do I get sha key for any repository' file.

### ISSUE THREAD

**Issue by yilmazedis** [gitpython-developers/GitPython#778]
I want to access sha key for any repository' files individually.

![gitpython](https://user-images.githubusercontent.com/15719990/42518100-d2ff8426-8469-11e8-88fd-ba1733387e97.PNG)

As you can see. There are a file structure and that is include a .git directory which I created with gitpython. I can get repository sha key for represent all files as follow;
```python

from git import Repo

repo = Repo("graph/features")
master = repo.head.reference
print(master.commit.hexsha)
```

My question is that I want to generate sha key for any file such as file2.txt. Are there any method to realize that. I am sorry, I am new about using gitPython.

**Comment by Byron** [comment]
Please have a look at how the [tree object is used in the tutorial](https://gitpython.readthedocs.io/en/stable/tutorial.html) - just search for `.tree`. It provides access for recursive traversal of git trees with access to all meta-data, among which is the SHA1 hash.
Even though I am closing this issue, please feel free to keep commenting as you see fit.
