### ISSUE TITLE
How to specify directory for checkout?

### ISSUE THREAD

**Issue by jmarshall9120** [gitpython-developers/GitPython#807]
How do you simulate the following checkout in GitPython:

```
> git fetch <remote> <branch>
> git checkout <remote>/<branch> -- relative/path/to/file/or/dir
```

I've been experimenting and looking through the code/docs, but this has bee kind of slammed.  How is the '--' flag simulated?  I have an open StackOverflow question here: 
https://stackoverflow.com/questions/53177140/gitpython-to-pull-a-specific-directory

I've been fooling around with this for hours but it seems to be well outside the bounds of the documentation.

**Comment by Byron** [comment]
Do you think that [using git directly](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly) could work for you?

**Comment by jmarshall9120** [comment]
Yeah, if the option to specify a path isn't in the "objects" for the api, then that's the answer.  It looks like the use git directly bit though, requires keywords.  What keyword would be equivalent to '--'?

**Comment by Byron** [comment]
It would be the literal string '--' as argument to `repo.git(...)`. Since
this is not obvious from the docs, I would be glad if you could contribute
a piece that would have helped you :).

**Comment by jmarshall9120** [comment]
Okay, so i didn't realize the git object would pass literals.  Here have a look at this.

This GitPython doesn't work:
```
_git = repo.git()
_git.checkout("Dev/master", "-- 'ETLApp'")
```

This git from the command line does work:
`git commit Dev/master -- "ETLApp"`

strangely look at the error from GitPython.  I bolded the part where the cmd equivalent is:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\jmarshall\source\repos\MediaDesignGroup\ETLApp\ETLApp\ETLAppEnv_3_7\lib\site-packages\git\cmd.py", line 548, in <lambda>
>     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
>   File "C:\Users\jmarshall\source\repos\MediaDesignGroup\ETLApp\ETLApp\ETLAppEnv_3_7\lib\site-packages\git\cmd.py", line 1014, in _call_process
>     return self.execute(call, **exec_kwargs)
>   File "C:\Users\jmarshall\source\repos\MediaDesignGroup\ETLApp\ETLApp\ETLAppEnv_3_7\lib\site-packages\git\cmd.py", line 825, in execute
>     raise GitCommandError(command, status, stderr_value, stdout_value)
> git.exc.GitCommandError: Cmd('git') failed due to: exit code(129)
**>   cmdline: git checkout Dev/master -- 'ETLApp'**
>   stderr: 'error: unknown option ` 'ETLApp''
> usage: git checkout [<options>] <branch>
>    or: git checkout [<options>] [<branch>] -- <file>...
> 
>     -q, --quiet           suppress progress reporting
>     -b <branch>           create and checkout a new branch
>     -B <branch>           create/reset and checkout a branch
>     -l                    create reflog for new branch
>     --detach              detach HEAD at named commit
>     -t, --track           set upstream info for new branch
>     --orphan <new-branch>
>                           new unparented branch
>     -2, --ours            checkout our version for unmerged files
>     -3, --theirs          checkout their version for unmerged files
>     -f, --force           force checkout (throw away local modifications)
>     -m, --merge           perform a 3-way merge with the new branch
>     --overwrite-ignore    update ignored files (default)
>     --conflict <style>    conflict style (merge or diff3)
>     -p, --patch           select hunks interactively
>     --ignore-skip-worktree-bits
>                           do not limit pathspecs to sparse entries only
>     --ignore-other-worktrees
>                           do not check if another worktree is holding the given ref
>     --recurse-submodules[=<checkout>]
>                           control recursive updating of submodules
>     --progress            force progress reporting
> '


any ideas?

**Comment by Byron** [comment]
What about `_git.checkout("Dev/master", "--",  "ETLApp")`?

**Comment by jmarshall9120** [comment]
Wow, that worked.  What was the hang up?  It must be a popen thing huh?  I've been tracing the stack, but hadn't figured this out myself.  Yet.  I appreciate the help, i'll suggest changing the docs to:

1. show a couple cmd equivalents of passed in commands.
2. say in the remotes section that checking out anything besides a header requires directly using git.

Let me know if that works for you.

**Comment by Byron** [comment]
I am closing this issue as by now it would have become clear how to workaround the limitations of the GitPython API.

@jmarshall9120 Thanks for the suggestions, any PR that improves the documentation is very welcome.
