### ISSUE TITLE
OSError referencing committed_date

### ISSUE THREAD

**Issue by mrlesmithjr** [gitpython-developers/GitPython#809]
Anyone else seen this by chance? Using the code block below on macOS or Linux I do not see this error, but on a Windows/Cygwin environment I get the following error:
```bash
INFO: Ignored error after process had died: OSError(3, 'No such process')
```
I originally thought it was coming from the time conversion but it throws the same error just printing `headcommit.committed_date`. This is being seen across different installations so not machine specific. Any thoughts or etc. would be much appreciated.

```python
def intro():
    """Display introduction header for screens."""
    # Set path to python menu driven automation tool
    repo_path = os.getcwd()
    # Setup repo
    repo = git.Repo(repo_path, search_parent_directories=True)
    # Ensure we are not working from a bare repo
    assert not repo.bare
    # Set the latest commit of repo head
    headcommit = repo.head.commit
    # Set release date to be presented on screen
    release_date = time.strftime(
        '%a, %d %b %Y %H:%M', time.gmtime(headcommit.committed_date))
    print 'Release date: {}\n'.format(release_date)
```

**Comment by Byron** [comment]
I think this issue can be ignored, it's just an [INFO statement indicating the git process was already shut down](https://github.com/gitpython-developers/GitPython/blob/3e1fe7f6a83633207c9e743708c02c6e66173e7d/git/cmd.py#L380).

It doesn't appear to affect the correctness of the results.
