### ISSUE TITLE
hooks

### ISSUE THREAD

**Issue by cancerhermit** [gitpython-developers/GitPython#81]
repo.index.commit("commit") not run hooks

**Comment by Byron** [comment]
Please note that even though commit hooks are implemented now, they are only tested and verified to work on posix.
If you need it on windows, please let me know what kind of hook you are running there, just because I am unsure how any script is run on windows by git at all.

**Comment by Byron** [comment]
You can see how this was implemented [on youtube](http://youtu.be/nm56OEG7RwY)
