### ISSUE TITLE
NameError: name 'git' is not defined

### ISSUE THREAD

**Issue by hick** [gitpython-developers/GitPython#811]
how can I debug something? 

it's sth like this issue, while I think maybe different:   https://github.com/gitpython-developers/GitPython/issues/107

![image](https://user-images.githubusercontent.com/38886/48928793-51302580-ef1d-11e8-8a3d-0ea6240614f7.png)

text version:

D:\hick\python>python git-.py
Traceback (most recent call last):
  File "git-.py", line 6, in <module>
    repo = git.Repo(r'D:\hick')
NameError: name 'git' is not defined

D:\hick\python>pip show GitPython
Name: GitPython
Version: 2.1.11
Summary: Python Git Library
Home-page: https://github.com/gitpython-developers/GitPython
Author: Sebastian Thiel, Michael Trier
Author-email: byronimo@gmail.com, mtrier@gmail.com
License: BSD License
Location: d:\program\python35\lib\site-packages
Requires: gitdb2

D:\hick\python>cat git-.py
'''
操作 git 的演练
'''
from git import Repo

repo = git.Repo(r'D:\hick')

print(repo.bare)

D:\hick\python>python -V
Python 3.5.4

**Comment by Dotrar** [comment]
if you `import Repo` from `git` you are importing Repo, not git.

just remove `git.`

**Comment by Byron** [comment]
I think @Dotrar has provided the answer to this question.
