### ISSUE TITLE
repo.index.add -> check if input is a list

### ISSUE THREAD

**Issue by MarcelBeining** [gitpython-developers/GitPython#813]
For ~~stupid~~ people like me:
Could you please add a check if the input to `repo.index.add(...)` is a list, and not a string?
It took me a while to find out that this was the real error behind:

> ValueError: Absolute path '\\' is not in git repository at 'C:\\Users\\xxx\\yyy\\zzz'

:-)

**Comment by Byron** [comment]
What I hear is that if this function is passed a string, the result is unexpected as it is treated as a list. Instead it should check if a singular item was passed, being either a string or one of the other supported objects, and put it into a list automatically.

A PR which implements this would be appreciated.
