### ISSUE TITLE
git.show raises an error when a file is passed as the second parameter

### ISSUE THREAD

**Issue by julianvargasalvarez** [gitpython-developers/GitPython#82]
Hey if I perform:

`repo.git.show('4aeba658ca4bb8dba3d7204b2931c7cb03d5be36', 'hello.txt')`

it will raise an error when 'hello.txt' no longer exists. If I go to the terminal and perform:

`git show '4aeba658ca4bb8dba3d7204b2931c7cb03d5be36' hello.txt`

I get the same error but if I put two dashes, it works

`git show '4aeba658ca4bb8dba3d7204b2931c7cb03d5be36' -- hello.txt`

Notice: this happens when `hello.txt` was commited before and it is part of the history but if it does not exist in the working directory the error will be thrown unless we put two dashes before the filename

**Comment by Byron** [comment]
By now, I do believe there is an easy workaround, as you should be able to just add the double-dash as argument, such as follows:
```python
repo.git.show('4aeba658ca4bb8dba3d7204b2931c7cb03d5be36', '--', 'hello.txt')
```
