### ISSUE TITLE
AttributeError: 'PushInfo' object has no attribute 'name'

### ISSUE THREAD

**Issue by tardis4500** [gitpython-developers/GitPython#820]
A simple call to:
                   result = self._client.remotes.origin.push(**args)
                    print(result.summary)
results in:
Traceback (most recent call last):
  File "C:\Users\jsmith\Envs\halpy\lib\site-packages\halpy\cms.py", line 623, in checkin_files
    print(result.summary)
  File "C:\Users\jsmith\Envs\halpy\lib\site-packages\git\util.py", line 883, in __getattr__
    if getattr(item, self._id_attr) == attr:
AttributeError: 'PushInfo' object has no attribute 'name'

**Comment by Byron** [comment]
Which version of GitPython are you using? Could you also provide a more self-contained example on how to reproduce the issue? Maybe `**args` makes all the difference.
Thank you

**Comment by tardis4500** [comment]
I'm using 2.1.11 and the following will reproduce the error.

`import git
git_client = git.Repo.clone_from(some_repo, 'test_clone')
result = git_client.remotes.origin.push()
print(result.summary)`

**Comment by Byron** [comment]
Thanks a lot! I could reproduce the issue.

**Comment by metakernelteam** [comment]
I have a similar problem, when printing result.summary:


`AttributeError: 'PushInfo' object has no attribute 'push_infos'`

This is the full stack:

```  File "/data/users/leit/fbsource/fbcode/buck-out/dev/gen/kernel/ksyncer/ksyncer#link-tree/kernel/ksyncer/push.py", line 43, in push_to_remote_repo
    print(pushinfo.summary)
  File "/data/users/leit/fbsource/fbcode/buck-out/dev/gen/kernel/ksyncer/ksyncer#link-tree/git/util.py", line 998, in __getattr__
    if getattr(item, self._id_attr) == attr:
    
```

**Comment by Asmokin11** [comment]
I am also facing the same error as @metakernelteam when trying to print the summary

**Comment by Byron** [comment]
I think it would be good to open a new issue for this, as that would contain instruction to reproduce a possibly new issue that looks similar. All that is under the assumption that this issue was actually fixed a couple of years ago - otherwise please do feel free to add instructions here for a reproduction to have this issue reopened instead. Thank you.
