### ISSUE TITLE
Equivalent to "git tag --contains" in gitpython 

### ISSUE THREAD

**Issue by HuKeping** [gitpython-developers/GitPython#821]
Does gitpython support git command like `git tag --contains`, `git tag --points-at`, etc.

**Comment by Byron** [comment]
Even though I don't think GitPython has that functionality built-in, one can always [resort to using git directly](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly).
If this doesn't answer your question, please let us know in the comments.
