### ISSUE TITLE
Travis CI tests fail when dist: xenial is used instead of dist: trusty

### ISSUE THREAD

**Issue by cclauss** [gitpython-developers/GitPython#827]
Why does __git.test.test_remote.TestRemote__ fail in all versions of Python on Travis CI when __dist: xenial__ is used instead of the Travis CI default of __dist: trusty__?  For Python >= 3.7 it is required that Travis runs on Xenial: https://github.com/gitpython-developers/GitPython/blob/master/.travis.yml#L11-L14

https://travis-ci.org/gitpython-developers/GitPython/builds/481862926

**Comment by Byron** [comment]
Even though I am as puzzled as you are, that particular test uses the git daemon to verify remote operation, without leaving the host. Possibly the git-daemon provided by this distro operates differently enough to make the test fail.

Something I could imagine is to just disable it, for now, for the python versions that require it. I say this under the assumption that nobody has the time to figure what's really going on though.

**Comment by cclauss** [comment]
OK.  I will add a PR for a __@pytest.mark.xfail()__

**Comment by jeking3** [comment]
The root cause and fix is buried in #826 right now.
