### ISSUE TITLE
Use of environment vars in paths is deprecated, Warning in Python 3.7

### ISSUE THREAD

**Issue by kamadoatfluid** [gitpython-developers/GitPython#832]
```
warnings.warn("The use of environment variables in paths is deprecated" +
/usr/local/lib/python3.7/dist-packages/git/repo/base.py:127: UserWarning: The use of environment variables in paths is deprecated for security reasons and may be removed in the future!!
```

However, I'm passing absolute paths to the Repo class, this creates a lot of warning messages in the script output

**Comment by Byron** [comment]
Can you verify the paths are indeed not containing any [of the characters the logic looks for](https://github.com/gitpython-developers/GitPython/blob/77e47bc313e42f9636e37ec94f2e0b366b492836/git/repo/base.py#L127)? Namely `%` and `$`.
