### ISSUE TITLE
Feature request - Alternative to local disk

### ISSUE THREAD

**Issue by bodegus** [gitpython-developers/GitPython#834]
It seems that git only works with local disk - I built a crawler to extract histories from every repo (full commit history/diffs/etc) and some repos/orgs can get in the many gbs in size.  It would be helpful to be able to use S3 or memory disk within python without doing something lower level.

As a work around I cache a repo locally for analysis and pull/push a cached version I store in s3.

**Comment by Byron** [comment]
Thanks for letting us know! It sounds like a great idea, and since GitPython is in maintenance mode, new features are only accepted in the form of PRs.
Thanks for your understanding.
