### ISSUE TITLE
Request for type support

### ISSUE THREAD

**Issue by pcd1193182** [gitpython-developers/GitPython#838]
As of PEP 484, python supports adding types to variables to improve correctness and help the development process. As of PEP 561, there is now a standardized way to include type information with packages. It would be useful for users of the package who are taking advantage of this new feature to have type information from the gitpython package, but it would also add some amount of maintenance burden to the developers having to keep these types accurate and up to date. I was wondering if this is something you would consider doing, or if users (including myself) should have our typecheckers ignore the git module (or stub out important functions ourselves) going forwards.

**Comment by Byron** [comment]
Thanks for the heads-up! Unfortunately, as GitPython is in maintenance mode, it cannot accept feature requests unless these are submitted as PR.

Would GitPython accept such a PR? Personally I don't know how python is these days and how the tradeoff is between adding types, which I assume are ignored by python itself, and maintaining them. My stance here is conservative, and if in doubt, keep things as they are. Other contributors and maintainers can chime in and if the majority is for such a PR, I won't be in the way.
