### ISSUE TITLE
push timeout or ssh user/pass dialog detect

### ISSUE THREAD

**Issue by cancerhermit** [gitpython-developers/GitPython#84]
remote.push(repo.head.reference) is freezing then git push ask user&pass

after gists update 
gist.github.com is now 204.232.175.94 (old ip is 207.97.227.243).
add ssh connection check to prevent this bug in future:

from envoy import run
host =="gist.github.com" # get from push url with urlparse
assert run("ssh -T git@" % host).status_code==1 # ok

**Comment by Byron** [comment]
I am not sure if this is still an issue, as gitpython will not open stdin when calling git-push. Underneath git will still use ssh and possibly trigger a freeze in case it opens stdin (which it shouldn't as it's not connected to a shell).
Under these circumstances ssh should just prevent the connection, as the user cannot be asked.

However, as I couldn't reproduce it, the hanging issue might still occour, and right now I don't know if gitpython is able to handle this. There are ways to tell git [which options to pass to ssh](http://stackoverflow.com/questions/7772190/passing-ssh-options-to-git-clone), and I believe these would have to be configured by the user.

However, if this issue reoccours and you can help me to reproduce it, I will be happy to make git-python impervious to it, if at all possible
