### ISSUE TITLE
Equivalent to "git tag --merged" in gitpython

### ISSUE THREAD

**Issue by regisz** [gitpython-developers/GitPython#843]
How can I do in gitpython the `git tag --merged` command?
I would like to get tags which are reachable from the actual (or other) branch.

**Comment by elpiekay** [comment]
```
import git

r = git.Repo('path/to/foo')
output = r.git.tag(merged=True)
tags = output.split('\n')
```

**Comment by regisz** [comment]
yes, I know this solution (git.Repo.git). But, in this case a subshell is created, and I would like to avoid this.

**Comment by Byron** [comment]
GitPython does not support more complex queries on tags natively. In that case, one will have to resort to using the git command.
I am closing the issue as part of Q&A, please feel free to keep commenting for clarification.
