### ISSUE TITLE
Please merge #837?

### ISSUE THREAD

**Issue by jeking3** [gitpython-developers/GitPython#845]
Although the PR build "failed", the linux side is fixed.  This is an improvement.  People might be skipping over it when they see the red "X", but it should be merged.  I have more changes to submit following this one.  Thanks.

#837

**Comment by Byron** [comment]
Sorry for the delays, it will be merged, hopefully this weekend. Thus far I
didn't spend any time on GitPython maintenance.

**Comment by jeking3** [comment]
Are you the only committer for all the gitpython-developers projects?  That's a lot to cover!

**Comment by jeking3** [comment]
Reminder?

**Comment by stsewd** [comment]
https://github.com/gitpython-developers/GitPython/pull/837 was already merged, this issue can be closed :)
