### ISSUE TITLE
Add support for git cherry

### ISSUE THREAD

**Issue by sffc** [gitpython-developers/GitPython#846]
*git cherry* returns a list of commit hashes with a prefix `+` or `-` to indicate whether the commit has an equivalent cherry-pick commit in a sibling branch.  I would like to be able to iterate over the output of `git cherry <ref1> <ref2>` similar to how I can use iter_commits to iterate over the output of `git log <ref1>..<ref2>`.

We would like this feature to use in ICU tooling: [ICU-20444](https://unicode-org.atlassian.net/browse/ICU-20444)

**Comment by sffc** [comment]
We would like this feature to use in ICU tooling: [ICU-20444](https://unicode-org.atlassian.net/browse/ICU-20444)

**Comment by Byron** [comment]
Thanks a lot! This does indeed sound useful! However, since GitPython is in maintenance mode, it cannot accept new features requests unless these are submitted as implementation via PR.
Thanks for your understanding.

**Comment by srl295** [comment]
Oh hi @sffc 

By the way, in digging into https://github.com/gitpython-developers/GitPython/blame/30387f16920f69544fcc7db40dfae554bcd7d1cc/git/objects/submodule/base.py#L847 I discovered that in 'command' mode it's possible to do this:

```python
    print (repo.git.cherry("origin/maint/maint-37", "origin/maint/maint-38","6962fb4ad25ce89645211c13bbd2cb1f52a62861"))
```

this is at least a work around.

**Comment by srl295** [comment]
@Byron the task may only be to document `Repo.git.cherry()` here?

**Comment by Byron** [comment]
Indeed, that could be it. Since it's a program invocation, it could possibly be an example in the "Using git directly" section of the tutorial.

Alternatively, one could always open a new section with a lot of useful, otherwise implicit features that are often requested.
