### ISSUE TITLE
Add instr option for Repo.git commands

### ISSUE THREAD

**Issue by sents** [gitpython-developers/GitPython#850]
Some git functions (e.g. git hash-object) can take input from stdin, they often take an --stdin flag to explicitly enable this.
Currently I can find no way to make this work with Repo.git commands.
Ideally for me such an instr option would also work with StringIO streams, not just files.

Right now I have to use subprocess.run for exactly this one thing and everything would look much more beautiful if I could use gitpython for everything.  Thanks for this module!

**Comment by elpiekay** [comment]
foo.py
```
import git

# python2

r = git.Repo('path/to/foo')
s = r.git.hash_object(stdin=True)
print s
```

echo "hello world" | python foo.py
3b18e512dba79e4c8300dd08aeb37f8e728b8dad

**Comment by Byron** [comment]
With this syntax you are able to connect any kind of stream or file-like object to said stdin.

```
r.git.hash_object(istream=fh, stdin=True))
```

I hope that answers the question sufficiently.
