### ISSUE TITLE
repo.index.diff("HEAD", create_patch=True) always empty

### ISSUE THREAD

**Issue by jadinm** [gitpython-developers/GitPython#852]
I am using GitPython v2.1.11 with Python 3.6. My git version is 2.17.1.

I see inconsistent behavior of the diff method of a repo index if create_patch option set to True.
I am running the following script in a git repository with staged and unstaged changes.

```python
from git import Repo

repo = Repo(".")

print(repo.index.diff("HEAD"))
print(repo.index.diff("HEAD", create_patch=True)) # Problem here

print(repo.index.diff(None))
print(repo.index.diff(None, create_patch=True))
```

But it prints:
```
[<git.diff.Diff object at 0x7fd54c328678>, <git.diff.Diff object at 0x7fd549e405e8>, <git.diff.Diff object at 0x7fd54c328558>]
[]
[<git.diff.Diff object at 0x7fd54c328678>]
[<git.diff.Diff object at 0x7fd54c328678>]
```

Somehow, the diff is empty if I set `create_patch` to True and the first argument to anything but `None`.
Do you know why it happens ?

**Comment by jadinm** [comment]
I found out the problem.

When running ``repo.index.diff("HEAD", create_patch=True)``, the command used is:
```bash
$ git diff -R <reference-hash> --cached --abbrev=40 --full-index -M -p --no-color
```

And this produces:
```
diff --git b/other_file.txt a/other_file.txt
deleted file mode 100644
index d733472942281cd2f19f52ab4b5ddecb4151bb72..0000000000000000000000000000000000000000
--- b/other_file.txt
+++ /dev/null
@@ -1 +0,0 @@
-Other file
```

But the regex that is used for parsing (i.e., ``Diff.re_header``) expects ``a/other_file.txt`` to be before ``b/other_file.txt``.
The inversion is due to the "-R" flag in the command line.

-------------------
A temporary fix for my use of GitPython is to set R to True to prevent the reversal.

```python
print(repo.index.diff("HEAD", create_patch=True, R=True))
```

**Comment by Byron** [comment]
Thanks a lot for sharing the issue, and for posting the workaround here as well!

**Comment by can-taslicukur** [comment]
I am using version 3.1.42 and experiencing this issue currently.

```python
from git import Repo

repo = Repo(".")
print(repo.index.diff("HEAD"))
print(repo.index.diff("HEAD", create_patch=True))
```

prints

```python
[<git.diff.Diff object at 0x10cbb08b0>]
[]
```
