### ISSUE TITLE
Get different commits between 2 branches

### ISSUE THREAD

**Issue by nttri** [gitpython-developers/GitPython#861]
In git have a command to get list of which commits in one branch aren't in the other like this:
`git cherry <branch-A> <branch-B>`

So is there any ways to get that result in GitPython? Please help me.

**Comment by elpiekay** [comment]
```
import git

r = git.Repo('path/to/foo')
s = r.git.cherry('branch-A', 'branch-B')
# parse s
```

**Comment by Byron** [comment]
Thanks, @elpiekay !
