### ISSUE TITLE
Git.log() with pretty option returns email ids instead of their names.

### ISSUE THREAD

**Issue by HEMA-MATHAVAN** [gitpython-developers/GitPython#863]
The following command returns author and commiter email ids instead of their names.i am using version 2.1.11.

Command
git.log('--pretty=%H %an %cn %s','--before=some_date',filename)

Output
677cdde6477cc92b7779d4239df66d6c8ced7aba 
bienvenu%nventure.com 
bienvenu%nventure.com 
fix 103732, sending unsent messages doesn't set replied/forwarded status on original msg, r/sr=mscott

**Comment by HEMA-MATHAVAN** [comment]
guys could someone reply...

**Comment by the-c0d3br34k3r** [comment]
It seems to work for me. I'm getting the name of the committer.
What does `git log 789f530f927887d0e732eb75e9e20e0b9749db41 -n 1` look like?``

**Comment by HEMA-MATHAVAN** [comment]
This is how it looks, still no author name.

[root@localhost ehan-mozilla]# git log 677cdde6477cc92b7779d4239df66d6c8ced7aba -n 1
commit 677cdde6477cc92b7779d4239df66d6c8ced7aba
Author: bienvenu%nventure.com <bienvenu%nventure.com>
Date:   Wed Jul 23 21:53:05 2003 +0000

    fix 103732, sending unsent messages doesn't set replied/forwarded status on original msg, r/sr=mscott

**Comment by the-c0d3br34k3r** [comment]
This is not an issue with Git or jGit.
Your commit has the email address in both the fields (author name and email ID).
A commit with a proper author name specified, looks like this:

commit ca82a6dff817ec66f44342007202690a93763949
Author: Scott Chacon <schacon@gee-mail.com>
Date:   Mon Mar 17 21:52:11 2008 -0700

    changed the version number

**Comment by jeking3** [comment]
Agreed; someone set their git user.name to their email address in that case (or perhaps never set their git user.name at all).

**Comment by HEMA-MATHAVAN** [comment]
The whole repository gives the same result. i felt the .mailmap file was missing.i have raised a issue there too. Thanks for helping out.
