### ISSUE TITLE
blob.path  error when git config core.quotepath = true

### ISSUE THREAD

**Issue by StevenKangWei** [gitpython-developers/GitPython#865]
blob.path  error when git config core.quotepath = true

**Comment by StevenKangWei** [comment]
one of solution is set quotepath to false:

```python
with repo.config_writer() as writer:
    writer.set_value('core', 'quotepath', 'false')
```

**Comment by Byron** [comment]
Thanks for letting me know. Even though one can turn quotepath off, it seems to be a workaround for a real issue (even though I didn't reproduce it). Please feel free to reopen if you agree.

**Comment by StevenKangWei** [comment]
> Thanks for letting me know. Even though one can turn quotepath off, it seems to be a workaround for a real issue (even though I didn't reproduce it). Please feel free to reopen if you agree.

If some filename or directory name contain UNICODE character, blob.path is not exact path.
