### ISSUE TITLE
os.getlogin() - Inappropriate ioctl for device when running in Docker container

### ISSUE THREAD

**Issue by mindej** [gitpython-developers/GitPython#878]
I am getting an error in Docker container `OSError: [Errno 25] Inappropriate ioctl for device` when running `os.getlogin()`

Here is my dlocker file: 
```
FROM python:3.6.8
ARG APP_USER=python
RUN useradd --system --no-create-home --shell /sbin/nologin $APP_USER
COPY . /app
RUN chown -R $APP_USER:$APP_USER /app
WORKDIR /app
RUN pip install  -r requirements.txt
USER $APP_USER
CMD python app.py
```

**Comment by Byron** [comment]
I am afraid without the actual app that triggers the issue, it can't be reproduced. Even if it was the case, `os.getlogin()` failing must be unrelated to GitPython.
Please feel free to reopen once there is reproducible evidence that this is related to GitPython. Thank you.
