### ISSUE TITLE
Inconsistent behaviour from merge-base

### ISSUE THREAD

**Issue by eKoopmans** [gitpython-developers/GitPython#880]
Hi, thanks for the great project! I've run into some inconsistent behaviour with `merge_base`, though it could be a misunderstanding on my end.

When finding the `merge_base` between two separate repos, comparing branches gives the wrong base (not a common ancestor), while comparing those branches' commits gives the correct base. I have been using two simple repos, where `repo1` is just a few commits ahead of `repo2`. In the example below, the first merge_base returns the HEAD of repo1 (which is ahead of repo2), while the second merge_base returns the HEAD of repo2 (which is correct):

```python
from git import Repo

# Setup repos and branch objects.
repo1 = Repo('./repo1')
repo2 = Repo('./repo2')
master1 = repo1.branches['master']
master2 = repo2.branches['master']

# Returns incorrect base (not a common ancestor).
badBase = repo1.merge_base(master1, master2)[0]

# Returns the correct base (is a common ancestor).
goodBase = repo1.merge_base(master1.commit, master2.commit)[0]
```

For now simply using the commits seems like a working solution, but I wanted to check if there's a deeper issue, or if I may be using it incorrectly. Thanks!

**Comment by eKoopmans** [comment]
Looks like using `.commit` wasn't a good solution either, it doesn't work if the commit isn't in `repo1`. I've fallen back to using a remote:

```python
repo1 = Repo('./repo1')
remote = repo.remote('repo2')
remote.fetch()
goodBase = repo1.merge_base(repo1.refs['master'], remote.refs['master'])[0]
```

I was hoping to get the merge-base without having to fetch the remote, but maybe that's simply not possible in git.

**Comment by elpiekay** [comment]
It's not a bug.

Call stack:
```
1    repo1.merge_base(master1, master2)
```
```
2    lines = self.git.merge_base(*rev, **kwargs).splitlines()
```
https://github.com/gitpython-developers/GitPython/blob/master/git/repo/base.py#L545
```
3    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
```
https://github.com/gitpython-developers/GitPython/blob/master/git/cmd.py#L545
```
4    ext_args = self.__unpack_args([a for a in args if a is not None])
````
https://github.com/gitpython-developers/GitPython/blob/master/git/cmd.py#L987
```
5    return [str(arg_list)]
```
https://github.com/gitpython-developers/GitPython/blob/master/git/cmd.py#L919

`master1` and `master2` are objects of `git.refs.head.Head`. When they are converted to `str`, `git.refs.head.Head.__str__` is called, https://github.com/gitpython-developers/GitPython/blob/master/git/refs/reference.py#L48. Both return `master`.

So `repo1.merge_base(master1, master2)` is equivalent to `repo1.merge_base('master', 'master')`, and internally calls the git command `git --git-dir=repo1/.git merge-base master master`. The 2 `master`s of `repo1` point to the same head, so the return value is the head commit, `master` itself.

For `repo1.merge_base(master1.commit, master2.commit)`, it calls the git command `git --git-dir=repo1/.git merge-base $commit1 $commit2` and the expected commit is returned. As `master1` is ahead of `master2`, `repo1` has the objects of `master2`.

**Comment by Byron** [comment]
I agree with @elpiekay
