### ISSUE TITLE
git.exc.InvalidGitRepositoryError for GitPython v2.1.11

### ISSUE THREAD

**Issue by weijiafeng** [gitpython-developers/GitPython#881]
Hi Authors,

I have installed the latest GitPython (v2.1.11), however I faced the git.exc.InvalidGitRepositoryError: /Users/maggiefeng/reward-learning-rl/softlearning. I've tried various methods as described in previous Issues, however it still didn't work. And I am aware the previous solutions refer to older versions of GitPython, the problem of which should be fixed in this latest version.

I would like to know where the problem lies, many thanks!

My environment is:
MacOS Mojave version 10.14.1
Python 3.6.5

The error screenshot:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/40955107/59113477-ae4e6e80-8977-11e9-81f4-67b099cabe85.png">

**Comment by elpiekay** [comment]
What's the value of `'{}/..'.format(path)` ?

**Comment by Byron** [comment]
I am closing this issue as there is not enough information to reproduce the issue. Please feel free to reopen once more information is provided. Thanks for your understanding.
