### ISSUE TITLE
Wrong change_type for diff('HEAD')

### ISSUE THREAD

**Issue by aruehl** [gitpython-developers/GitPython#882]
I've seen Issue #531 and #534, but this failure exists further on.

change_type, new_file and deleted_file have wrong values.

It seems for me, that the detection for added and removed files are interchanged.

Here is what I've done:

```
$ git init
$ echo "removed" > removed.txt
$ git add removed.txt
$ git commit -m "removed.txt added"
$ echo "added" > added.txt
$ git add added.txt
$ git rm removed.txt
$ git status -s
A  added.txt
D  removed.txt
$
```

executing the script
```
from git import Repo, IndexFile
repo = Repo(".")
for diff_item in repo.index.diff("HEAD"):
        print(diff_item.a_path)
        print(diff_item.change_type)
        print(diff_item.new_file)
        print(diff_item.deleted_file)
        print()
```
```
$ python3 difffailure.py
added.txt
D
False
True

removed.txt
A
True
False

$ python3 --version
Python 3.6.6
$ python3 -m pip show GitPython
Name: GitPython
Version: 2.1.11
[...]
```

**Comment by elpiekay** [comment]
I don't think it's a bug.

In `git status -s`, it shows what have been changed from `HEAD` to `index`. In `repo.index.diff("HEAD")`, it shows what have been changed from `index` to `HEAD`.

To get the right diff, you may use `repo.index.diff("HEAD", R=True)` instead.

**Comment by Byron** [comment]
Maybe [this part of the docs helps to clarify](https://gitpython.readthedocs.io/en/stable/tutorial.html#obtaining-diff-information) what it is doing. 

Do you still think the behaviour is incorrect?
