### ISSUE TITLE
how to use git submodule foreach and its variables

### ISSUE THREAD

**Issue by 3nids** [gitpython-developers/GitPython#886]
Not strictly an issue, but I couldn't find anything in the doc and my understanding of the API is limited. Sorry if it's a stupid question.

I would like to use `repo.git.submodule('foreach', …)` and get the variables available such as `name`, `sm_path`, `displaypath`, `sha1` and `toplevel` as defined in the [git documentation](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt-foreach--recursiveltcommandgt).

**Comment by 3nids** [comment]
I cross-posted on stack-overflow as it might be nice to leave a trace there as it might be more visible than a bugtracker on github.

**Comment by stsewd** [comment]
Sorry If I didn't understood the question, but I think you can do this with 

```
repo = git.Repo('foo/bar')
for sub in repo.submodules:
    pass
```

https://gitpython.readthedocs.io/en/stable/reference.html#git.repo.base.Repo.submodules

**Comment by 3nids** [comment]
hmmm...looks like I was overthinking it...
many thanks for your reply
