### ISSUE TITLE
Semantics of 'bare'

### ISSUE THREAD

**Issue by itsbluething** [gitpython-developers/GitPython#896]
Could I get the exact definition of a 'bare' repo versus one that isn't bare? I'm having trouble understanding the semantics of the flag- for example, `Repo.init(dirname)` initialized on a directory with no contents is not necessarily 'bare'.

**Comment by Byron** [comment]
In short, a bare repository is a repository without a working tree. [Here is the longer version](https://mijingo.com/blog/what-is-a-bare-git-repository).
