### ISSUE TITLE
GitPython wheel includes "py2" in filename, but doesn't support Python 2

### ISSUE THREAD

**Issue by toddmowen** [gitpython-developers/GitPython#898]
I'm not sure the proper conventions for using wheel to distribute packages, but the current artifact on PyPI is called `GitPython-2.1.12-py2.py3-none-any.whl`, implying support for Python 2. Although it's true that the "Meta" section on PyPI specifies Python >=3.0.

Is it possible to configure wheel to name it just with `py3` instead?

**Comment by olivierlefloch** [comment]
`2.1.12` specifies

```
Requires-Python: >=3.0, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
```

`2.1.11` specifies

```
Requires-Python: >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*
```

The changelog however does not mention removal of `2.7` support:

https://github.com/gitpython-developers/GitPython/blob/master/doc/source/changes.rst#2112---bugfixes-and-features

Python 2.7 support was dropped in

https://github.com/gitpython-developers/GitPython/issues/312

Perhaps doing this in a minor version was a bit heavy handed?

**Comment by stsewd** [comment]
BTW, python 2 support was kind of dropped in 2.1.11 https://github.com/gitpython-developers/GitPython/commit/7f08b7730438bde34ae55bc3793fa524047bb804#diff-c276fc3c4df38382ec884e59657b869dR125 (when using a unicode branch/tag name that will fail)

**Comment by Byron** [comment]
@olivierlefloch I absolutely agree, and apologies, and I have just released `v2.1.13` which returns python 2 support.

I am _trying_ to cut a new release `v3.0.0` which removes python 2 support, if I can manage to figure out all the places to edit to make that happen. For now I don't know how to turn off the `py2.` part in the whl filename, but I will keep trying 😅.

**Comment by dstine** [comment]
@Byron 
I did a quick experiment on the tip of master, and it appears that if you update `setup.cfg` to 
```
[bdist_wheel]
universal=0
```
then the python tag will be just `py3` instead of `py2.py3` and the resulting wheel filename is `GitPython-2.1.13-py3-none-any.whl`. Assuming you are building with Python 3.

You would still want to update `setup.py` as you did before, to change `python_requires` and `classifiers`.

**Comment by Byron** [comment]
Perfect, this works. Thanks so much, @dstine
