### ISSUE TITLE
Get the output of "git ls-remote --heads origin" with GitPython

### ISSUE THREAD

**Issue by inazir** [gitpython-developers/GitPython#909]
Hello,

I have been trying to get the remote branches, to be more precise the output of the following command `git ls-remote --heads origin`. But I haven't been successful so far. I have tried the following methods in the mean time, which don't serve my purpose.

`repo = git.Repo(my_git_path)`

#method 1
`current_branches = repo.git.branch('-a')`

#method 2
`current_branches = []`
`for ref in repo.git.branch('-r').split('\n'):`
`    current_branches.append(ref)`

Could anyone please help me with the issue?

**Comment by Byron** [comment]
If you are interested in the output of said git command and it's inconvenient to reproduce it with  the plumbing provided by GitPython, one can run and parse the output of the exact git command like so: `git.Repo(my_git_path).git.ls_remote(heads = 'origin')`.
More information about this can be found [in the docs](https://gitpython.readthedocs.io/en/stable/tutorial.html#using-git-directly).

I am closing the issue, please feel free to use the commends for follow-up questions or remarks.
