### ISSUE TITLE
GitPython reports no remote 'origin'

### ISSUE THREAD

**Issue by adrianbn** [gitpython-developers/GitPython#910]
Hi,

I've been seeing the following error pop up every now and then. GitPython `3.0.0` fails to identify the remote `origin` even though it is there. 
```
>>> from os import system
>>> system('git remote')
origin
0
>>> from git import Repo
>>> repo = Repo('.')
>>> repo.remotes
[]
```
The stacktrace shows the following:
```
  File "/usr/local/lib/python3.6/site-packages/git/util.py", line 889, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin'
```

I don't exactly know why this happens. But a few of our repositories get into this state on occasion. We're running on Python 3.6 @ CentOS 7.

Thanks!

**Comment by Byron** [comment]
Thanks for posting! I am tentatively acknowledging the issue based on the assumption that certain `git` repositories store their references in a format GitPython cannot yet parse.

In order to fix the issue, one would have to provide an example making the issue reproducible. Usually refs are stored in the `.git` folder, and one should find them wherever they are with `grep -r origin .git/`, which yields this on my system.

```
.git//config:[remote "origin"]
.git//config:   fetch = +refs/heads/*:refs/remotes/origin/*
.git//config:   remote = origin
.git//info/refs:4dece994f099bad28f12714698088b81835c24bf        refs/remotes/origin/master
.git//packed-refs:4dece994f099bad28f12714698088b81835c24bf refs/remotes/origin/master
```
I suspect the `packed-refs` file to be in a format that is not understood.

**Comment by adrianbn** [comment]
Hey @Byron,

a fresh clone of the repositories in question fixed the issue so I can't get you a `packed-refs` file at the moment. If / when this surfaces again I will be happy to upload one.

**Comment by Byron** [comment]
Thanks, @panterozo .
Could you tell me how the first line of .git/packed-refs look like?
Mine is `# pack-refs with: peeled fully-peeled sorted` for example. Maybe there is something unusual that prevents GitPython to parse the file.

**Comment by Byron** [comment]
As part of spring cleaning, I am closing this issue as it was opened more than half a year ago while still asking for feedback.

If this is a mistake or any other action should rather be taken, please let me know in the comments or create a new issue as digest of this one.
Thanks for your understanding and the work that undoubtedly went into this.
