### ISSUE TITLE
how can I add username and password?

### ISSUE THREAD

**Issue by testforgity** [gitpython-developers/GitPython#912]
Git always askes me to write username and password so my program can't push into git. How can I improve it?

**Comment by testforgity** [comment]
Maybe I missed some information about this problem in GitPython's api

**Comment by Byron** [comment]
What kind of repository URL are you using, and which OS are you using?

I assume it's HTTPS for the time being. The way it works for me is to enter the credentials once, it will store it in the keychain, which subsequently can be used by git. I would expect this to be working similarly when git is used by another program.

I am closing the issue as it is a question, please feel free to keep using the comments for further clarification.
