### ISSUE TITLE
Class Documentation ?

### ISSUE THREAD

**Issue by linceaerian** [gitpython-developers/GitPython#981]
Hello Maintainers :)

Is it me or you do not have any documentation of the sources on the readthedoc ?

I thought it should be in https://gitpython.readthedocs.io/en/stable/reference.html#
but it's empty....

For instance i'm searching if `gitpython.repo/remote.push` returns a boolean or not but I do not find any class documentation, just the tuto (which are usefull nevertheless :) )

Maybe It's not really necessary as we can always search inside the code but.... sphinx allow it directly as long as you comment your code (which is already done for what I've seen).

Regards

**Comment by scottj97** [comment]
I was just about to file the same issue. The API reference seems broken.

**Comment by Harmon758** [comment]
The Read the Docs Python interpreter needs to be set to CPython 3.x rather than CPython 2.x in the project's advanced settings.

For now, you can refer to https://gitpython.readthedocs.io/en/3.0.5/reference.html instead.

@Byron Can you add [me](https://readthedocs.org/profiles/Harmon758/) as a maintainer for the RtD project at https://readthedocs.org/dashboard/gitpython/users/?

**Comment by stsewd** [comment]
I'd recommend using a config file for rtd https://docs.readthedocs.io/en/stable/config-file/v2.html, so there is not need to touch the dashboard

**Comment by Harmon758** [comment]
That wouldn't work retroactively for v3.0.6 and v3.0.7.
I also don't really see a need to add a configuration file just for that setting.
I'd also like to activate the latest version as well. I'm not sure why it's private, but it would help to catch issues with the documentation prior to releases.

**Comment by Byron** [comment]
Thanks for pointing this out, and thanks everyone for your input!

@Harmon758 is now a maintainer on readthedocs, and while I was there I took the opportunity to change the python interpreter to 3.x, and rebuilt a bunch of past versions.

![Screenshot 2020-02-13 at 07 03 05](https://user-images.githubusercontent.com/63622/74385768-45d15e80-4e2f-11ea-94ed-1c0d6a1a9dff.png)


By the looks of it, the class documentation is back.

**Comment by Harmon758** [comment]
I'm going to close this now as the issue has been resolved.
It's also not really related to or dependent upon the release of v3.0.8.

I've also made [the latest version](https://gitpython.readthedocs.io/en/latest/) public.
