### ISSUE TITLE
Noticed this on git for windows

### ISSUE THREAD

**Issue by jamesharris-garmin** [gitpython-developers/GitPython#982]
https://github.com/gitpython-developers/GitPython/blob/3c40cf5e83e56e339ec6ab3e75b008721e544ede/git/cmd.py#L560

This comment is inaccurate because the first three numbers are inaccurate because my current git version is `2.23.0.windows.1`  which causes a major failure trying to convert windows to an int.

Might I suggest attempting to convert with an inline method?:

```python
def safe_int(int_maybe: str):
    try:
        return int(int_maybe)
    except ValueError:
        return int_maybe

self._version_info = tuple(safe_int(n) for n in version_numbers.split('.'))
```

Then you can convert the whole version tuple.  (just not in a particularly useful pattern.)  that or only return the first 3 version numbers?

**Comment by jamesharris-garmin** [comment]
terrible thing: I'm stuck on python 2.7 for the time being so I found this as far back as 2.1.1.

**Comment by Byron** [comment]
Thanks for reporting, would you mind providing a PR or this one?

**Comment by jamesharris-garmin** [comment]
Looks like 6a61110053bca2bbf605b66418b9670cbd555802 fixes the issue. Looks like this isn't in the 2.x branch.

**Comment by jamesharris-garmin** [comment]
https://github.com/gitpython-developers/GitPython/blob/3c40cf5e83e56e339ec6ab3e75b008721e544ede/git/cmd.py#L562 appears to address the issue but it is not in the released versions on pypi. (at least not in 2.1.1 through 2.1.14)

**Comment by jamesharris-garmin** [comment]
😫 This was a configuration issue on my host machine. For some reason my python 2.7 install had version 0.3.2rc1 installed in the global version and this version was trumping what was in my virtualenvironment. I'm not sure how that happens but it did.
