### ISSUE TITLE
[BUG] Nano editor is not opened if triggered by git command

### ISSUE THREAD

**Issue by oerp-odoo** [gitpython-developers/GitPython#995]
If triggered command must open editor, like write commit message, process goes into waiting without opening anything.

_I noticed this specifically with **Nano** editor only. For example, with Sublime, it does work and opens editor._

For example, let say current directory is git repo directory.

This does not work:

```python
import git
git.Repo('.').git.commit('--amend')
```
Running such script, it goes in pending state where it never finishes and never opens editor.

This works (if I directly run git via subprocess):

```python
import subprocess
import shutil
subprocess.run([shutil.which('git'), 'commit', '--amend'])
```

My editor global settings look like this:

```
[core]
	editor = nano -w
```

git python version: 3.0.2

**Comment by Byron** [comment]
Thanks for the detailed description of the issue.

I think this related to how GitPython starts Git as a subprocess - it usually connects stdin and stdout, overriding the default terminal connection.

Given that the script above is essentially `git commit --amend` in a shell of your choice, I don't see the need to use GitPython for that, which does not try to be suited for interactive use of the git command it invokes.

Having said that, I am closing the issue, but invite you to make clear why GitPython should be able to support this case. 
Thanks for your understanding

**Comment by oerp-odoo** [comment]
Well in my case, I have written a script that automates some git actions.
And for that I use gitPython. One of the actions is git commit, where there
is ant option to open editor for user, so he could confirm if commit
message is correct and edit if needed.

To me, it does not make sense that gitPython behaves differently with Nano
than other editors like Sublime.

Its perfectly normal action to open editor when running a script. For
example when creating tag and allowing user to write a message etc.

And you say gitPython is not suited for interactive use. Why is that? I
thought it was just a better subprocess version specifically suited for git
commands?

**Comment by Byron** [comment]
GitPython will always [collect the git process' output](https://github.com/gitpython-developers/GitPython/blob/master/git/cmd.py#L586:L586), which is what prevents it from being connected to the terminal. That is needed for most interaction though. Maybe there is a way around it if the subprocess specifically connects to the terminal, as specified in the `TTY` environment variable, but that's something most programs don't implement.

In your case it's probably best to call git yourself, and it should be most portable if `git.Git.GIT_PYTHON_GIT_EXECUTABLE` is used. It will be a working git on most systems, and GitPython seems to jump through quite some hoops to get there.
